"""Unit tests for lairs._codegen.emit."""

from __future__ import annotations

import importlib.util
import sys
from typing import TYPE_CHECKING

from lairs._codegen import emit
from lairs._codegen.emit import emit_module
from lairs._codegen.schema_to_spec import FieldSpec, ModelSpec, VariantSpec

if TYPE_CHECKING:
    from pathlib import Path
    from types import ModuleType

_HASH = "deadbeefcafef00d"


def _load_module(text: str, tmp_path: Path, name: str) -> ModuleType:
    """Write emitted text to a file and import it as a real module.

    Importing rather than ``exec`` avoids inheriting the test module's
    ``from __future__ import annotations`` future flag, which would turn the
    emitted annotations into strings that didactic cannot classify.
    """
    path = tmp_path / f"{name}.py"
    path.write_text(text, encoding="utf-8")
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _model(name: str, fields: tuple[FieldSpec, ...]) -> ModelSpec:
    return ModelSpec(
        name=name,
        nsid="pub.layers.demo.demo",
        def_name="main",
        is_record=True,
        description=f"the {name}",
        fields=fields,
    )


def test_exports() -> None:
    assert set(emit.__all__) == {"emit_module"}


def test_header_carries_marker_and_hash() -> None:
    text = emit_module([_model("Demo", ())], manifest_hash=_HASH)
    assert text.startswith("# generated by lairs gen; do not edit")
    assert _HASH in text


def test_emitted_module_is_importable_python(tmp_path: Path) -> None:
    fields = (
        FieldSpec(name="text", type_kind="str", required=True, description="text"),
        FieldSpec(name="count", type_kind="int", minimum=0, maximum=5),
        FieldSpec(name="flag", type_kind="bool"),
    )
    text = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    module = _load_module(text, tmp_path, "emit_demo_module")
    demo = module.Demo
    instance = demo(text="hi")
    assert demo.model_validate(instance.model_dump()) == instance


def test_emitted_field_metadata_is_preserved(tmp_path: Path) -> None:
    fields = (
        FieldSpec(
            name="kind",
            type_kind="str",
            known_values=("a", "b"),
            string_format="at-uri",
        ),
    )
    text = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    module = _load_module(text, tmp_path, "emit_metadata_module")
    spec = module.Demo.__field_specs__["kind"]
    assert spec.extras["knownValues"] == ("a", "b")
    assert spec.extras["format"] == "at-uri"


def test_emitted_union_is_a_tagged_union(tmp_path: Path) -> None:
    union = ModelSpec(
        name="Sel",
        nsid="pub.layers.demo.demo",
        def_name="holder.selector",
        is_union=True,
        discriminator="kind",
        variants=(
            VariantSpec(discriminator_value="quote", class_name="SelQuote", target="Q"),
        ),
    )
    member = ModelSpec(
        name="Q",
        nsid="pub.layers.demo.demo",
        def_name="quote",
    )
    text = emit_module([member, union], manifest_hash=_HASH)
    module = _load_module(text, tmp_path, "emit_union_module")
    sel = module.Sel
    assert sel.__discriminator__ == "kind"
    assert "quote" in sel.__variants__


def test_emission_is_deterministic() -> None:
    fields = (FieldSpec(name="text", type_kind="str", required=True),)
    first = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    second = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    assert first == second


def test_overlong_description_keeps_an_e501_suppression() -> None:
    long_text = "word " * 40
    fields = (
        FieldSpec(name="text", type_kind="str", required=True, description=long_text),
    )
    text = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    over_length = [
        line
        for line in text.split("\n")
        if "word word" in line and len(line) > 88 and "# noqa: E501" not in line
    ]
    assert over_length == []
    assert "# noqa: E501" in text


def test_quote_and_backslash_in_description_are_escaped(tmp_path: Path) -> None:
    fields = (
        FieldSpec(
            name="text",
            type_kind="str",
            required=True,
            description='a "quoted" path C:\\x and a """ triple',
        ),
    )
    text = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    # the emitted module imports cleanly, proving the escaping is valid python
    module = _load_module(text, tmp_path, "emit_escape_module")
    spec = module.Demo.__field_specs__["text"]
    assert spec.description == 'a "quoted" path C:\\x and a """ triple'


def test_optional_array_emits_default_factory_tuple(tmp_path: Path) -> None:
    item = FieldSpec(name="tag", type_kind="str", required=True)
    fields = (FieldSpec(name="tags", type_kind="array", item=item),)
    text = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    assert "default_factory=tuple," in text
    module = _load_module(text, tmp_path, "emit_array_default_module")
    assert module.Demo().tags == ()


def test_bytes_field_emits_opaque(tmp_path: Path) -> None:
    fields = (FieldSpec(name="payload", type_kind="bytes", required=True),)
    text = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    assert "opaque=True," in text
    module = _load_module(text, tmp_path, "emit_bytes_module")
    instance = module.Demo(payload=b"abc")
    assert module.Demo.model_validate(instance.model_dump()) == instance


def test_array_of_embed_element_annotation(tmp_path: Path) -> None:
    item = FieldSpec(name="inner", type_kind="embed", target="Inner", required=True)
    holder_fields = (FieldSpec(name="inners", type_kind="array", item=item),)
    holder = ModelSpec(
        name="Holder",
        nsid="pub.layers.demo.demo",
        def_name="holder",
        fields=holder_fields,
    )
    inner = ModelSpec(
        name="Inner",
        nsid="pub.layers.demo.demo",
        def_name="inner",
        fields=(FieldSpec(name="x", type_kind="str", required=True),),
    )
    text = emit_module([inner, holder], manifest_hash=_HASH)
    assert "tuple[dx.Embed[Inner], ...]" in text
    module = _load_module(text, tmp_path, "emit_array_embed_module")
    instance = module.Holder(inners=(module.Inner(x="a"),))
    assert module.Holder.model_validate(instance.model_dump()) == instance
