"""Unit tests for lairs._codegen.emit."""

from __future__ import annotations

import importlib.util
import sys
from typing import TYPE_CHECKING

from lairs._codegen import emit
from lairs._codegen.emit import emit_module
from lairs._codegen.schema_to_spec import FieldSpec, ModelSpec, VariantSpec

if TYPE_CHECKING:
    from pathlib import Path
    from types import ModuleType

_HASH = "deadbeefcafef00d"


def _load_module(text: str, tmp_path: Path, name: str) -> ModuleType:
    """Write emitted text to a file and import it as a real module.

    Importing rather than ``exec`` avoids inheriting the test module's
    ``from __future__ import annotations`` future flag, which would turn the
    emitted annotations into strings that didactic cannot classify.
    """
    path = tmp_path / f"{name}.py"
    path.write_text(text, encoding="utf-8")
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _model(name: str, fields: tuple[FieldSpec, ...]) -> ModelSpec:
    return ModelSpec(
        name=name,
        nsid="pub.layers.demo.demo",
        def_name="main",
        is_record=True,
        description=f"the {name}",
        fields=fields,
    )


def test_exports() -> None:
    assert set(emit.__all__) == {"emit_module"}


def test_header_carries_marker_and_hash() -> None:
    text = emit_module([_model("Demo", ())], manifest_hash=_HASH)
    assert text.startswith("# generated by lairs gen; do not edit")
    assert _HASH in text


def test_emitted_module_is_importable_python(tmp_path: Path) -> None:
    fields = (
        FieldSpec(name="text", type_kind="str", required=True, description="text"),
        FieldSpec(name="count", type_kind="int", minimum=0, maximum=5),
        FieldSpec(name="flag", type_kind="bool"),
    )
    text = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    module = _load_module(text, tmp_path, "emit_demo_module")
    demo = module.Demo
    instance = demo(text="hi")
    assert demo.model_validate(instance.model_dump()) == instance


def test_emitted_field_metadata_is_preserved(tmp_path: Path) -> None:
    fields = (
        FieldSpec(
            name="kind",
            type_kind="str",
            known_values=("a", "b"),
            string_format="at-uri",
        ),
    )
    text = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    module = _load_module(text, tmp_path, "emit_metadata_module")
    spec = module.Demo.__field_specs__["kind"]
    assert spec.extras["knownValues"] == ("a", "b")
    assert spec.extras["format"] == "at-uri"


def test_emitted_union_is_a_tagged_union(tmp_path: Path) -> None:
    union = ModelSpec(
        name="Sel",
        nsid="pub.layers.demo.demo",
        def_name="holder.selector",
        is_union=True,
        discriminator="kind",
        variants=(
            VariantSpec(discriminator_value="quote", class_name="SelQuote", target="Q"),
        ),
    )
    member = ModelSpec(
        name="Q",
        nsid="pub.layers.demo.demo",
        def_name="quote",
    )
    text = emit_module([member, union], manifest_hash=_HASH)
    module = _load_module(text, tmp_path, "emit_union_module")
    sel = module.Sel
    assert sel.__discriminator__ == "kind"
    assert "quote" in sel.__variants__


def test_emission_is_deterministic() -> None:
    fields = (FieldSpec(name="text", type_kind="str", required=True),)
    first = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    second = emit_module([_model("Demo", fields)], manifest_hash=_HASH)
    assert first == second
