# generated by lairs gen; do not edit
"""Generated record models, one module per ``pub.layers.*`` namespace.

This package is emitted by ``lairs gen`` from the vendored lexicons. Each
module mirrors one lexicon namespace; nothing here is hand-authored.
"""

from __future__ import annotations

from lairs.records._generated import (
    alignment,
    annotation,
    changelog,
    corpus,
    defs,
    eprint,
    expression,
    graph,
    judgment,
    media,
    ontology,
    persona,
    resource,
    segmentation,
)

__all__ = [
    "alignment",
    "annotation",
    "changelog",
    "corpus",
    "defs",
    "eprint",
    "expression",
    "graph",
    "judgment",
    "media",
    "ontology",
    "persona",
    "resource",
    "segmentation",
]
