# generated by lairs gen; do not edit
# lexicon tree hash 1407dd60301c40d7da0f2996197f4cdc49f2ea76d811ea3ec46ecae8f8a8eec6
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.acquisition lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AccessCondition,
    AnnotationMetadata,
    DeviceInfo,
    EthicsApproval,
    FeatureMap,
    KnowledgeRef,
    LanguageRef,
    Licensing,
    ObjectRef,
    ReproducibilityInfo,
    Uuid,
)
from lairs.records._generated.judgment import PresentationSpec

__all__ = [
    "Consent",
    "LanguageCompetence",
    "Participant",
    "Run",
    "Session",
    "Stream",
]


class Consent(dx.Model):
    """The basis on which a participant's data may be published and redistributed, and how identifiable the retained data is. Separate from licensing, which governs the artifact, and from accessCondition, which governs the gate: a licence permits reuse, consent permits existence, an access condition permits retrieval, and all three must hold. Absent from all 26 record types in 0.8.0."""  # noqa: E501

    ethicsApprovals: tuple[dx.Embed[EthicsApproval], ...] | None = dx.field(
        default_factory=tuple,
        description="Approvals this consent falls under, reusing pub.layers.defs#ethicsApproval rather than declaring a second shape.",  # noqa: E501
    )
    expiresAt: datetime | None = dx.field(
        default=None,
        description="When consent expires, if it does.",
        extras={"format": "datetime"},
    )
    grantedAt: datetime | None = dx.field(
        default=None,
        description="When consent was granted. MAY be coarsened for de-identification.",
        extras={"format": "datetime"},
    )
    identifiability: str = dx.field(
        description="How identifiable the retained data is (fallback when the Uri is unavailable). This decides whether the data may live in Layers at all. identifiable is a hard signal NOT to carry the bytes here: face video, unmodified voice, a full-head structural MRI and a clinically annotated iEEG montage are identifiable however the metadata is scrubbed, and a public PDS plus a firehose is the wrong container. Such data belongs behind media.externalUri with a matching accessCondition, with Layers holding only the description.",  # noqa: E501
        extras={
            "knownValues": (
                "anonymous",
                "pseudonymous",
                "de-identified",
                "identifiable",
                "not-reported",
            ),
            "maxLength": 64,
        },
    )
    identifiabilityUri: str | None = dx.field(
        default=None,
        description="AT-URI of the identifiability definition node.",
        extras={"format": "at-uri"},
    )
    notes: str | None = dx.field(
        default=None,
        description="Free-text consent detail the typed fields do not capture.",
        extras={"maxLength": 4096},
    )
    scope: str = dx.field(
        description="What redistribution the participant agreed to (fallback when scopeUri unavailable). not-redistributable and controlled-access are declarations that the underlying bytes MUST NOT be carried as a Layers blob and MUST instead be referenced by media.externalUri pointing at a gated repository.",  # noqa: E501
        extras={
            "knownValues": (
                "public",
                "research-only",
                "restricted",
                "controlled-access",
                "not-redistributable",
                "not-reported",
            ),
            "maxLength": 128,
        },
    )
    scopeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the redistribution scope definition node (typeDef of consent-scope at layers-acquisition.ontology.layers.pub).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    status: str = dx.field(
        description="Current status (fallback when statusUri unavailable). A consumer MUST NOT redistribute data whose status is withdrawn.",  # noqa: E501
        extras={
            "knownValues": (
                "granted",
                "granted-with-restrictions",
                "withdrawn",
                "expired",
                "not-reported",
            ),
            "maxLength": 64,
        },
    )
    statusUri: str | None = dx.field(
        default=None,
        description="AT-URI of the consent status definition node.",
        extras={"format": "at-uri"},
    )
    withdrawalContact: str | None = dx.field(
        default=None,
        description="Where a withdrawal request should be sent: a URL or an institutional address, never a personal one.",  # noqa: E501
        extras={"maxLength": 512},
    )
    withdrawnAt: datetime | None = dx.field(
        default=None,
        description="When consent was withdrawn. Its presence obliges the publisher to delete or tombstone the associated records and obliges every indexer to suppress them. It does NOT and cannot guarantee erasure: a record broadcast on the firehose or pulled by getRepo is outside the publisher's control, and Layers is a read-only indexer with no authority over third-party consumers. The normative consequence belongs stated rather than implied: do not write into a Layers record anything whose later erasure you would need to guarantee.",  # noqa: E501
        extras={"format": "datetime"},
    )


class LanguageCompetence(dx.Model):
    """One language in a participant's repertoire, with the role it plays and how it was acquired. Composes pub.layers.defs#languageRef rather than re-declaring tag, script and grounding."""  # noqa: E501

    ageOfAcquisitionMonths: int | None = dx.field(
        default=None,
        description="Age of first exposure in whole months.",
        extras={"minimum": 0},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Competence detail not yet promoted to a typed field.",
    )
    language: dx.Embed[LanguageRef] = dx.field(
        description="The language, including sign languages (ase, bfi, gsg). Its role field carries l1, l2, heritage, signed-l1 and signed-l2: a hearing L2 signer and a deaf L1 signer are different participants for essentially every research question in the field.",  # noqa: E501
    )
    proficiency: str | None = dx.field(
        default=None,
        description="Proficiency slug (fallback when proficiencyUri unavailable).",
        extras={
            "knownValues": (
                "native",
                "near-native",
                "advanced",
                "intermediate",
                "beginner",
                "receptive-only",
                "not-reported",
            ),
            "maxLength": 64,
        },
    )
    proficiencyUri: str | None = dx.field(
        default=None,
        description="AT-URI of the proficiency scale point definition node (typeDef of proficiency at layers-acquisition.ontology.layers.pub).",  # noqa: E501
        extras={"format": "at-uri"},
    )


class Participant(dx.Model):
    """A research participant, subject, speaker, signer, or consultant. A separate record rather than a hierarchy level for three reasons: the same person recurs across studies, so a node with one parent cannot hold them; withdrawal must delete one record rather than collapse a level; and consent-bearing data about a third party must never be embedded in records that cannot be individually erased. DE-IDENTIFICATION IS BY CONSTRUCTION: this record carries no name, no e-mail, no DID, no date of birth and no free-text identifier field, because Layers records live in public PDSes and are broadcast on the firehose, so anything written here must be safe to publish at the moment it is written. A publisher who cannot satisfy that MUST reference a gated external repository through media.externalUri with access.mode set accordingly."""  # noqa: E501

    access: dx.Embed[AccessCondition] | None = dx.field(
        default=None,
        description="Conditions under which this participant's data may be obtained, when narrower than the collection's.",  # noqa: E501
    )
    ageIsCapped: bool | None = dx.field(
        default=None,
        description="True when ageMonths is clamped and the true value is greater. Distinguishes a clamped 89-year-old from a real one.",  # noqa: E501
    )
    ageMonths: int | None = dx.field(
        default=None,
        description="Age at first participation in whole months, so infant, child-language and animal work is expressible without floats; NWB Subject.age uses an ISO 8601 duration for the same reason. BIDS caps participants.tsv age at 89 years for privacy, so values above 1068 SHOULD be clamped with ageIsCapped set. In small or clinical populations age alone is a quasi-identifier and may legitimately be omitted.",  # noqa: E501
        extras={"minimum": 0},
    )
    ageReference: str | None = dx.field(
        default=None,
        description="What ageMonths is measured from (fallback when the Uri is unavailable). NWB Subject.age__reference, which takes birth or gestational. Load-bearing for infant work, where the two differ by months.",  # noqa: E501
        extras={
            "knownValues": (
                "birth",
                "gestational",
                "post-natal-day",
                "unknown",
            ),
            "maxLength": 64,
        },
    )
    ageReferenceUri: str | None = dx.field(
        default=None,
        description="AT-URI of the age reference definition node.",
        extras={"format": "at-uri"},
    )
    consent: dx.Embed[Consent] = dx.field(
        description="REQUIRED. The basis on which this participant's data may be published and redistributed. Required rather than optional because a participant record with no consent declaration is a claim about a person with no stated warrant, and no consumer can tell an unrecorded consent from an absent one.",  # noqa: E501
    )
    createdAt: datetime = dx.field(
        description="When this participant record was created.",
        extras={"format": "datetime"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Study-specific variables (education, clinical group, screening scores). Keys SHOULD be declared as a column schema on the containing collection. MUST NOT reintroduce a direct identifier the typed fields deliberately omit.",  # noqa: E501
    )
    gender: str | None = dx.field(
        default=None,
        description="Self-reported gender slug (fallback when genderUri unavailable). No BIDS or NWB counterpart; added because sociolinguistic and psycholinguistic work routinely collects it and would otherwise put it in an untyped feature.",  # noqa: E501
        extras={
            "knownValues": (
                "woman",
                "man",
                "non-binary",
                "other",
                "not-reported",
                "undisclosed",
            ),
            "maxLength": 64,
        },
    )
    genderUri: str | None = dx.field(
        default=None,
        description="AT-URI of the gender definition node.",
        extras={"format": "at-uri"},
    )
    genotype: str | None = dx.field(
        default=None,
        description="Genotype for non-human subjects. NWB Subject.genotype.",
        extras={"maxLength": 512},
    )
    handedness: str | None = dx.field(
        default=None,
        description="Handedness slug (fallback when handednessUri unavailable). BIDS participants.tsv handedness, a near-universal inclusion criterion in neurolinguistic work.",  # noqa: E501
        extras={
            "knownValues": (
                "right",
                "left",
                "ambidextrous",
                "not-reported",
                "undisclosed",
            ),
            "maxLength": 64,
        },
    )
    handednessScore: int | None = dx.field(
        default=None,
        description="Laterality quotient scaled to per mille, so an Edinburgh Handedness Inventory score of -100.0 to +100.0 becomes -1000 to 1000.",  # noqa: E501
        extras={"minimum": -1000, "maximum": 1000},
    )
    handednessUri: str | None = dx.field(
        default=None,
        description="AT-URI of the handedness definition node.",
        extras={"format": "at-uri"},
    )
    hearingStatus: str | None = dx.field(
        default=None,
        description="Hearing status slug (fallback when the Uri is unavailable). No BIDS or NWB counterpart; load-bearing for sign language and speech perception research, where it is a defining participant variable.",  # noqa: E501
        extras={
            "knownValues": (
                "hearing",
                "deaf",
                "hard-of-hearing",
                "deafblind",
                "not-reported",
                "undisclosed",
            ),
            "maxLength": 64,
        },
    )
    hearingStatusUri: str | None = dx.field(
        default=None,
        description="AT-URI of the hearing status definition node.",
        extras={"format": "at-uri"},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="External grounding: ncbi-taxonomy for species, rrid for strain. MUST NOT carry an ORCID or any identifier resolving to a named human, which is what distinguishes this field from every other knowledgeRefs field in the lexicon.",  # noqa: E501
    )
    languageProfiles: tuple[dx.Embed[LanguageCompetence], ...] | None = dx.field(
        default_factory=tuple,
        description="Per-language background, each a pub.layers.acquisition.defs#languageCompetence. A bare BCP-47 array cannot distinguish an L1 Finnish speaker with late L2 English from a simultaneous bilingual, and that distinction is the point of most of the research this record serves.",  # noqa: E501
    )
    languageRefs: tuple[dx.Embed[LanguageRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Structured language references complementing languages, each a pub.layers.defs#languageRef. Carries a variety below the language level and grounding of a languoid whose identity is contested, which a bare BCP-47 tag cannot. No array-level cap; the record size limit governs.",  # noqa: E501
    )
    languages: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Canonical BCP-47 tags this participant produced or comprehended data in, including sign language tags. A flat facet for filtering; languageProfiles carries the structure. No array-level cap, since a multilingual consultant's repertoire has no natural bound; the record size limit governs.",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who created this participant record, with what tool.",
    )
    participantId: str = dx.field(
        description="Pseudonymous identifier, stable within the authoring repo and meaningless outside it (sub-01, P17). BIDS participant_id, REQUIRED and the first column of participants.tsv. MUST NOT be a name, an e-mail address, a DID, a handle, an institutional identifier, a worker-platform identifier that resolves to an account, or any string derived from a birth date.",  # noqa: E501
        extras={"maxLength": 128},
    )
    sex: str | None = dx.field(
        default=None,
        description="Biological sex as recorded by the study (fallback when sexUri unavailable). BIDS participants.tsv sex; NWB Subject.sex. Deliberately distinct from gender, because collapsing them is both scientifically and ethically wrong.",  # noqa: E501
        extras={
            "knownValues": (
                "female",
                "male",
                "intersex",
                "other",
                "not-reported",
                "undisclosed",
            ),
            "maxLength": 64,
        },
    )
    sexUri: str | None = dx.field(
        default=None,
        description="AT-URI of the sex definition node.",
        extras={"format": "at-uri"},
    )
    species: str | None = dx.field(
        default=None,
        description="Species slug (fallback when speciesUri unavailable). BIDS participants.tsv species, which expects an NCBI Taxonomy binomial; NWB Subject.species. Ground the binomial through knowledgeRefs with source ncbi-taxonomy rather than minting Layers-local nodes.",  # noqa: E501
        extras={
            "knownValues": (
                "homo-sapiens",
                "macaca-mulatta",
                "macaca-fascicularis",
                "pan-troglodytes",
                "mus-musculus",
                "rattus-norvegicus",
                "taeniopygia-guttata",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    speciesUri: str | None = dx.field(
        default=None,
        description="AT-URI of the species definition node. Grounded through knowledgeRefs with source ncbi-taxonomy rather than a Layers-local vocabulary.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    strainRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="Strain for non-human subjects, grounded via rrid. BIDS strain_rrid; NWB Subject.strain. No free-text twin: two encodings of one fact with no precedence rule is a conflict waiting to be written.",  # noqa: E501
    )
    visionStatus: str | None = dx.field(
        default=None,
        description="Vision status slug (fallback when the Uri is unavailable). Relevant to eye-tracking and reading studies, where corrected-to-normal is a routine inclusion criterion and correction type affects tracker performance.",  # noqa: E501
        extras={
            "knownValues": (
                "normal",
                "corrected-to-normal",
                "impaired",
                "blind",
                "not-reported",
                "undisclosed",
            ),
            "maxLength": 64,
        },
    )
    visionStatusUri: str | None = dx.field(
        default=None,
        description="AT-URI of the vision status definition node.",
        extras={"format": "at-uri"},
    )
    weightGrams: int | None = dx.field(
        default=None,
        description="Body weight in grams. NWB Subject.weight, kilograms upstream. Primarily an animal-work field; for humans it is a quasi-identifier in small samples and is usually better omitted.",  # noqa: E501
        extras={"minimum": 0},
    )


class Run(dx.Model):
    """An uninterrupted acquisition within a session, sharing acquisition parameters and task throughout. BIDS run-<index>. Also the grouping object a media.defs#motionInfo tracking system points at, addressed by uuid."""  # noqa: E501

    durationNanos: int | None = dx.field(
        default=None,
        description="Run duration in nanoseconds.",
        extras={"minimum": 0},
    )
    eventLayerRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.annotation.annotationLayer of kind tier carrying this run's trigger and event codes. This is where BIDS events.tsv lands.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Run-specific properties not yet promoted to a typed field.",
    )
    judgmentSetRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of pub.layers.judgment.judgmentSet records collected during this run.",  # noqa: E501
    )
    label: str | None = dx.field(
        default=None,
        description="Human-readable run name.",
        extras={"maxLength": 256},
    )
    runIndex: int | None = dx.field(
        default=None,
        description="0-based run number (ordinal) within the session.",
        extras={"minimum": 0},
    )
    startNanos: int | None = dx.field(
        default=None,
        description="Signed start on the session clock.",
    )
    streams: tuple[dx.Embed[ObjectRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Streams active during this run, as objectRefs into the session's streams.",  # noqa: E501
    )
    task: str | None = dx.field(
        default=None,
        description="Task slug for this run (fallback when taskUri unavailable), from the session task vocabulary.",  # noqa: E501
        extras={"maxLength": 128},
    )
    taskUri: str | None = dx.field(
        default=None,
        description="AT-URI of this run's task definition node, when it differs from the session's.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    uuid: dx.Embed[Uuid] = dx.field(
        description="Stable identifier for this run within this session. Required because a motion tracking system points at a run by uuid, and a name join cannot be validated.",  # noqa: E501
    )


class Stream(dx.Model):
    """One synchronized media stream within a session, with its offset against the session clock. The uuid is what an anchor's pub.layers.defs#mediaScope.stream objectRef points at, and what pub.layers.media.media#stream resolves to."""  # noqa: E501

    driftPartsPerBillion: int | None = dx.field(
        default=None,
        description="Signed measured clock drift against the session master, in parts per billion. Independent oscillators diverge measurably over an hour, and zero is a claim rather than a safe default.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Stream-specific properties not yet promoted to a typed field.",
    )
    mediaCid: str | None = dx.field(
        default=None,
        description="CID of the media revision this session's offsets were measured against, so a replaced recording is detectable rather than silently reinterpreted.",  # noqa: E501
        extras={"format": "cid"},
    )
    mediaRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.media.media carrying this stream.",
        extras={"format": "at-uri"},
    )
    offsetNanos: int | None = dx.field(
        default=None,
        description="Signed offset from the session clock's zero to this stream's first sample, session-relative and never UTC-epoch. Negative when the stream began before t=0, which BIDS StartTime explicitly permits. Duplicates media.sync.offsetNanos deliberately: the session is authoritative when the two disagree, because only the session sees all streams.",  # noqa: E501
    )
    participantRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.acquisition.participant this stream records, when the session has several and streams are per-participant.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    streamId: str | None = dx.field(
        default=None,
        description="Human-readable session-local label (cam-left, lapel-a, eeg, eyetrack-right, mocap-upper). Display cache, advisory: uuid is the join key.",  # noqa: E501
        extras={"maxLength": 64},
    )
    streamRole: str | None = dx.field(
        default=None,
        description="What this stream is FOR (fallback when streamRoleUri unavailable). Distinct from the medium's kind: two audio streams can be a close-talk and a room microphone, which are the same kind and not interchangeable.",  # noqa: E501
        extras={
            "knownValues": (
                "primary",
                "reference",
                "close-talk",
                "far-field",
                "room",
                "camera",
                "overhead",
                "face",
                "hands",
                "screen-capture",
                "neural",
                "physiological",
                "gaze",
                "motion",
                "articulatory",
                "stimulus",
                "trigger",
                "annotation-aid",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    streamRoleUri: str | None = dx.field(
        default=None,
        description="AT-URI of the stream role definition node (typeDef of stream-role at layers-acquisition.ontology.layers.pub).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    syncMethod: str | None = dx.field(
        default=None,
        description="How this stream was aligned (fallback when syncMethodUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "hardware-trigger",
                "shared-clock",
                "ltc-timecode",
                "clapperboard",
                "audio-cross-correlation",
                "ptp",
                "ntp",
                "manual",
                "unsynchronized",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    syncMethodUri: str | None = dx.field(
        default=None,
        description="AT-URI of the synchronization method definition node (typeDef of sync-method at layers-acquisition.ontology.layers.pub), the same node set as media.defs#syncInfo.clockSourceUri.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    syncUncertaintyNanos: int | None = dx.field(
        default=None,
        description="Estimated alignment uncertainty in nanoseconds. A hardware trigger and a clapperboard differ by three orders of magnitude, and a consumer needs it to know how far to trust a cross-stream anchor.",  # noqa: E501
        extras={"minimum": 0},
    )
    uuid: dx.Embed[Uuid] = dx.field(
        description="Stable identifier for this stream within this session. Required because media records and anchors point at streams, and a session-local label string is a name join that cannot be validated.",  # noqa: E501
    )


class Session(dx.Model):
    """One acquisition session. Corresponds to BIDS ses-<label>, a logical grouping of neuroimaging and behavioral data consistent across subjects, and to one NWB file, whose session_description, identifier and session_start_time are all required there and none of which has a home in Layers 0.8.0. Without this record a synchronized multi-stream recording is unrepresentable, and adding signal media alone would leave cross-stream annotation unanchorable."""  # noqa: E501

    access: dx.Embed[AccessCondition] | None = dx.field(
        default=None,
        description="Conditions under which this session's data may be obtained.",
    )
    clock: str | None = dx.field(
        default=None,
        description="What t=0 means (fallback when clockUri unavailable). Every stream offset and every anchor into this session is measured from it, so leaving it implicit would make every cross-stream anchor ambiguous.",  # noqa: E501
        extras={
            "knownValues": (
                "session-start",
                "first-stream-start",
                "master-stream-start",
                "first-trigger",
                "wall-clock",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    clockUri: str | None = dx.field(
        default=None,
        description="AT-URI of the session clock definition node.",
        extras={"format": "at-uri"},
    )
    consent: dx.Embed[Consent] | None = dx.field(
        default=None,
        description="Session-level consent when it differs from the participants' standing consent. Absent means the participants' declarations govern.",  # noqa: E501
    )
    createdAt: datetime = dx.field(
        description="When this session record was created.",
        extras={"format": "datetime"},
    )
    devices: tuple[dx.Embed[DeviceInfo], ...] | None = dx.field(
        default_factory=tuple,
        description="Instruments used, structured rather than a free-text device string; each a pub.layers.defs#deviceInfo.",  # noqa: E501
    )
    durationNanos: int | None = dx.field(
        default=None,
        description="Session duration in nanoseconds.",
        extras={"minimum": 0},
    )
    environment: str | None = dx.field(
        default=None,
        description="Recording environment slug (fallback when environmentUri unavailable). Determines what a consumer may assume about noise floor, lighting and electromagnetic interference.",  # noqa: E501
        extras={
            "knownValues": (
                "sound-booth",
                "laboratory",
                "field",
                "home",
                "classroom",
                "clinic",
                "mri-scanner",
                "meg-shielded-room",
                "operating-room",
                "online",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    environmentUri: str | None = dx.field(
        default=None,
        description="AT-URI of the recording environment definition node.",
        extras={"format": "at-uri"},
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of eprint records describing or associated with this session.",  # noqa: E501
    )
    ethicsApprovals: tuple[dx.Embed[EthicsApproval], ...] | None = dx.field(
        default_factory=tuple,
        description="Human-subjects or animal-care approvals this session was conducted under, each a pub.layers.defs#ethicsApproval (the shared def, reused rather than a bespoke shape). BIDS EthicsApprovals is an optional array of free-text strings upstream.",  # noqa: E501
    )
    experimentRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.judgment.experimentDef this session instantiates. An experimentDef is a type-level protocol; a session is the token event that ran it, and 0.8.0 has only the type level.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Protocol deviations, timestamp coarsening, surgery, pharmacology, stimulus notes. NWB protocol, surgery, virus, pharmacology, data_collection and stimulus_notes land here until any earns a typed field.",  # noqa: E501
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references for this session (task grounded via cognitive-atlas, site via ror).",  # noqa: E501
    )
    label: str | None = dx.field(
        default=None,
        description="Human-readable label. NWB session_description.",
        extras={"maxLength": 512},
    )
    languageRefs: tuple[dx.Embed[LanguageRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Structured language references complementing languages, each a pub.layers.defs#languageRef. No array-level cap; the record size limit governs.",  # noqa: E501
    )
    languages: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Canonical BCP-47 tags this session's data covers, including sign language tags. No array-level cap; the record size limit governs.",  # noqa: E501
    )
    licensing: dx.Embed[Licensing] | None = dx.field(
        default=None,
        description="Governs the artifact; consent governs the person; access governs the gate.",  # noqa: E501
    )
    masterStream: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="The stream whose clock defines t=0, when clock is master-stream-start. An objectRef whose recordRef is this session and whose objectId is the stream uuid.",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who created this session record, with what tool.",
    )
    participantRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of the pub.layers.acquisition.participant records recorded. An array because dialogue, interview, map-task and elicitation sessions have several, and each stream may belong to a different one.",  # noqa: E501
    )
    presentation: dx.Embed[PresentationSpec] | None = dx.field(
        default=None,
        description="How stimuli were displayed, including screen geometry, which gaze-on-screen eye-tracking requires and which BIDS places in the events sidecar StimulusPresentation object rather than on the tracker.",  # noqa: E501
    )
    reproducibility: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
        description="How the acquisition was driven computationally, plus funding, via the shared reproducibilityInfo shape. Session-level ethics approvals are carried by ethicsApprovals. BIDS Funding is a free-text string array upstream.",  # noqa: E501
    )
    runs: tuple[dx.Embed[Run], ...] | None = dx.field(
        default_factory=tuple,
        description="Sub-divisions of the session. BIDS run-<index>, an uninterrupted repetition of data acquisition with the same acquisition parameters and task. A session routinely spans several runs and, per BIDS Motion, several tracking systems at different sampling rates, which is why a session cannot carry one sampling rate.",  # noqa: E501
    )
    sessionId: str = dx.field(
        description="Stable session identifier within the authoring repo (ses-01, buckeye-s01-b03). BIDS session_id, REQUIRED in sessions.tsv; NWB session_id.",  # noqa: E501
        extras={"maxLength": 128},
    )
    siteRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="Institution or site, grounded via ror. Not an at-uri: an institution is an external entity Layers references, not a Layers record. NWB institution and lab.",  # noqa: E501
    )
    startedAt: datetime | None = dx.field(
        default=None,
        description="Acquisition start. BIDS sessions.tsv and scans.tsv acq_time; NWB session_start_time, required there. MAY be coarsened for de-identification; when it is, say so in features, because a consumer cannot otherwise distinguish a coarsened timestamp from a precise one.",  # noqa: E501
        extras={"format": "datetime"},
    )
    streams: tuple[dx.Embed[Stream], ...] = dx.field(
        description="The synchronized media streams making up this session. Inline rather than an edge record because a session is authored by one party who controls all its streams, the same reasoning that makes resource.templateComposition.members inline while corpus.membership is a record.",  # noqa: E501
    )
    task: str | None = dx.field(
        default=None,
        description="Task slug (fallback when taskUri unavailable). BIDS TaskName is REQUIRED in every EEG, MEG, iEEG and NIRS sidecar, yet 0.8.0's only task construct is judgment.experimentDef, reachable only from judgmentSet.experimentRef, so a neural recording with no behavioural judgments could not name what the participant was doing.",  # noqa: E501
        extras={
            "knownValues": (
                "rest",
                "naturalistic-listening",
                "naturalistic-viewing",
                "reading",
                "self-paced-reading",
                "acceptability-judgment",
                "picture-naming",
                "lexical-decision",
                "priming",
                "visual-world",
                "oddball",
                "elicitation",
                "free-conversation",
                "interview",
                "narrative",
                "map-task",
                "wordlist",
                "repetition",
                "production",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    taskUri: str | None = dx.field(
        default=None,
        description="AT-URI of the task definition node; ground to the Cognitive Atlas through knowledgeRefs where possible.",  # noqa: E501
        extras={"format": "at-uri"},
    )
