# generated by lairs gen; do not edit
# lexicon tree hash cedfb9f34cc55fb5be1abb81dda63fd6a6671af2efd6a5e5923fca0c77ba0fd1
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.alignment lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AlignmentLink,
    AnnotationMetadata,
    FeatureMap,
    KnowledgeRef,
    Licensing,
    ObjectRef,
    ReproducibilityInfo,
)

__all__ = [
    "Alignment",
]


class Alignment(dx.Model):
    """An alignment between two parallel sequences. The sequences can be tokenizations, annotation layers, expressions (for parallel text), or tiers. Links establish many-to-many correspondence between elements indexed by position."""  # noqa: E501

    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Eprint records (papers/preprints) describing or associated with this alignment.",  # noqa: E501
    )
    expression: str | None = dx.field(
        default=None,
        description="Primary expression context (for within-document alignments).",
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    kind: str = dx.field(
        description="Alignment kind slug (fallback). The type of alignment.",
        extras={
            "knownValues": (
                "tokenization-to-tokenization",
                "interlinear",
                "parallel-text",
                "audio-to-text",
                "layer-to-layer",
                "error-to-correction",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the alignment kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references for this alignment (e.g., alignment model, parallel corpus source).",  # noqa: E501
    )
    licensing: dx.Embed[Licensing] | None = dx.field(
        default=None,
        description="Licensing terms governing this alignment (supports dual/multi/component licensing).",  # noqa: E501
    )
    links: tuple[dx.Embed[AlignmentLink], ...] = dx.field(
        description="The alignment links.",
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
    reproducibility: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
        description="How this alignment was produced (code, commit, command, environment, seed).",  # noqa: E501
    )
    source: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="Reference to the source sequence. Use localId for within-segmentation tokenization UUID, recordRef for cross-record AT-URI (annotation layer, expression, etc.).",  # noqa: E501
    )
    sourceLang: str | None = dx.field(
        default=None,
        description="BCP-47 language tag for the source (for parallel text alignment).",
        extras={"maxLength": 64},
    )
    subkind: str | None = dx.field(
        default=None,
        description="Alignment subkind slug (fallback). More specific alignment type within the kind.",  # noqa: E501
        extras={
            "knownValues": (
                "word-to-morpheme",
                "word-to-word",
                "sentence-to-sentence",
                "phrase-to-phrase",
                "morpheme-to-gloss",
                "forced-alignment",
                "manual-alignment",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    subkindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the alignment subkind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    target: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="Reference to the target sequence. Use localId for within-segmentation tokenization UUID, recordRef for cross-record AT-URI.",  # noqa: E501
    )
    targetLang: str | None = dx.field(
        default=None,
        description="BCP-47 language tag for the target.",
        extras={"maxLength": 64},
    )
