# generated by lairs gen; do not edit
# lexicon tree hash c579e63d3ffd0d55171eeeef7fbee9254e184419ebdfbb1bddc4807310069330
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.annotation lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    Anchor,
    AnnotationMetadata,
    FeatureMap,
    KnowledgeRef,
    ObjectRef,
    SpatialExpression,
    TemporalExpression,
    Uuid,
)

__all__ = [
    "Annotation",
    "AnnotationLayer",
    "ArgumentRef",
    "Cluster",
    "ClusterSet",
]


class ArgumentRef(dx.Model):
    """A role/argument reference in a predicate-argument structure. Uses the composable objectRef to point to another annotation, either locally (same layer, by UUID) or remotely (cross-layer or cross-record, by AT-URI + UUID)."""  # noqa: E501

    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    role: str = dx.field(
        description="The argument role label (e.g., ARG0, Agent, Theme, CAUSE, connective, etc.).",  # noqa: E501
        extras={"maxLength": 256},
    )
    target: dx.Embed[ObjectRef] = dx.field(
        description="Reference to the annotation filling this role. Use localId for same-layer, recordRef+objectId for cross-layer.",  # noqa: E501
    )


class Annotation(dx.Model):
    """A single abstract annotation. The fields populated depend on the layer's kind/subkind. For token-tags: tokenIndex + label. For spans: anchor + label. For trees: anchor + label + parentId/childIds. For relations: anchor + arguments. For graphs: anchor + arguments or headIndex/targetIndex. This single type replaces the former tag, spanAnnotation, entityMention, situationMention, dependencyArc, parseNode, etc."""  # noqa: E501

    anchor: dx.Embed[Anchor] | None = dx.field(
        default=None,
        description="How this annotation attaches to the source data.",
    )
    arguments: tuple[dx.Embed[ArgumentRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Role/argument fillers for predicate-argument structures (FrameNet, PropBank, AMR, etc.). Each argument references another annotation.",  # noqa: E501
    )
    childIds: tuple[dx.Embed[Uuid], ...] | None = dx.field(
        default_factory=tuple,
        description="Child annotation UUIDs in tree structures.",
    )
    confidence: int | None = dx.field(
        default=None,
        description="Confidence score 0-1000.",
        extras={"minimum": 0, "maximum": 1000},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features. Use for domain-specific properties: phraseType, polarity, modality, tense, isEnhanced, morphological features, etc.",  # noqa: E501
    )
    headIndex: int | None = dx.field(
        default=None,
        description="Head/governor token index for directed arcs (dependency parsing). -1 for root.",  # noqa: E501
        extras={"minimum": -1},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Links to external knowledge bases.",
    )
    label: str | None = dx.field(
        default=None,
        description="The primary label (POS tag, entity type, frame name, constituent label, dependency relation, etc.).",  # noqa: E501
        extras={"maxLength": 512},
    )
    ontologyTypeRef: str | None = dx.field(
        default=None,
        description="Reference to a type definition in a pub.layers.ontology.",
        extras={"format": "at-uri"},
    )
    parentId: dx.Embed[Uuid] | None = dx.field(
        default=None,
        description="Parent annotation in tree structures (constituency, RST, etc.).",
    )
    spatial: dx.Embed[SpatialExpression] | None = dx.field(
        default=None,
        description="Structured spatial annotation. For spatial-expression and location-mention subkinds. Subsumes ISO-Space place annotations (ISO 24617-7), SpatialML PLACE elements, and GeoJSON/WKT geometries.",  # noqa: E501
    )
    targetIndex: int | None = dx.field(
        default=None,
        description="Dependent/target token index for directed arcs.",
        extras={"minimum": 0},
    )
    temporal: dx.Embed[TemporalExpression] | None = dx.field(
        default=None,
        description="Structured temporal annotation. For temporal-expression, temporal-value, and temporal-vagueness subkinds. Subsumes TimeML TIMEX3 and OWL-Time GeneralDateTimeDescription.",  # noqa: E501
    )
    text: str | None = dx.field(
        default=None,
        description="Surface text of the annotated span.",
        extras={"maxLength": 4096},
    )
    tokenIndex: int | None = dx.field(
        default=None,
        description="For token-level annotations: 0-based index into the tokenization.",
        extras={"minimum": 0},
    )
    uuid: dx.Embed[Uuid] = dx.field(
        description="generated field",
    )
    value: str | None = dx.field(
        default=None,
        description="Secondary value (lemma form, gloss, normalized temporal value, etc.).",  # noqa: E501
        extras={"maxLength": 4096},
    )


class AnnotationLayer(dx.Model):
    """A named layer of annotations over an expression. All annotation types use this single record type. The combination of kind, subkind, and formalism tells the appview how to render. Multiple layers can coexist for the same expression."""  # noqa: E501

    alternativesRef: str | None = dx.field(
        default=None,
        description="Reference to the top-ranked layer in a k-best group.",
        extras={"format": "at-uri"},
    )
    annotations: tuple[dx.Embed[Annotation], ...] = dx.field(
        description="The annotations in this layer.",
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    expression: str = dx.field(
        description="The expression this annotation layer applies to.",
        extras={"format": "at-uri"},
    )
    formalism: str | None = dx.field(
        default=None,
        description="Formalism slug (fallback when formalismUri unavailable). The linguistic formalism or annotation standard used.",  # noqa: E501
        extras={
            "knownValues": (
                "universal-dependencies",
                "penn-treebank",
                "stanford",
                "prague",
                "propbank",
                "framenet",
                "verbnet",
                "amr",
                "ucca",
                "rst",
                "erst",
                "sdrt",
                "pdtb",
                "timeml",
                "iso-space",
                "spatialml",
                "conll-u",
                "brat",
                "elan",
                "leipzig-glossing",
                "ipa",
                "tobi",
                "bpe",
                "sentencepiece",
                "unimorph",
                "wals",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    formalismUri: str | None = dx.field(
        default=None,
        description="AT-URI of the formalism definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    kind: str = dx.field(
        description="Primary annotation kind slug (fallback when kindUri unavailable). Determines the structural interpretation of annotations in this layer.",  # noqa: E501
        extras={
            "knownValues": (
                "token-tag",
                "span",
                "relation",
                "tree",
                "graph",
                "tier",
                "document-tag",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the annotation kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    labelSet: str | None = dx.field(
        default=None,
        description="Identifier for the label set used (e.g., 'universal-pos', 'ontonotes-ner', 'penn-treebank-pos').",  # noqa: E501
        extras={"maxLength": 256},
    )
    language: str | None = dx.field(
        default=None,
        description="BCP-47 language tag for this annotation layer, if different from the expression's language.",  # noqa: E501
        extras={"maxLength": 64},
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
    ontologyRef: str | None = dx.field(
        default=None,
        description="Reference to a pub.layers.ontology defining the types used in this layer.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    parentLayerRef: str | None = dx.field(
        default=None,
        description="For dependent/subordinate layers: the parent layer this one subdivides or refines. Supports ELAN-style tier dependencies, error-correction pairs, etc.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    rank: int | None = dx.field(
        default=None,
        description="Rank among k-best alternatives (1 = best).",
        extras={"minimum": 1},
    )
    sourceMethod: str | None = dx.field(
        default=None,
        description="How this annotation layer was produced (fallback when sourceMethodUri unavailable). Follows UD's per-layer annotation source tracking.",  # noqa: E501
        extras={
            "knownValues": (
                "manual-native",
                "manual-corrected",
                "automatic",
                "automatic-corrected",
                "converted",
                "converted-corrected",
                "crowd-sourced",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    sourceMethodUri: str | None = dx.field(
        default=None,
        description="AT-URI of the annotation source method definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    subkind: str | None = dx.field(
        default=None,
        description="Annotation subkind slug (fallback when subkindUri unavailable). The appview uses this for specialized rendering.",  # noqa: E501
        extras={
            "knownValues": (
                "pos",
                "xpos",
                "ner",
                "lemma",
                "morph",
                "supersense",
                "sense",
                "chunk",
                "speaker",
                "gloss",
                "phonetic",
                "prosody",
                "tobi",
                "language-id",
                "entity-mention",
                "situation-mention",
                "frame",
                "predicate",
                "discourse-unit",
                "speech-act",
                "temporal-expression",
                "temporal-signal",
                "spatial-expression",
                "spatial-signal",
                "spatial-relation",
                "location-mention",
                "sentiment",
                "emotion",
                "stance",
                "information-structure",
                "error",
                "correction",
                "code-switch",
                "highlight",
                "comment",
                "bookmark",
                "temporal-value",
                "temporal-vagueness",
                "dependency",
                "enhanced-dependency",
                "constituency",
                "ccg",
                "coreference",
                "bridging",
                "temporal-relation",
                "causal-relation",
                "discourse-relation",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    subkindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the annotation subkind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    tokenizationId: dx.Embed[Uuid] | None = dx.field(
        default=None,
        description="For token-aligned layers (kind=token-tag, dependency, constituency, etc.): the tokenization these annotations are aligned to.",  # noqa: E501
    )


class Cluster(dx.Model):
    """A cluster of annotations (e.g., coreferent entity mentions, situation mentions referring to the same situation)."""  # noqa: E501

    canonicalLabel: str | None = dx.field(
        default=None,
        description="The canonical/representative label for this cluster.",
        extras={"maxLength": 1024},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
    )
    members: tuple[dx.Embed[ObjectRef], ...] = dx.field(
        description="References to the annotations in this cluster. Use localId for same-layer members, recordRef+objectId for cross-layer or cross-document coreference.",  # noqa: E501
    )
    uuid: dx.Embed[Uuid] = dx.field(
        description="generated field",
    )


class ClusterSet(dx.Model):
    """Groups annotations into equivalence classes. Used for coreference resolution (entity clusters, situation clusters), bridging anaphora grouping, and any annotation clustering task."""  # noqa: E501

    clusters: tuple[dx.Embed[Cluster], ...] = dx.field(
        description="generated field",
    )
    corpusRef: str | None = dx.field(
        default=None,
        description="Corpus these clusters span (for cross-document clustering).",
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    expression: str | None = dx.field(
        default=None,
        description="Primary expression context. Optional for cross-document clustering.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    expressionRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="For cross-document clustering: all expressions these clusters span.",  # noqa: E501
    )
    kind: str = dx.field(
        description="Clustering kind slug (fallback when kindUri unavailable).",
        extras={
            "knownValues": (
                "coreference",
                "situation-coreference",
                "bridging",
                "same-as",
                "clustering",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the clustering kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    layerRef: str | None = dx.field(
        default=None,
        description="The annotation layer whose annotations these clusters group.",
        extras={"format": "at-uri"},
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
