# generated by lairs gen; do not edit
# lexicon tree hash 1407dd60301c40d7da0f2996197f4cdc49f2ea76d811ea3ec46ecae8f8a8eec6
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.catalog lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AgentRef,
    AnnotationMetadata,
    FeatureMap,
    KnowledgeRef,
    LanguageRef,
    Licensing,
    ObjectRef,
    ReproducibilityInfo,
)

__all__ = [
    "Citation",
    "Collection",
    "ContentSummary",
    "MemberRef",
    "Membership",
]


class Citation(dx.Model):
    """How to cite this collection, and whether this collection is the level that should be cited at all. A collection carrying a citation block is a citable node: a publisher declaration rather than a schema tier, which is what lets UD name the treebank as citable while UniMorph names the project. Absent means the publisher has not declared; consumers should fall back to the nearest ancestor that has."""  # noqa: E501

    acknowledgement: str | None = dx.field(
        default=None,
        description="Acknowledgement text the publisher asks downstream users to reproduce.",  # noqa: E501
        extras={"maxLength": 4096},
    )
    authors: tuple[dx.Embed[AgentRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Authors or maintainers credited for this collection, as agentRefs so an ORCID grounds a person and a DID grounds an ATProto-native contributor. Structured rather than a name string because release-level deposits routinely flatten hundreds of contributors into 'Zeman, Daniel; et al.', and the project node and the release node legitimately carry different author sets.",  # noqa: E501
    )
    citeAs: str | None = dx.field(
        default=None,
        description="The publisher's preferred citation string, as prose. Prose by design: this is the residue after authors, publisher and identifiers have been given structurally, and forcing a bibliography style into a schema would be false precision.",  # noqa: E501
        extras={"maxLength": 4096},
    )
    creditPolicy: str | None = dx.field(
        default=None,
        description="Where the publisher wants credit to land (fallback when creditPolicyUri unavailable). 'cite-self' marks this node as the row a bibliography should name, which is UniMorph's case: 186 language datasets share one paper. 'cite-children' delegates downward, which is UD's case: researchers cite the treebank, not the project. 'cite-both' is legitimate when a project paper and a component paper both exist. Umbrella collections SHOULD default to 'cite-children' so that a duplicate citable level is authored deliberately rather than by omission.",  # noqa: E501
        extras={
            "knownValues": (
                "cite-self",
                "cite-children",
                "cite-parent",
                "cite-both",
                "do-not-cite",
            ),
            "maxLength": 64,
        },
    )
    creditPolicyUri: str | None = dx.field(
        default=None,
        description="AT-URI of the credit-policy definition node (typeDef of 'credit-policy' at layers-core.ontology.layers.pub). Refines creditPolicy; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    identifiers: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Persistent identifiers for this collection, grounded via source 'doi', 'handle', 'islrn', 'datacite', 'openalex' or 'ror'. This is the field that gives a persistent identifier to the level researchers actually name, which today is a directory inside a tarball under someone else's handle.",  # noqa: E501
    )
    publishedAt: datetime | None = dx.field(
        default=None,
        description="Publication date used in a citation. Distinct from createdAt, which is when the Layers record was written.",  # noqa: E501
        extras={"format": "datetime"},
    )
    publisher: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="The publishing organization or repository, grounded via source 'ror', 'lindat', 'ldc', 'elra', 'openneuro' or 'wikidata'. Not a free-text name: 'LDC', 'Linguistic Data Consortium' and 'U. Penn LDC' are one organization and must facet as one.",  # noqa: E501
    )


class ContentSummary(dx.Model):
    """One publisher-declared bucket of what a collection contains: a produce record type, optionally narrowed by kind, subkind and modality, with a count and an explicit statement of where the count came from. Exists so a browse row can state 'sentence-level dependency annotation over 16,622 expressions, English, gold' without paging tens of thousands of annotation records. Never authoritative over the appview's computed rollup; countSource is what lets a consumer tell the two apart."""  # noqa: E501

    asOf: datetime | None = dx.field(
        default=None,
        description="When this summary was last recomputed by its publisher. A stale summary is detectable only if it is dated.",  # noqa: E501
        extras={"format": "datetime"},
    )
    count: int | None = dx.field(
        default=None,
        description="How many units this bucket holds. Meaningless without countSource: pub.layers.corpus.corpus.expressionCount is null on every live record today, and a rollup that cannot distinguish a declared 16,622 from a computed 16,622 from an absent one will present zero as fact.",  # noqa: E501
        extras={"minimum": 0},
    )
    countIsExact: bool | None = dx.field(
        default=None,
        description="Whether count is exact rather than rounded or floored. Absent means unstated.",  # noqa: E501
    )
    countSource: str = dx.field(
        description="Where count came from. Required, because an unqualified number in a catalogue is a claim the catalogue cannot support. 'declared' is the publisher's own figure; 'computed' is derived from records the publisher holds; 'estimated' is sampled or projected; 'unavailable' asserts the bucket exists while its size is unknown, which is the honest state for most of the live corpus today.",  # noqa: E501
        extras={
            "knownValues": (
                "declared",
                "computed",
                "estimated",
                "unavailable",
            ),
            "maxLength": 64,
        },
    )
    countSourceUri: str | None = dx.field(
        default=None,
        description="AT-URI of the count-source definition node (typeDef of 'count-source' at layers-core.ontology.layers.pub). Refines countSource; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    exampleRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of a few representative records from this bucket, so a browse row can render a real example without a query. Advisory and small by design.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open key-value map for publisher-specific summary attributes not covered by the named fields.",  # noqa: E501
    )
    formalism: str | None = dx.field(
        default=None,
        description="Annotation formalism slug (fallback when formalismUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "universal-dependencies",
                "stanford-dependencies",
                "surface-syntactic-ud",
                "penn-treebank",
                "tiger",
                "prague-tectogrammatical",
                "ccgbank",
                "abstract-meaning-representation",
                "universal-decompositional-semantics",
                "propbank",
                "framenet",
                "verbnet",
                "ontonotes",
                "unimorph",
                "sigmorphon",
                "conll-u",
                "conll-2003",
                "elan-tier",
                "praat-textgrid",
                "bids",
                "nwb",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    formalismUri: str | None = dx.field(
        default=None,
        description="AT-URI of the formalism definition node (typeDef of 'formalism' at layers-annotation.ontology.layers.pub). Refines formalism; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    kind: str | None = dx.field(
        default=None,
        description="Kind slug (fallback when kindUri unavailable). Draws on the kind vocabulary of the record type named by produceCollection, so its value space is polymorphic by construction. A consumer that cannot resolve produceCollection MUST render this slug verbatim rather than attempting to validate it.",  # noqa: E501
        extras={"maxLength": 128},
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the kind definition node for this bucket. MUST resolve into the kind vocabulary of the record type named by produceCollection: a pub.layers.ontology.typeDef of the 'annotation-kind' ontology at layers-annotation.ontology.layers.pub for an annotationLayer bucket, of 'catalog-kind' at layers-core.ontology.layers.pub for a nested collection bucket. Refines kind; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    languages: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Canonical BCP-47 language tags this bucket covers, when narrower than the collection's own languages array. Canonical means the shortest ISO 639 code that exists for the language: 'en' not 'eng', 'fi' not 'fin', but 'poma' for Pomak because no 639-1 code exists.",  # noqa: E501
    )
    modality: str | None = dx.field(
        default=None,
        description="Modality slug (fallback when modalityUri unavailable). Covers everything Layers can annotate, not text alone.",  # noqa: E501
        extras={
            "knownValues": (
                "text",
                "speech-audio",
                "non-speech-audio",
                "video",
                "sign-language-video",
                "image",
                "document-scan",
                "eeg",
                "meg",
                "ieeg",
                "ecog",
                "fnirs",
                "fmri",
                "structural-mri",
                "dwi",
                "pet",
                "emg",
                "ecg",
                "eda",
                "respiration",
                "eye-tracking",
                "pupillometry",
                "motion-capture",
                "articulography",
                "ultrasound-tongue",
                "electroglottography",
                "electropalatography",
                "keystroke",
                "mouse-tracking",
                "button-box",
                "touch",
                "behavioral-response",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    modalityUri: str | None = dx.field(
        default=None,
        description="AT-URI of the modality definition node, a pub.layers.ontology.typeDef of the 'modality' ontology at layers-core.ontology.layers.pub. The SAME node set is named by pub.layers.judgment.defs#recordingMethod.methodUri and by pub.layers.media.defs#signalInfo.modalityUri, so a recording, the experiment that produced it, and the catalogue entry advertising it join on one vocabulary. Distinct from pub.layers.media.media.kindUri, which names the CARRIER: each modality node reaches its carrier node by parentTypeRef, so 'collections with EEG' and 'media of kind signal' are one traversal rather than two enums.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    produceCollection: str = dx.field(
        description="NSID of the produce record type this bucket summarizes. Takes the same value space as pub.layers.catalog.defs#memberRef.memberType so a summary and an edge over the same produce join without translation.",  # noqa: E501
        extras={
            "knownValues": (
                "pub.layers.corpus.corpus",
                "pub.layers.expression.expression",
                "pub.layers.annotation.annotationLayer",
                "pub.layers.annotation.clusterSet",
                "pub.layers.segmentation.segmentation",
                "pub.layers.alignment.alignment",
                "pub.layers.graph.graphEdgeSet",
                "pub.layers.ontology.ontology",
                "pub.layers.ontology.typeDef",
                "pub.layers.resource.collection",
                "pub.layers.resource.entry",
                "pub.layers.judgment.experimentDef",
                "pub.layers.judgment.judgmentSet",
                "pub.layers.media.media",
                "pub.layers.acquisition.session",
                "pub.layers.acquisition.participant",
            ),
            "maxLength": 317,
        },
    )
    sourceMethod: str | None = dx.field(
        default=None,
        description="How the contents of this bucket were produced (fallback when sourceMethodUri unavailable). This is the gold-versus-silver discriminator and the single most requested filter in corpus browsing.",  # noqa: E501
        extras={
            "knownValues": (
                "manual",
                "double-annotated-adjudicated",
                "semi-automatic",
                "automatic",
                "projected",
                "converted",
                "crowdsourced",
                "native",
                "synthetic",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    sourceMethodUri: str | None = dx.field(
        default=None,
        description="AT-URI of the production-method definition node (typeDef of 'source-method' at layers-annotation.ontology.layers.pub). Refines sourceMethod; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    subkind: str | None = dx.field(
        default=None,
        description="Subkind slug (fallback when subkindUri unavailable). This is the primary selection criterion for corpus and NLP browsing: 'has dependency annotation' and 'has coreference' are subkind queries, and answering them by paging annotationLayer records costs minutes and hundreds of megabytes per refresh.",  # noqa: E501
        extras={
            "knownValues": (
                "pos",
                "xpos",
                "lemma",
                "morph",
                "ner",
                "supersense",
                "sense",
                "chunk",
                "dependency",
                "enhanced-dependency",
                "constituency",
                "ccg",
                "frame",
                "predicate",
                "coreference",
                "bridging",
                "discourse-relation",
                "temporal-relation",
                "causal-relation",
                "sentiment",
                "emotion",
                "stance",
                "information-structure",
                "speaker",
                "gloss",
                "phonetic",
                "prosody",
                "tobi",
                "language-id",
                "code-switch",
                "error",
                "correction",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    subkindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the subkind definition node (typeDef of 'annotation-subkind' at layers-annotation.ontology.layers.pub for annotation buckets). Refines subkind; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    unit: str | None = dx.field(
        default=None,
        description="Unit slug for count (fallback when unitUri unavailable).",
        extras={
            "knownValues": (
                "expression",
                "sentence",
                "token",
                "word",
                "type",
                "lemma",
                "entry",
                "paradigm-cell",
                "annotation",
                "span",
                "relation",
                "tree",
                "node",
                "edge",
                "cluster",
                "document",
                "media-item",
                "session",
                "participant",
                "trial",
                "judgment",
                "run",
                "class",
                "type-def",
                "second",
                "sample",
                "byte",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    unitUri: str | None = dx.field(
        default=None,
        description="AT-URI of the unit definition node (typeDef of 'unit' at layers-core.ontology.layers.pub). Refines unit; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class Collection(dx.Model):
    """A citable, nestable grouping of linguistic material: the thing a researcher names in prose, cites in a bibliography, and browses for. 'UD English-EWT', 'Universal Dependencies', 'VerbNet', 'MegaAcceptability Linking v1', 'UniMorph Finnish' and 'Buckeye' are each one of these, at whatever depth their community organizes them. Container-ness is a kind, not a separate record type, so a collection may hold other collections to arbitrary depth. Distinct from pub.layers.resource.collection, which is the narrower notion of a set of lexical resource entries and remains a legitimate member of this one."""  # noqa: E501

    access: str | None = dx.field(
        default=None,
        description="Access conditions on the underlying material (fallback when accessUri unavailable). Distinct from licensing, which states what a recipient may do; this states who may become a recipient, which for participant-identifiable neural, audio and video data is the governing constraint.",  # noqa: E501
        extras={
            "knownValues": (
                "open",
                "registration-required",
                "agreement-required",
                "restricted",
                "embargoed",
                "closed",
            ),
            "maxLength": 64,
        },
    )
    accessUri: str | None = dx.field(
        default=None,
        description="AT-URI of the access-condition definition node (typeDef of 'access-condition' at layers-core.ontology.layers.pub). Refines access; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    citation: dx.Embed[Citation] | None = dx.field(
        default=None,
        description="How to cite this collection, and whether this is the level that should be cited. Presence marks this node as citable; creditPolicy delegates upward or downward when it is not.",  # noqa: E501
    )
    contents: tuple[dx.Embed[ContentSummary], ...] | None = dx.field(
        default_factory=tuple,
        description="Publisher-declared summary of what this collection contains, one entry per produce type and narrowing. Makes a browse row renderable without paging the produces, which is the difference between a page load and a multi-minute crawl over tens of thousands of annotation records. Every entry states its countSource, so a consumer can tell a declared figure from a computed one and from an absent one. Never authoritative over the appview's computed rollup.",  # noqa: E501
    )
    createdAt: datetime = dx.field(
        description="When this Layers record was written. Distinct from firstReleasedAt and citation.publishedAt, which describe the material rather than the record.",  # noqa: E501
        extras={"format": "datetime"},
    )
    currentVersionRef: str | None = dx.field(
        default=None,
        description="AT-URI of the release a consumer should treat as current. Written on the concept node; a rollup over a concept node resolves through it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    depth: int | None = dx.field(
        default=None,
        description="Number of parentRef hops from the root: 0 for a project with no parent, 1 for UD English under UD, 2 for UD English-EWT. Denormalized for indexed subtree queries and, as a side effect, a validity check: a claimed depth that disagrees with the observed chain is how a cycle or a stale parent surfaces. Bounded because a bound is what makes it checkable, not because any depth is meaningful.",  # noqa: E501
        extras={"minimum": 0, "maximum": 8},
    )
    description: str | None = dx.field(
        default=None,
        description="Prose description of what this collection is and what it contains.",  # noqa: E501
        extras={"maxLength": 50000},
    )
    embargoedUntil: datetime | None = dx.field(
        default=None,
        description="When an embargo lifts, present when access is 'embargoed'.",
        extras={"format": "datetime"},
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of pub.layers.eprint.eprint records describing this collection. Inherited by descendants that declare none: one parent eprintRef is what lets UniMorph replace 185 redundant per-language citations with one.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features that no field above reaches. Not a place to reintroduce a controlled vocabulary as key-value strings.",  # noqa: E501
    )
    firstReleasedAt: datetime | None = dx.field(
        default=None,
        description="When this collection was first released to the public, which for imported material is decades before the Layers record existed.",  # noqa: E501
        extras={"format": "datetime"},
    )
    homepage: str | None = dx.field(
        default=None,
        description="Canonical project or dataset homepage.",
        extras={"format": "uri", "maxLength": 2048},
    )
    kind: str = dx.field(
        description="Collection kind slug. REQUIRED, because a consumer that cannot resolve kindUri, or that has not yet indexed the ontology account, must still be able to render and facet this record. Container-ness is carried here rather than by a separate record type: 'project' and 'language-group' habitually contain other collections, 'treebank' and 'judgment-study' habitually do not, and nothing in the schema enforces the habit.",  # noqa: E501
        extras={
            "knownValues": (
                "project",
                "language-group",
                "sub-project",
                "release",
                "treebank",
                "corpus",
                "annotated-corpus",
                "parallel-corpus",
                "comparable-corpus",
                "speech-corpus",
                "audio-corpus",
                "video-corpus",
                "sign-language-corpus",
                "multimodal-corpus",
                "neuro-dataset",
                "eye-tracking-dataset",
                "motion-dataset",
                "experiment-series",
                "judgment-study",
                "stimulus-set",
                "lexicon",
                "frame-inventory",
                "wordnet",
                "ontology",
                "ontology-alignment",
                "morphological-paradigm-set",
                "gazetteer",
                "treebank-family",
                "benchmark",
                "shared-task",
                "subcorpus",
                "archive",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the collection kind definition node, a pub.layers.ontology.typeDef of the 'catalog-kind' ontology at layers-core.ontology.layers.pub, or a pub.layers.graph.graphNode. Community-expandable via knowledge graph. Refines kind; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="External groundings for this collection as an entity: Wikidata for the project, ROR for its home institution, OpenAlex or DOI for its canonical publication, LDC or LINDAT or OpenNeuro or PARADISEC for its deposit elsewhere.",  # noqa: E501
    )
    languageRefs: tuple[dx.Embed[LanguageRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Structured language references, present when a bare BCP-47 tag is insufficient: a variety below the language level, a Glottolog languoid, a disputed code, or a per-language role in a parallel or bilingual collection. Each entry's tag SHOULD also appear in languages so consumers filtering on the cheap array are not silently excluded.",  # noqa: E501
    )
    languages: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Canonical BCP-47 language tags this collection covers. Canonical means the shortest ISO 639 code that exists for the language: 'en' not 'eng', 'fi' not 'fin', but 'poma' for Pomak because no 639-1 code exists. Language is a FACET, never a level: 107 of UD's 145 languages have exactly one treebank, so a language tier would insert 107 nodes identical to their sole child, and 88 treebanks sit in cross-language families that a language tier cannot address at any depth. Rolls up as a set union over the containment spine, so a project node legitimately carries 145 tags. Where a tag cannot name the variety precisely, carry the tag here and the precise identity in languageRefs.",  # noqa: E501
    )
    licensing: dx.Embed[Licensing] | None = dx.field(
        default=None,
        description="Licensing terms governing this collection (supports dual, multi, composite and component-scoped licensing). Component-scoped licensing is the normal case in a nested catalogue: a per-treebank license sits beneath a release-level one, which is what licenseRef.appliesTo carries.",  # noqa: E501
    )
    localId: str | None = dx.field(
        default=None,
        description="Stable, lowercase, immutable, human-readable local identifier for this collection within its publishing account ('ewt', 'eng', 'ud'). Survives handle changes, account merges and record rebuilds, which AT-URIs do not when a repo is rebuilt in place. Advisory for resolution and authoritative for nothing; parentRef is the link.",  # noqa: E501
        extras={"maxLength": 128},
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who curated this collection record, under what persona, with what tool, and what upstream records it was derived from.",  # noqa: E501
    )
    name: str = dx.field(
        description="Human-readable name, as the community writes it ('UD English-EWT', 'MegaAcceptability Linking v1').",  # noqa: E501
        extras={"maxLength": 2048},
    )
    ontologyRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of pub.layers.ontology.ontology records defining the type systems used across this collection.",  # noqa: E501
    )
    parentRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.catalog.collection that contains this one. Child-held and single-valued: a child's PDS can always write this, whereas nothing can compel a parent's PDS to write a member array, so this is the canonical containment spine and a parent-held member list would be a derived cache at best. MUST NOT be self-referential directly or transitively; the appview rejects cycles at index time. A collection has at most one parent and may be a member of any number of collections through pub.layers.catalog.membership.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    pinPolicy: str | None = dx.field(
        default=None,
        description="Whether this collection's membership is pinned to exact member revisions or tracks them as they change. Declared rather than enforced, because the declaration is what a consumer needs and enforcement across repos it does not own is not available. Under 'pinned', every pub.layers.catalog.membership edge into this collection SHOULD carry memberCid, and the appview flags those that do not. Layers-hosted collections whose repos are rebuilt in place SHOULD declare 'floating' and carry the release axis in version plus previousVersionRef, since a rebuild moves every CID and dangles every pin taken before it.",  # noqa: E501
        extras={
            "knownValues": (
                "pinned",
                "floating",
                "undeclared",
            ),
            "maxLength": 64,
        },
    )
    pinPolicyUri: str | None = dx.field(
        default=None,
        description="AT-URI of the pin-policy definition node (typeDef of 'pin-policy' at layers-core.ontology.layers.pub). Refines pinPolicy; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    previousVersionRef: str | None = dx.field(
        default=None,
        description="AT-URI of the collection release this one directly supersedes, forming a version chain. Distinct from a sibling work: four MegaAttitude datasets share one project and only one of them is a version of another.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    releasedAt: datetime | None = dx.field(
        default=None,
        description="When this particular version was released.",
        extras={"format": "datetime"},
    )
    reproducibility: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
        description="How this collection was built: pipeline name and version, container, code repository, commit, command, funding and ethics approvals. Required in spirit for any collection derived from another, since nesting produces derivatives by construction.",  # noqa: E501
    )
    rootRef: str | None = dx.field(
        default=None,
        description="AT-URI of the root of this collection's parent chain, denormalized so subtree selection is an indexed equality rather than a recursive chase. Equal to this record's own AT-URI when parentRef is absent, which cannot be written into the record and is therefore left absent at depth 0.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    stability: str | None = dx.field(
        default=None,
        description="Lifecycle state of this collection (fallback when stabilityUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "draft",
                "active",
                "maintained",
                "frozen",
                "deprecated",
                "withdrawn",
            ),
            "maxLength": 64,
        },
    )
    stabilityNotice: str | None = dx.field(
        default=None,
        description="Prose explaining a deprecation or withdrawal, and where to go instead.",  # noqa: E501
        extras={"maxLength": 4096},
    )
    stabilityUri: str | None = dx.field(
        default=None,
        description="AT-URI of the stability definition node (typeDef of 'stability' at layers-core.ontology.layers.pub). Refines stability; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    supersededByRef: str | None = dx.field(
        default=None,
        description="AT-URI of the collection that replaces this one after a withdrawal or a rename. Distinct from previousVersionRef's inverse: supersession may cross project boundaries.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    version: str | None = dx.field(
        default=None,
        description="Version or release designation of this collection ('2.18', 'v2.1', 'FrameNet 1.7'). Present on a release node; usually absent on the concept node above it.",  # noqa: E501
        extras={"maxLength": 64},
    )
    versionOfRef: str | None = dx.field(
        default=None,
        description="AT-URI of the concept-level collection this record is a released version OF. Version is orthogonal to containment: a release is a versionOf its concept node, NEVER a child of it. UD has 24 releases; were a release a child and release edges summed, UD would report 24 times 228 treebanks. Rollups on a concept node resolve through currentVersionRef and sum that release only.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class MemberRef(dx.Model):
    """A reference to the thing contained by a collection. Composes pub.layers.defs#objectRef rather than re-declaring recordRef and objectId, so a member that exists only in an external knowledge base (a VerbNet class present in Wikidata but not yet in Layers) is representable, and so any resolver written against objectRef works here unchanged."""  # noqa: E501

    memberCid: str | None = dx.field(
        default=None,
        description="CID of the exact member revision this edge pins. Required in practice when the containing collection declares pinPolicy 'pinned'. Pins the member's RECORD, not its contents: a corpus record's expressions and annotation layers live in other repos reached through pub.layers.corpus.membership, which this CID does not cover. Pin the produce edges too for layer-set coverage; byte-level reproducibility is not implied.",  # noqa: E501
        extras={"format": "cid"},
    )
    memberName: str | None = dx.field(
        default=None,
        description="Display cache of the member's name, advisory in exactly the way an ATProto handle is advisory. Lets a container render a member list before its members are indexed; superseded by the member record whenever it resolves.",  # noqa: E501
        extras={"maxLength": 2048},
    )
    memberType: str = dx.field(
        description="NSID of the member's record type, denormalized so a member list can dispatch its renderer and filter by type without resolving every AT-URI. Mirrors the NSID-discriminator pattern of pub.layers.changelog.entry#subjectCollection. Empty string when the member is knowledgeRef-only.",  # noqa: E501
        extras={
            "knownValues": (
                "pub.layers.catalog.collection",
                "pub.layers.corpus.corpus",
                "pub.layers.expression.expression",
                "pub.layers.resource.collection",
                "pub.layers.resource.entry",
                "pub.layers.annotation.annotationLayer",
                "pub.layers.annotation.clusterSet",
                "pub.layers.segmentation.segmentation",
                "pub.layers.alignment.alignment",
                "pub.layers.graph.graphEdgeSet",
                "pub.layers.ontology.ontology",
                "pub.layers.ontology.typeDef",
                "pub.layers.judgment.experimentDef",
                "pub.layers.judgment.judgmentSet",
                "pub.layers.media.media",
                "pub.layers.acquisition.session",
                "pub.layers.acquisition.participant",
                "pub.layers.eprint.eprint",
                "pub.layers.persona.persona",
            ),
            "maxLength": 317,
        },
    )
    memberVersion: str | None = dx.field(
        default=None,
        description="Display cache of the member's version string. Advisory; superseded by the member record whenever it resolves.",  # noqa: E501
        extras={"maxLength": 64},
    )
    ref: dx.Embed[ObjectRef] = dx.field(
        description="The member. Populate recordRef for a Layers record, recordRef plus objectId for a sub-record object, knowledgeRef for a member Layers does not hold.",  # noqa: E501
    )


class Membership(dx.Model):
    """A typed edge from a pub.layers.catalog.collection to something it contains, produces, annotates, or otherwise relates to. A record rather than an inline array because the two endpoints routinely live in different repos: PropBank-SRL's edge onto a UD treebank is written by PropBank's account, and requiring UD to bless every annotation over its treebanks is unimplementable. Complements rather than replaces the containment spine: parentRef on the child is the single canonical parent, and these edges carry produces, cross-family relations, and multiple membership."""  # noqa: E501

    catalogRef: str = dx.field(
        description="AT-URI of the pub.layers.catalog.collection at the container end of this edge.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        description="Timestamp when this membership edge record was created.",
        extras={"format": "datetime"},
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of pub.layers.eprint.eprint records documenting this relation.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open key-value map for edge-specific attributes not covered by the named fields.",  # noqa: E501
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="External groundings for the relation itself, such as the paper that established a derivation or an alignment.",  # noqa: E501
    )
    member: dx.Embed[MemberRef] = dx.field(
        description="The thing at the other end, as an objectRef plus a denormalized NSID and optional pinning CID. Covers Layers records, sub-record objects, and members Layers does not hold.",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who asserted this edge, under what persona, with what tool.",  # noqa: E501
    )
    notes: str | None = dx.field(
        default=None,
        description="Prose qualifying this edge: what was projected, what was excluded, what is approximate.",  # noqa: E501
        extras={"maxLength": 4096},
    )
    ordinal: int | None = dx.field(
        default=None,
        description="Ordering index within the container, when the container has a meaningful order (a release sequence, a paradigm ordering, a curriculum). Absent means unordered.",  # noqa: E501
        extras={"minimum": 0},
    )
    pinPolicy: str | None = dx.field(
        default=None,
        description="Pin policy for this edge specifically, overriding the container's declaration. Present because one collection legitimately pins some members and floats others: a release pins the treebanks it shipped while floating the ontology it types against.",  # noqa: E501
        extras={
            "knownValues": (
                "pinned",
                "floating",
                "undeclared",
            ),
            "maxLength": 64,
        },
    )
    pinPolicyUri: str | None = dx.field(
        default=None,
        description="AT-URI of the pin-policy definition node (typeDef of 'pin-policy' at layers-core.ontology.layers.pub). Refines pinPolicy; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    role: str = dx.field(
        description="What this edge asserts. REQUIRED, and it is the field that decides arithmetic. Exactly two roles contribute to a rollup: 'produce', which names a corpus, annotation layer, segmentation, alignment, judgment set, media item or ontology this collection publishes and is where the count recursion bottoms out, and 'member', which names a nested collection whose own parentRef points back here and which therefore lies on the containment spine. Every other role is rendered and never summed, so PropBank-SRL over UD English-EWT appears on the treebank's page under 'annotated by' contributing zero, and a parallel-corpus grouping browses as first-class without inflating the counts of treebanks it does not own.",  # noqa: E501
        extras={
            "knownValues": (
                "member",
                "produce",
                "annotates",
                "derived-from",
                "subset-of",
                "translation-of",
                "parallel-with",
                "aligned-with",
                "registry-for",
                "typed-by",
                "replicates",
                "extends",
                "mirror-of",
                "same-as",
                "stimulus-for",
                "documented-by",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    roleUri: str | None = dx.field(
        default=None,
        description="AT-URI of the membership role definition node, a pub.layers.ontology.typeDef of the 'membership-role' ontology at layers-core.ontology.layers.pub, or a pub.layers.graph.graphNode. Community-expandable via knowledge graph. Refines role; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    selfAsserted: bool | None = dx.field(
        default=None,
        description="True when the edge's author does not control the member, which is the normal case for 'annotates', 'derived-from' and 'parallel-with'. Consumers that surface only curated structure filter on it; consumers that surface everything render it with attribution to the edge's repo.",  # noqa: E501
    )
    validFrom: datetime | None = dx.field(
        default=None,
        description="When this membership took effect. Lets two releases of one collection carry different member sets as coexisting edges rather than as a rewritten array.",  # noqa: E501
        extras={"format": "datetime"},
    )
    validUntil: datetime | None = dx.field(
        default=None,
        description="When this membership ceased. A member dropped between releases is expressed by closing its edge, not by deleting it, so a pinned earlier release still resolves.",  # noqa: E501
        extras={"format": "datetime"},
    )
