# generated by lairs gen; do not edit
# lexicon tree hash c579e63d3ffd0d55171eeeef7fbee9254e184419ebdfbb1bddc4807310069330
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.changelog lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import ObjectRef

__all__ = [
    "ChangeItem",
    "ChangeSection",
    "Entry",
    "SemanticVersion",
]


class ChangeItem(dx.Model):
    """An individual change entry. The targets field uses objectRef for machine-readable sub-record targeting, allowing a change item to point at specific objects within the subject record."""  # noqa: E501

    changeType: str | None = dx.field(
        default=None,
        description="Type of change.",
        extras={
            "knownValues": (
                "added",
                "changed",
                "removed",
                "fixed",
                "deprecated",
            ),
            "maxLength": 32,
        },
    )
    description: str = dx.field(
        description="Description of the change.",
        extras={"maxLength": 2000},
    )
    fieldPath: str | None = dx.field(
        default=None,
        description="Path to the changed field within the target (e.g., 'annotations/3/label', 'formalism', 'annotationDesign/guidelinesRef').",  # noqa: E501
        extras={"maxLength": 200},
    )
    newValue: str | None = dx.field(
        default=None,
        description="New value as a display string.",
        extras={"maxLength": 1000},
    )
    previousValue: str | None = dx.field(
        default=None,
        description="Previous value as a display string.",
        extras={"maxLength": 1000},
    )
    targets: tuple[dx.Embed[ObjectRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Specific objects that changed. Uses recordRef + objectId for sub-record targeting (e.g., a specific annotation within an annotation layer).",  # noqa: E501
    )


class ChangeSection(dx.Model):
    """A group of changes under a single category."""

    category: str = dx.field(
        description="Category of changes.",
        extras={
            "knownValues": (
                "annotations",
                "segmentation",
                "text",
                "ontology",
                "corpus",
                "alignment",
                "graph",
                "experiment",
                "resource",
                "media",
                "provenance",
                "references",
                "corrections",
                "other",
            ),
            "maxLength": 128,
        },
    )
    items: tuple[dx.Embed[ChangeItem], ...] = dx.field(
        description="Individual change items in this section.",
    )


class SemanticVersion(dx.Model):
    """A semantic version following the major.minor.patch convention."""

    major: int = dx.field(
        description="Major version number.",
        extras={"minimum": 0},
    )
    minor: int = dx.field(
        description="Minor version number.",
        extras={"minimum": 0},
    )
    patch: int = dx.field(
        description="Patch version number.",
        extras={"minimum": 0},
    )


class Entry(dx.Model):
    """A changelog entry describing changes to any Layers record."""

    createdAt: datetime = dx.field(
        description="When this changelog entry was created.",
        extras={"format": "datetime"},
    )
    previousVersion: dx.Embed[SemanticVersion] | None = dx.field(
        default=None,
        description="Previous semantic version.",
    )
    sections: tuple[dx.Embed[ChangeSection], ...] = dx.field(
        description="Categorized change sections.",
    )
    subject: str = dx.field(
        description="AT-URI of the record this changelog describes (any pub.layers.* record).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    subjectCollection: str = dx.field(
        description="The NSID of the subject record's collection (e.g., 'pub.layers.annotation.annotationLayer'). Enables efficient filtering by record type without resolving the AT-URI.",  # noqa: E501
        extras={"maxLength": 256},
    )
    summary: str = dx.field(
        description="One-line summary of changes.",
        extras={"maxLength": 500},
    )
    version: dx.Embed[SemanticVersion] | None = dx.field(
        default=None,
        description="Semantic version this changelog describes.",
    )
