# generated by lairs gen; do not edit
# lexicon tree hash cedfb9f34cc55fb5be1abb81dda63fd6a6671af2efd6a5e5923fca0c77ba0fd1
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.corpus lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AnnotationMetadata,
    FeatureMap,
    Licensing,
    ReproducibilityInfo,
)

__all__ = [
    "AdjudicationSpec",
    "AnnotationDesign",
    "Corpus",
    "Membership",
    "QualityCriterion",
    "RedundancySpec",
]


class AdjudicationSpec(dx.Model):
    """How disagreements between annotators are resolved into a final annotation."""

    agreementThreshold: int | None = dx.field(
        default=None,
        description="Agreement level (0-1000) above which adjudication is skipped.",
        extras={"minimum": 0, "maximum": 1000},
    )
    dedicatedAdjudicator: bool | None = dx.field(
        default=None,
        description="Whether a separate adjudicator (not one of the annotators) resolves disagreements.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    method: str | None = dx.field(
        default=None,
        description="Adjudication method (fallback when methodUri unavailable).",
        extras={
            "knownValues": (
                "expert",
                "majority-vote",
                "unanimous",
                "discussion",
                "dawid-skene",
                "automatic-merge",
                "intersection",
                "union",
                "none",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    methodUri: str | None = dx.field(
        default=None,
        description="AT-URI of the adjudication method definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class QualityCriterion(dx.Model):
    """An acceptance criterion for annotation quality."""

    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    metric: str = dx.field(
        description="Agreement or quality metric (fallback when metricUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "cohens-kappa",
                "fleiss-kappa",
                "krippendorff-alpha",
                "percent-agreement",
                "f1",
                "smatch",
                "uas",
                "las",
                "correlation",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    metricUri: str | None = dx.field(
        default=None,
        description="AT-URI of the metric definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    scope: str | None = dx.field(
        default=None,
        description="Evaluation scope (fallback when scopeUri unavailable).",
        extras={
            "knownValues": (
                "item",
                "layer",
                "document",
                "corpus",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    scopeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the evaluation scope definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    threshold: int | None = dx.field(
        default=None,
        description="Minimum acceptable metric value (0-1000).",
        extras={"minimum": 0, "maximum": 1000},
    )


class RedundancySpec(dx.Model):
    """How many annotators work on each item and how they are assigned."""

    annotatorPool: int | None = dx.field(
        default=None,
        description="Total number of annotators in the project.",
        extras={"minimum": 0},
    )
    assignmentStrategy: str | None = dx.field(
        default=None,
        description="How annotators are assigned to items (fallback when assignmentStrategyUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "random",
                "round-robin",
                "stratified",
                "expertise-based",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    assignmentStrategyUri: str | None = dx.field(
        default=None,
        description="AT-URI of the assignment strategy definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    count: int | None = dx.field(
        default=None,
        description="Number of independent annotators per item.",
        extras={"minimum": 0},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )


class AnnotationDesign(dx.Model):
    """Annotation project design parameters: annotator assignment, adjudication, and quality criteria."""  # noqa: E501

    adjudication: dx.Embed[AdjudicationSpec] | None = dx.field(
        default=None,
        description="How disagreements are resolved.",
    )
    annotationRounds: int | None = dx.field(
        default=None,
        description="Number of annotation passes in the project workflow.",
        extras={"minimum": 1},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    guidelinesRef: str | None = dx.field(
        default=None,
        description="AT-URI of the annotation guidelines document (e.g., a pub.layers.persona or external resource).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    guidelinesVersion: str | None = dx.field(
        default=None,
        description="Version identifier for the annotation guidelines.",
        extras={"maxLength": 64},
    )
    qualityCriteria: tuple[dx.Embed[QualityCriterion], ...] | None = dx.field(
        default_factory=tuple,
        description="Acceptance criteria for annotation quality.",
    )
    redundancy: dx.Embed[RedundancySpec] | None = dx.field(
        default=None,
        description="How annotators are assigned to items.",
    )


class Corpus(dx.Model):
    """A corpus: a curated collection of expressions."""

    annotationDesign: dx.Embed[AnnotationDesign] | None = dx.field(
        default=None,
        description="Annotation project design: annotator assignment, adjudication, and quality criteria.",  # noqa: E501
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    description: str | None = dx.field(
        default=None,
        extras={"maxLength": 50000},
    )
    domain: str | None = dx.field(
        default=None,
        description="Domain slug (fallback when domainUri unavailable).",
        extras={
            "knownValues": (
                "news",
                "biomedical",
                "legal",
                "social-media",
                "dialogue",
                "literary",
                "scientific",
                "web",
                "spoken",
                "custom",
            ),
            "maxLength": 256,
        },
    )
    domainUri: str | None = dx.field(
        default=None,
        description="AT-URI of the domain definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Eprint records (papers/preprints) describing or associated with this corpus.",  # noqa: E501
    )
    expressionCount: int | None = dx.field(
        default=None,
        description="Number of expressions in the corpus.",
        extras={"minimum": 0},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    languages: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="BCP-47 language tags this record covers. Empty when language is unspecified or unknown.",  # noqa: E501
    )
    licensing: dx.Embed[Licensing] | None = dx.field(
        default=None,
        description="Licensing terms governing this corpus (supports dual/multi/component licensing).",  # noqa: E501
    )
    name: str = dx.field(
        description="Corpus name.",
        extras={"maxLength": 512},
    )
    ontologyRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Ontologies used in this corpus.",
    )
    reproducibility: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
        description="How this corpus was produced (code, commit, command, environment, seed).",  # noqa: E501
    )
    version: str | None = dx.field(
        default=None,
        extras={"maxLength": 64},
    )


class Membership(dx.Model):
    """A record indicating that a expression belongs to a corpus, with optional split assignment."""  # noqa: E501

    corpusRef: str = dx.field(
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    expressionRef: str = dx.field(
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features for this membership (e.g., source file, import batch, quality flags).",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who assigned this expression to this corpus, when, with what tool.",  # noqa: E501
    )
    ordinal: int | None = dx.field(
        default=None,
        description="Ordering index within the corpus.",
        extras={"minimum": 0},
    )
    split: str | None = dx.field(
        default=None,
        description="Split slug (fallback when splitUri unavailable).",
        extras={
            "knownValues": (
                "train",
                "dev",
                "test",
                "unlabeled",
            ),
            "maxLength": 64,
        },
    )
    splitUri: str | None = dx.field(
        default=None,
        description="AT-URI of the split definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
