# generated by lairs gen; do not edit
# lexicon tree hash 1407dd60301c40d7da0f2996197f4cdc49f2ea76d811ea3ec46ecae8f8a8eec6
# ruff: noqa: N815, TC003

"""Generated models for the pub.layers.defs lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime
from typing import Literal

import didactic.api as dx

__all__ = [
    "AccessCondition",
    "AgentRef",
    "AlignmentLink",
    "Anchor",
    "AnnotationMetadata",
    "BoundingBox",
    "Constraint",
    "ContentDigest",
    "DeviceInfo",
    "EthicsApproval",
    "ExternalTarget",
    "ExternalTargetSelector",
    "ExternalTargetSelectorFragmentSelector",
    "ExternalTargetSelectorTextPositionSelector",
    "ExternalTargetSelectorTextQuoteSelector",
    "Feature",
    "FeatureMap",
    "FragmentSelector",
    "FrequencyBand",
    "FundingRef",
    "Keyframe",
    "KnowledgeRef",
    "LanguageRef",
    "LicenseRef",
    "Licensing",
    "MediaScope",
    "ObjectRef",
    "PageAnchor",
    "ReproducibilityInfo",
    "SignalSpan",
    "Span",
    "SpatialEntity",
    "SpatialExpression",
    "SpatialModifier",
    "SpatioTemporalAnchor",
    "TemporalEntity",
    "TemporalExpression",
    "TemporalModifier",
    "TemporalSpan",
    "TextPositionSelector",
    "TextQuoteSelector",
    "TokenRef",
    "TokenRefSequence",
    "Uuid",
]


class KnowledgeRef(dx.Model):
    """A reference to an external knowledge base entry. Supports ATProto-native KBs (e.g., chive.pub with AT-URI nodes), external KBs (e.g., Wikidata with QIDs), and user/persona-specific KBs (AT-URIs in user PDSes)."""  # noqa: E501

    identifier: str = dx.field(
        description="The identifier within the knowledge base (e.g., Wikidata QID, chive.pub node URI, Glottolog languoid ID).",  # noqa: E501
        extras={"maxLength": 512},
    )
    label: str | None = dx.field(
        default=None,
        description="Human-readable label for the referenced entity.",
        extras={"maxLength": 1024},
    )
    source: str = dx.field(
        description="Knowledge base source slug (fallback when sourceUri unavailable).",
        extras={
            "knownValues": (
                "chive.pub",
                "wikidata",
                "wordnet",
                "framenet",
                "propbank",
                "verbnet",
                "unimorph",
                "glottolog",
                "cldr",
                "iso639-3",
                "orcid",
                "ror",
                "openalex",
                "crossref",
                "dblp",
                "semantic-scholar",
                "doi",
                "handle",
                "islrn",
                "datacite",
                "ldc",
                "elra",
                "lindat",
                "openneuro",
                "dandi",
                "paradisec",
                "talkbank",
                "ncbi-taxonomy",
                "rrid",
                "cognitive-atlas",
                "cogpo",
                "hed",
                "uberon",
                "mesh",
                "clinicaltrials",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    sourceUri: str | None = dx.field(
        default=None,
        description="AT-URI of the knowledge base type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    uri: str | None = dx.field(
        default=None,
        description="Optional full URI for the knowledge base entry.",
        extras={"format": "uri"},
    )


class AccessCondition(dx.Model):
    """How the referenced bytes may actually be obtained. 0.8.0 carries licensing but no gate: it can say a corpus is LDC-User-Agreement licensed but not that obtaining it requires a signed agreement with a named body. Layers DECLARES access conditions and cannot ENFORCE them, because every record it indexes lives in someone else's PDS; the block exists so a consumer knows where the gate is before wasting a request."""  # noqa: E501

    agreementUri: str | None = dx.field(
        default=None,
        description="The data use agreement or end-user licence that must be signed.",
        extras={"format": "uri", "maxLength": 2048},
    )
    applicationUri: str | None = dx.field(
        default=None,
        description="URL of the access application or registration form.",
        extras={"format": "uri", "maxLength": 2048},
    )
    embargoedUntil: datetime | None = dx.field(
        default=None,
        description="When an embargo lifts, when mode is embargoed.",
        extras={"format": "datetime"},
    )
    gatekeeperRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="The body that grants access, grounded via ror or wikidata (an archive, a data access committee, a consortium).",  # noqa: E501
    )
    mode: str = dx.field(
        description="Access mode slug (fallback when modeUri unavailable).",
        extras={
            "knownValues": (
                "open",
                "registration-required",
                "agreement-required",
                "restricted",
                "embargoed",
                "closed",
            ),
            "maxLength": 64,
        },
    )
    modeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the access mode definition node (typeDef of access-condition at layers-core.ontology.layers.pub).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    notes: str | None = dx.field(
        default=None,
        description="Free-text access detail the typed fields do not capture.",
        extras={"maxLength": 4096},
    )
    permittedUse: str | None = dx.field(
        default=None,
        description="What the access grant permits (fallback when the Uri is unavailable). Distinct from the licence: some agreements permit analysis but forbid redistribution or model training regardless of licence.",  # noqa: E501
        extras={
            "knownValues": (
                "any",
                "research-only",
                "non-commercial",
                "no-redistribution",
                "no-model-training",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    permittedUseUri: str | None = dx.field(
        default=None,
        description="AT-URI of the permitted-use definition node.",
        extras={"format": "at-uri"},
    )


class AgentRef(dx.Model):
    """A composable reference to any agent (human annotator, ML model, crowd worker, expert panel, etc.) that produced data. Separates the identity of the producer from the interpretive framework (persona) and the software used (tool). Consumers dispatch on which field(s) are populated: did for ATProto-native agents, id for anonymized or platform-specific identifiers, knowledgeRef for externally grounded agents (ORCID, HuggingFace model card, Wikidata)."""  # noqa: E501

    did: str | None = dx.field(
        default=None,
        description="ATProto DID of the agent, if the agent has one.",
        extras={"format": "did"},
    )
    id: str | None = dx.field(
        default=None,
        description="Arbitrary string identifier (anonymized crowdworker ID, platform username, model version string, etc.).",  # noqa: E501
        extras={"maxLength": 512},
    )
    knowledgeRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="External knowledge graph reference for the agent (e.g., ORCID for a human, HuggingFace model card for an ML model, Wikidata for an organization).",  # noqa: E501
    )
    name: str | None = dx.field(
        default=None,
        description="Human-readable display name for the agent.",
        extras={"maxLength": 512},
    )


class Feature(dx.Model):
    """A single key-value feature."""

    key: str = dx.field(
        description="Feature name/key.",
        extras={"maxLength": 256},
    )
    value: str = dx.field(
        description="Feature value as string. Consumers may parse typed values based on the key's semantics.",  # noqa: E501
        extras={"maxLength": 4096},
    )


class FeatureMap(dx.Model):
    """An open-ended set of typed key-value features that can be attached to any annotation. Provides maximum extensibility without committing to any label set or linguistic theory."""  # noqa: E501

    entries: tuple[dx.Embed[Feature], ...] = dx.field(
        description="The feature entries.",
    )


class AlignmentLink(dx.Model):
    """A single link in an alignment between two parallel sequences. Maps element(s) in a source sequence to element(s) in a target sequence. Supports many-to-many correspondence for interlinear glossing, parallel text alignment, cross-tokenization mapping, etc."""  # noqa: E501

    confidence: int | None = dx.field(
        default=None,
        description="Alignment confidence 0-1000.",
        extras={"minimum": 0, "maximum": 1000},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features of this alignment link not reached by the named fields.",  # noqa: E501
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references for this link (e.g., bilingual dictionary entry, translation memory source).",  # noqa: E501
    )
    label: str | None = dx.field(
        default=None,
        description="Optional label for the alignment link (e.g., alignment type).",
        extras={"maxLength": 256},
    )
    sourceIndices: tuple[int, ...] | None = dx.field(
        default_factory=tuple,
        description="Indices into the source sequence.",
    )
    targetIndices: tuple[int, ...] | None = dx.field(
        default_factory=tuple,
        description="Indices into the target sequence.",
    )


class Uuid(dx.Model):
    """A universally unique identifier for cross-referencing annotation objects."""

    value: str = dx.field(
        description="The UUID string value.",
        extras={"minLength": 1, "maxLength": 64},
    )


class ObjectRef(dx.Model):
    """A composable reference to any Layers object, whether local (same record, by UUID), remote (different record, by AT-URI + optional object UUID), or external (knowledge graph entry). This is the universal cross-referencing primitive; consumers dispatch on which field(s) are populated. Used by argumentRef, graphNode, alignment endpoints, and any other cross-object pointer."""  # noqa: E501

    knowledgeRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="Reference to an external knowledge graph node (Wikidata, chive.pub, FrameNet, etc.).",  # noqa: E501
    )
    localId: dx.Embed[Uuid] | None = dx.field(
        default=None,
        description="UUID of an object within the same record.",
    )
    objectId: dx.Embed[Uuid] | None = dx.field(
        default=None,
        description="UUID of a specific object within the record referenced by recordRef.",  # noqa: E501
    )
    recordRef: str | None = dx.field(
        default=None,
        description="AT-URI of a Layers record in another user's PDS or another record in the same PDS.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class MediaScope(dx.Model):
    """Identifies which medium, session clock, stream, and track a sample-indexed or time-indexed anchor is measured against. Absent means the single medium reachable from the annotated expression, which preserves the single-stream reading of records that omit it."""  # noqa: E501

    mediaCid: str | None = dx.field(
        default=None,
        description="CID pinning the exact version of the media record.",
        extras={"format": "cid"},
    )
    mediaRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.media.media record this anchor addresses.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    sessionRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.acquisition.session whose clock the sample and nanosecond times are on.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    stream: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="The session stream this anchor is on; recordRef is the sessionRef and objectId is the stream uuid (acquisition.defs#stream).",  # noqa: E501
    )
    trackIndex: int | None = dx.field(
        default=None,
        description="0-indexed track within the medium (e.g., an audio track or a subtitle track).",  # noqa: E501
        extras={"minimum": 0},
    )


class BoundingBox(dx.Model):
    """A spatial bounding box for image or video frame annotation."""

    frameIndex: int | None = dx.field(
        default=None,
        description="0-indexed frame this box lies on, for framed media.",
        extras={"minimum": 0},
    )
    height: int = dx.field(
        description="Height in pixels.",
        extras={"minimum": 1},
    )
    page: int | None = dx.field(
        default=None,
        description="0-indexed page this box lies on, for paged media.",
        extras={"minimum": 0},
    )
    scope: dx.Embed[MediaScope] | None = dx.field(
        default=None,
        description="Which medium, session clock, stream, and track this box is measured against. Absent means the single medium reachable from the annotated expression.",  # noqa: E501
    )
    timeNanos: int | None = dx.field(
        default=None,
        description="Signed time in nanoseconds, session-relative, at which this box applies.",  # noqa: E501
    )
    unit: str | None = dx.field(
        default=None,
        description="Coordinate unit slug (fallback when unitUri unavailable). Absent means pixel.",  # noqa: E501
        extras={
            "knownValues": (
                "pixel",
                "per-mille-normalized",
            ),
            "maxLength": 32,
        },
    )
    unitUri: str | None = dx.field(
        default=None,
        description="AT-URI of the coordinate unit definition node (a unit typeDef under layers-core.ontology.layers.pub). Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    width: int = dx.field(
        description="Width in pixels.",
        extras={"minimum": 1},
    )
    x: int = dx.field(
        description="X coordinate of top-left corner in pixels.",
    )
    y: int = dx.field(
        description="Y coordinate of top-left corner in pixels.",
    )


class FragmentSelector(dx.Model):
    """W3C FragmentSelector: selects by URI fragment identifier."""

    conformsTo: str | None = dx.field(
        default=None,
        description="Specification the fragment conforms to.",
        extras={"format": "uri"},
    )
    value: str = dx.field(
        description="Fragment identifier value.",
        extras={"maxLength": 1000},
    )


class TextPositionSelector(dx.Model):
    """W3C TextPositionSelector adapted for ATProto: selects by UTF-8 byte offsets. Semantically equivalent to pub.layers.defs#span but named for W3C compatibility with at.margin."""  # noqa: E501

    byteEnd: int = dx.field(
        description="Ending UTF-8 byte position (exclusive).",
        extras={"minimum": 0},
    )
    byteStart: int = dx.field(
        description="Starting UTF-8 byte position (0-indexed, inclusive).",
        extras={"minimum": 0},
    )
    charEnd: int | None = dx.field(
        default=None,
        description="Ending character position (exclusive). Optional; for compatibility with character-offset datasets.",  # noqa: E501
        extras={"minimum": 0},
    )
    charStart: int | None = dx.field(
        default=None,
        description="Starting character position (0-indexed, inclusive). Optional; for compatibility with character-offset datasets.",  # noqa: E501
        extras={"minimum": 0},
    )


class TextQuoteSelector(dx.Model):
    """W3C TextQuoteSelector: selects text by quoting it with surrounding context. Compatible with at.margin.annotation and the W3C Web Annotation Data Model."""  # noqa: E501

    exact: str = dx.field(
        description="The exact text to match.",
        extras={"maxLength": 5000},
    )
    prefix: str | None = dx.field(
        default=None,
        description="Text immediately before the selection.",
        extras={"maxLength": 500},
    )
    suffix: str | None = dx.field(
        default=None,
        description="Text immediately after the selection.",
        extras={"maxLength": 500},
    )


class ExternalTargetSelector(dx.TaggedUnion, discriminator="kind"):
    """W3C selector for identifying the specific segment within the resource."""


class ExternalTargetSelectorTextQuoteSelector(ExternalTargetSelector):
    """The 'textQuoteSelector' member of ExternalTargetSelector."""

    kind: Literal["textQuoteSelector"] = dx.field(
        default="textQuoteSelector",
        description="discriminator pinning this member to textQuoteSelector",
    )
    value: TextQuoteSelector | None = dx.field(
        default=None,
        description="the wrapped member model",
    )


class ExternalTargetSelectorTextPositionSelector(ExternalTargetSelector):
    """The 'textPositionSelector' member of ExternalTargetSelector."""

    kind: Literal["textPositionSelector"] = dx.field(
        default="textPositionSelector",
        description="discriminator pinning this member to textPositionSelector",
    )
    value: TextPositionSelector | None = dx.field(
        default=None,
        description="the wrapped member model",
    )


class ExternalTargetSelectorFragmentSelector(ExternalTargetSelector):
    """The 'fragmentSelector' member of ExternalTargetSelector."""

    kind: Literal["fragmentSelector"] = dx.field(
        default="fragmentSelector",
        description="discriminator pinning this member to fragmentSelector",
    )
    value: FragmentSelector | None = dx.field(
        default=None,
        description="the wrapped member model",
    )


class ExternalTarget(dx.Model):
    """Target for annotating external resources (web pages, documents, etc.). Compatible with at.margin's target model and the W3C Web Annotation Data Model."""  # noqa: E501

    selector: ExternalTargetSelector | None = dx.field(
        default=None,
        description="W3C selector for identifying the specific segment within the resource.",  # noqa: E501
    )
    source: str = dx.field(
        description="The URI of the external resource being annotated.",
        extras={"format": "uri"},
    )
    sourceHash: str | None = dx.field(
        default=None,
        description="SHA256 hash of normalized URI for indexing.",
        extras={"maxLength": 128},
    )
    title: str | None = dx.field(
        default=None,
        description="Title of the resource at annotation time.",
        extras={"maxLength": 500},
    )


class Span(dx.Model):
    """A contiguous span of text defined by UTF-8 byte offsets."""

    byteEnd: int = dx.field(
        description="Exclusive end UTF-8 byte offset.",
        extras={"minimum": 0},
    )
    byteStart: int = dx.field(
        description="Inclusive start UTF-8 byte offset (0-indexed).",
        extras={"minimum": 0},
    )
    charEnd: int | None = dx.field(
        default=None,
        description="Exclusive end character offset. Optional; for compatibility with character-offset datasets.",  # noqa: E501
        extras={"minimum": 0},
    )
    charStart: int | None = dx.field(
        default=None,
        description="Inclusive start character offset. Optional; for compatibility with character-offset datasets.",  # noqa: E501
        extras={"minimum": 0},
    )


class PageAnchor(dx.Model):
    """Anchor to a specific page and region in a paged document (PDF, etc.). Compatible with chive.pub's page-level annotation model."""  # noqa: E501

    boundingBox: dx.Embed[BoundingBox] | None = dx.field(
        default=None,
        description="Bounding box of the anchored region within the page.",
    )
    page: int = dx.field(
        description="0-indexed page number.",
        extras={"minimum": 0},
    )
    textSpan: dx.Embed[Span] | None = dx.field(
        default=None,
        description="Character offsets within the page text.",
    )


class FrequencyBand(dx.Model):
    """A frequency band selecting a sub-band of a continuous signal (e.g., an EEG rhythm or a speech formant). Follows the URI+slug pattern; explicit low/high bounds override the slug where present."""  # noqa: E501

    band: str | None = dx.field(
        default=None,
        description="Frequency band slug (fallback when bandUri unavailable).",
        extras={
            "knownValues": (
                "delta",
                "theta",
                "alpha",
                "mu",
                "beta",
                "low-gamma",
                "high-gamma",
                "ripple",
                "broadband",
                "f0",
                "f1",
                "f2",
                "f3",
                "f4",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    bandUri: str | None = dx.field(
        default=None,
        description="AT-URI of the frequency band definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    highMilliHz: int | None = dx.field(
        default=None,
        description="Upper bound of the band in millihertz.",
        extras={"minimum": 0},
    )
    lowMilliHz: int | None = dx.field(
        default=None,
        description="Lower bound of the band in millihertz.",
        extras={"minimum": 0},
    )


class SpatialEntity(dx.Model):
    """A normalized spatial value representing a point, region, line, or complex geometry. Parallel to temporalEntity. Subsumes GeoJSON geometry types, WKT primitives, and ISO 19107 spatial schema. Consumers dispatch on which fields are populated: bbox only (pixel bounding box), geometry+type (parsed geometry string), geometry+geometryFormat (format-specific parsing)."""  # noqa: E501

    articulator: str | None = dx.field(
        default=None,
        description="Articulator slug (fallback when articulatorUri unavailable), naming the body part or articulator this region tracks.",  # noqa: E501
        extras={
            "knownValues": (
                "dominant-hand",
                "non-dominant-hand",
                "both-hands",
                "head",
                "torso",
                "face",
                "eyebrows",
                "mouth",
                "eye-gaze",
                "tongue",
                "lips",
                "jaw",
                "velum",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    articulatorUri: str | None = dx.field(
        default=None,
        description="AT-URI of the articulator definition node (an articulator typeDef under layers-annotation.ontology.layers.pub). Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    bbox: dx.Embed[BoundingBox] | None = dx.field(
        default=None,
        description="Structured pixel bounding box (axis-aligned rectangle). The most common case for image/video annotation.",  # noqa: E501
    )
    crs: str | None = dx.field(
        default=None,
        description="Coordinate reference system slug (fallback when crsUri unavailable). Determines how coordinates in geometry/bbox are interpreted.",  # noqa: E501
        extras={
            "knownValues": (
                "pixel",
                "percentage",
                "wgs84",
                "web-mercator",
                "per-mille-normalized",
                "mni152-nlin-2009c",
                "mni305",
                "talairach",
                "acpc",
                "scanner-ras",
                "fsaverage",
                "individual-t1",
                "voxel-index",
                "world-metric",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    crsUri: str | None = dx.field(
        default=None,
        description="AT-URI of the coordinate reference system definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    dimensions: int | None = dx.field(
        default=None,
        description="Number of coordinate dimensions (2 for planar, 3 for volumetric/elevation).",  # noqa: E501
        extras={"minimum": 2, "maximum": 4},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features of this spatial value not reached by the named fields.",  # noqa: E501
    )
    frameIndex: int | None = dx.field(
        default=None,
        description="0-indexed frame this region lies on, for framed media.",
        extras={"minimum": 0},
    )
    geometry: str | None = dx.field(
        default=None,
        description="Geometry as a string in the format specified by geometryFormat. WKT examples: 'POINT(37.7749 -122.4194)', 'POLYGON((0 0, 100 0, 100 100, 0 100, 0 0))'. GeoJSON example: '{\"type\":\"Point\",\"coordinates\":[-122.4194,37.7749]}'. SVG path example: 'M 10 10 L 100 10 L 100 100 Z'. Default format is WKT.",  # noqa: E501
        extras={"maxLength": 65536},
    )
    geometryFormat: str | None = dx.field(
        default=None,
        description="Format of the geometry string (fallback when geometryFormatUri unavailable). Default is WKT.",  # noqa: E501
        extras={
            "knownValues": (
                "wkt",
                "geojson",
                "svg-path",
                "coco-polygon",
                "coco-rle",
                "page-xml-coords",
                "alto-polygon",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    geometryFormatUri: str | None = dx.field(
        default=None,
        description="AT-URI of the geometry format definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    maskMediaRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.media.media record carrying a pixel or voxel mask for this region.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    page: int | None = dx.field(
        default=None,
        description="0-indexed page this region lies on, for paged media.",
        extras={"minimum": 0},
    )
    parcelRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="Reference to an atlas parcel grounding this region (e.g., an Uberon or atlas node).",  # noqa: E501
    )
    readingOrder: int | None = dx.field(
        default=None,
        description="0-indexed reading order of this region among sibling regions on the same page or surface.",  # noqa: E501
        extras={"minimum": 0},
    )
    role: str | None = dx.field(
        default=None,
        description="Spatial-region role slug (fallback when roleUri unavailable), naming what layout or anatomical part this region is.",  # noqa: E501
        extras={
            "knownValues": (
                "text-region",
                "text-line",
                "baseline",
                "word",
                "glyph",
                "column",
                "margin-note",
                "figure",
                "table",
                "instance-mask",
                "interest-area",
                "articulator-contour",
                "region-of-interest",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    roleUri: str | None = dx.field(
        default=None,
        description="AT-URI of the spatial-region role definition node (a role typeDef under layers-annotation.ontology.layers.pub). Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    scope: dx.Embed[MediaScope] | None = dx.field(
        default=None,
        description="Which medium, session clock, stream, and track this region is measured against. Absent means the single medium reachable from the annotated expression.",  # noqa: E501
    )
    sensors: tuple[dx.Embed[ObjectRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Sensors whose positions define this region; each objectRef has recordRef the media record and objectId a sensorSpec uuid.",  # noqa: E501
    )
    timeNanos: int | None = dx.field(
        default=None,
        description="Signed time in nanoseconds, session-relative, at which this region applies.",  # noqa: E501
    )
    type: str | None = dx.field(
        default=None,
        description="Geometry type slug (fallback when typeUri unavailable). For dispatch without parsing the geometry string.",  # noqa: E501
        extras={
            "knownValues": (
                "point",
                "box",
                "polygon",
                "multi-polygon",
                "line-string",
                "multi-line-string",
                "circle",
                "ellipse",
                "multi-point",
                "geometry-collection",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    typeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the geometry type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    uncertainty: str | None = dx.field(
        default=None,
        description="Spatial precision or uncertainty radius as a string with units (e.g., '50m', '10px', '0.001deg'). Units depend on the CRS.",  # noqa: E501
        extras={"maxLength": 64},
    )


class SignalSpan(dx.Model):
    """A span over one or more channels of a continuous signal (EEG, MEG, ECoG, audio waveform, motion or eye-tracking stream). Addressable by sample index or by session-relative nanoseconds; scope is required because an unscoped sample index is meaningless."""  # noqa: E501

    channelNames: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Advisory channel-name fallback; channels wins where both are present.",  # noqa: E501
    )
    channels: tuple[dx.Embed[ObjectRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Channels this span covers; each objectRef has recordRef the media record and objectId a signalChannel uuid. Empty or absent means all channels.",  # noqa: E501
    )
    endSample: int | None = dx.field(
        default=None,
        description="Exclusive end sample, signed.",
    )
    endingNanos: int | None = dx.field(
        default=None,
        description="Signed end on the stream or session clock, session-relative.",
    )
    epochIndex: int | None = dx.field(
        default=None,
        description="0-indexed epoch within an epoched signal.",
        extras={"minimum": 0},
    )
    frequencyBand: dx.Embed[FrequencyBand] | None = dx.field(
        default=None,
        description="Frequency band this span selects, for time-frequency annotation.",
    )
    region: dx.Embed[SpatialEntity] | None = dx.field(
        default=None,
        description="Spatial region this span applies to, reusing the promoted spatial anchor (no separate voxel-region type is introduced).",  # noqa: E501
    )
    scope: dx.Embed[MediaScope] = dx.field(
        description="Which medium, session clock, stream, and track the sample and nanosecond indices are measured against. Required.",  # noqa: E501
    )
    sensors: tuple[dx.Embed[ObjectRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Sensors this span covers; each objectRef has recordRef the media record and objectId a sensorSpec uuid.",  # noqa: E501
    )
    startNanos: int | None = dx.field(
        default=None,
        description="Signed start on the stream or session clock, session-relative and never UTC-epoch. Authoritative when startSample is absent; startSample wins where both are present.",  # noqa: E501
    )
    startSample: int | None = dx.field(
        default=None,
        description="Inclusive 0-indexed start sample, signed (may precede the clock origin).",  # noqa: E501
    )
    volumeIndexEnd: int | None = dx.field(
        default=None,
        description="Exclusive end volume, for volumetric time series.",
        extras={"minimum": 0},
    )
    volumeIndexStart: int | None = dx.field(
        default=None,
        description="Inclusive 0-indexed start volume, for volumetric time series (e.g., fMRI runs).",  # noqa: E501
        extras={"minimum": 0},
    )


class Keyframe(dx.Model):
    """A spatial annotation at a specific time point."""

    bbox: dx.Embed[BoundingBox] = dx.field(
        description="The spatial bounding box occupied at this time point.",
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Per-keyframe features (e.g., visibility, occlusion percentage, confidence, pose data).",  # noqa: E501
    )
    timeMs: int = dx.field(
        description="Time in milliseconds.",
        extras={"minimum": 0},
    )


class TemporalSpan(dx.Model):
    """A temporal span within a media source, defined by start and end times in milliseconds on the referenced session or stream clock. Times are signed and session-relative (they may precede the clock origin, matching BIDS StartTime); they are never UTC-epoch values."""  # noqa: E501

    ending: int = dx.field(
        description="End time in milliseconds, signed and session-relative.",
    )
    endingNanos: int | None = dx.field(
        default=None,
        description="Exact signed end in nanoseconds, session-relative; authoritative over ending where both are present.",  # noqa: E501
    )
    scope: dx.Embed[MediaScope] | None = dx.field(
        default=None,
        description="Which medium, session clock, stream, and track this span is measured against. Absent means the single medium reachable from the annotated expression.",  # noqa: E501
    )
    start: int = dx.field(
        description="Start time in milliseconds, signed and session-relative (may be negative when it precedes the clock origin).",  # noqa: E501
    )
    startNanos: int | None = dx.field(
        default=None,
        description="Exact signed start in nanoseconds, session-relative; authoritative over start where both are present.",  # noqa: E501
    )


class SpatioTemporalAnchor(dx.Model):
    """Combined spatial and temporal anchor for video annotation with keyframe-based tracking."""  # noqa: E501

    interpolation: str | None = dx.field(
        default=None,
        description="Interpolation mode slug (fallback when interpolationUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "linear",
                "step",
                "cubic",
            )
        },
    )
    interpolationUri: str | None = dx.field(
        default=None,
        description="AT-URI of the interpolation mode definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    keyframes: tuple[dx.Embed[Keyframe], ...] | None = dx.field(
        default_factory=tuple,
        description="Keyframes defining spatial positions at specific times.",
    )
    temporalSpan: dx.Embed[TemporalSpan] = dx.field(
        description="The temporal extent over which this spatio-temporal region is tracked.",  # noqa: E501
    )


class TokenRef(dx.Model):
    """A reference to a specific token within a tokenization, by index."""

    tokenIndex: int = dx.field(
        description="0-based index of the token within its tokenization.",
        extras={"minimum": 0},
    )
    tokenizationId: dx.Embed[Uuid] = dx.field(
        description="UUID of the tokenization containing the referenced token.",
    )


class TokenRefSequence(dx.Model):
    """A sequence of token references, possibly non-contiguous, within a single tokenization."""  # noqa: E501

    anchorTokenIndex: int | None = dx.field(
        default=None,
        description="Optional head/anchor token index within the sequence.",
        extras={"minimum": 0},
    )
    tokenIndexes: tuple[int, ...] = dx.field(
        description="0-based indices of the tokens.",
    )
    tokenizationId: dx.Embed[Uuid] = dx.field(
        description="UUID of the tokenization containing the referenced tokens.",
    )


class Anchor(dx.Model):
    """Abstract anchor: how an annotation attaches to its source data. This is a polymorphic type; at least one anchoring field should be present. Consumers dispatch on which field(s) are populated."""  # noqa: E501

    boundingBox: dx.Embed[BoundingBox] | None = dx.field(
        default=None,
        description="Static spatial region in an image or single frame. Imposes no temporal span; for a region that tracks over time use spatioTemporalAnchor.",  # noqa: E501
    )
    externalTarget: dx.Embed[ExternalTarget] | None = dx.field(
        default=None,
        description="External resource target (web page, document, etc.).",
    )
    pageAnchor: dx.Embed[PageAnchor] | None = dx.field(
        default=None,
        description="Page and region in a paged document.",
    )
    signalSpan: dx.Embed[SignalSpan] | None = dx.field(
        default=None,
        description="Sample-indexed or time-indexed span over one or more channels of a continuous signal (EEG, MEG, audio waveform, sensor stream, etc.).",  # noqa: E501
    )
    spatialRegion: dx.Embed[SpatialEntity] | None = dx.field(
        default=None,
        description="Normalized spatial region used as an anchor (aliased so anchor-use is distinct from the annotation.spatial content-use of the same type).",  # noqa: E501
    )
    spatioTemporalAnchor: dx.Embed[SpatioTemporalAnchor] | None = dx.field(
        default=None,
        description="Spatio-temporal region in video.",
    )
    temporalSpan: dx.Embed[TemporalSpan] | None = dx.field(
        default=None,
        description="Temporal span in audio/video.",
    )
    textSpan: dx.Embed[Span] | None = dx.field(
        default=None,
        description="Character-offset span in the expression text.",
    )
    tokenRef: dx.Embed[TokenRef] | None = dx.field(
        default=None,
        description="Single token reference.",
    )
    tokenRefSequence: dx.Embed[TokenRefSequence] | None = dx.field(
        default=None,
        description="Sequence of token references (possibly non-contiguous).",
    )


class ContentDigest(dx.Model):
    """A structured content hash for integrity verification. Separates the algorithm from the digest value so verifiers dispatch on algorithm rather than parsing a packed string."""  # noqa: E501

    algorithm: str = dx.field(
        description="Digest algorithm slug (fallback when algorithmUri unavailable).",
        extras={
            "knownValues": (
                "sha256",
                "sha512",
                "blake3",
                "md5",
                "custom",
            ),
            "maxLength": 32,
        },
    )
    algorithmUri: str | None = dx.field(
        default=None,
        description="AT-URI of the digest algorithm definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    value: str = dx.field(
        description="The digest as lowercase hexadecimal.",
        extras={"maxLength": 160},
    )


class AnnotationMetadata(dx.Model):
    """Metadata about who or what produced an annotation, when, and with what confidence. The three key provenance fields are: agent (who did it), personaRef (under what framework), and tool (with what software)."""  # noqa: E501

    agent: dx.Embed[AgentRef] | None = dx.field(
        default=None,
        description="The agent (human or model) that produced this annotation. Distinct from personaRef (the interpretive framework) and tool (the software).",  # noqa: E501
    )
    confidence: int | None = dx.field(
        default=None,
        description="Confidence score scaled 0-1000 (to avoid floats). 1000 = maximum confidence.",  # noqa: E501
        extras={"minimum": 0, "maximum": 1000},
    )
    contentDigest: dx.Embed[ContentDigest] | None = dx.field(
        default=None,
        description="Structured content hash for integrity verification of this annotation.",  # noqa: E501
    )
    dependencies: tuple[dx.Embed[ObjectRef], ...] | None = dx.field(
        default_factory=tuple,
        description="References to upstream records this annotation was derived from.",
    )
    personaRef: str | None = dx.field(
        default=None,
        description="Reference to the persona/annotation framework under which this annotation was produced. Distinct from agent (who did it).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    timestamp: datetime | None = dx.field(
        default=None,
        description="When the annotation was produced.",
        extras={"format": "datetime"},
    )
    tool: str = dx.field(
        description="Name or identifier of the software tool used to produce this annotation (e.g., 'spaCy 3.7', 'brat 1.3', 'ELAN 6.4'). Distinct from agent (who ran the tool). Display fallback when toolRef is unavailable.",  # noqa: E501
        extras={"maxLength": 512},
    )
    toolRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="Grounded reference to the software tool, typically via rrid (a Research Resource Identifier). Distinct from agent (who ran the tool).",  # noqa: E501
    )


class Constraint(dx.Model):
    """An abstract constraint expression. Used for type constraints on role slots, slot-level constraints in templates, cross-slot agreement constraints, and any other declarative restriction. The expression field holds a DSL string whose format is identified by expressionFormat/expressionFormatUri."""  # noqa: E501

    context: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Names of the slots or variables this constraint ranges over (for cross-slot and cross-template constraints).",  # noqa: E501
    )
    description: str | None = dx.field(
        default=None,
        description="Human-readable description of the constraint.",
        extras={"maxLength": 2048},
    )
    expression: str = dx.field(
        description="The constraint expression (e.g., 'self.pos == \"VERB\"', 'subject.features.number == verb.features.number').",  # noqa: E501
        extras={"maxLength": 4096},
    )
    expressionFormat: str | None = dx.field(
        default=None,
        description="Expression format slug (fallback when expressionFormatUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "python-expr",
                "json-logic",
                "regex",
                "sparql-filter",
                "type-ref",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    expressionFormatUri: str | None = dx.field(
        default=None,
        description="AT-URI of the expression format definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    scope: str | None = dx.field(
        default=None,
        description="Constraint scope slug (fallback when scopeUri unavailable).",
        extras={
            "knownValues": (
                "slot",
                "template",
                "cross-template",
                "global",
            ),
            "maxLength": 128,
        },
    )
    scopeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the scope definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class EthicsApproval(dx.Model):
    """A reference to an ethics or institutional review board approval covering a piece of work. Shared across acquisition consent, sessions, and reproducibility info."""  # noqa: E501

    approvedAt: datetime | None = dx.field(
        default=None,
        description="When the approval was granted.",
        extras={"format": "datetime"},
    )
    bodyName: str | None = dx.field(
        default=None,
        description="Advisory name of the approving board; bodyRef wins where both are present.",  # noqa: E501
        extras={"maxLength": 512},
    )
    bodyRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="The approving board, grounded via ror; clinicaltrials for a registered trial.",  # noqa: E501
    )
    expiresAt: datetime | None = dx.field(
        default=None,
        description="When the approval expires.",
        extras={"format": "datetime"},
    )
    protocolId: str = dx.field(
        description="Protocol or approval number.",
        extras={"maxLength": 256},
    )
    uri: str | None = dx.field(
        default=None,
        description="URI of the approval record.",
        extras={"format": "uri", "maxLength": 2048},
    )


class FundingRef(dx.Model):
    """A reference to a grant or award that funded a piece of work. Shared across acquisition consent and reproducibility info."""  # noqa: E501

    awardId: str = dx.field(
        description="Grant or award number.",
        extras={"maxLength": 256},
    )
    funderRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="The funding body, grounded via ror or the Crossref Funder Registry.",  # noqa: E501
    )
    title: str | None = dx.field(
        default=None,
        description="Title of the grant or award.",
        extras={"maxLength": 1024},
    )
    uri: str | None = dx.field(
        default=None,
        description="URI of the award record.",
        extras={"format": "uri", "maxLength": 2048},
    )


class ReproducibilityInfo(dx.Model):
    """Information about how to reproduce a dataset or the data produced from an eprint. Shared by data-producing produces (corpus, annotation layers, experiments) and eprint data links."""  # noqa: E501

    codeUri: str | None = dx.field(
        default=None,
        description="URI of the code repository.",
        extras={"format": "uri", "maxLength": 2048},
    )
    command: str | None = dx.field(
        default=None,
        description="Command to reproduce the data.",
        extras={"maxLength": 4096},
    )
    commitHash: str | None = dx.field(
        default=None,
        description="Git commit hash for reproducibility.",
        extras={"maxLength": 64},
    )
    container: str | None = dx.field(
        default=None,
        description="The container or environment image the procedure ran in.",
    )
    environment: str | None = dx.field(
        default=None,
        description="Environment specification (Docker image, conda env, etc.).",
        extras={"maxLength": 2048},
    )
    ethicsApprovals: tuple[dx.Embed[EthicsApproval], ...] | None = dx.field(
        default_factory=tuple,
        description="Ethics or IRB approvals covering the work producing this data.",
    )
    funding: tuple[dx.Embed[FundingRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Grants or awards that funded the work producing this data.",
    )
    name: str | None = dx.field(
        default=None,
        description="Human-readable name of the pipeline, model, or procedure that produced the data.",  # noqa: E501
        extras={"maxLength": 256},
    )
    operatingSystem: str | None = dx.field(
        default=None,
        description="Operating system the procedure ran on.",
        extras={"maxLength": 256},
    )
    randomSeed: int | None = dx.field(
        default=None,
        description="Random seed used.",
    )
    softwareRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Grounded references to the software used, typically via rrid (Research Resource Identifiers).",  # noqa: E501
    )
    version: str | None = dx.field(
        default=None,
        description="Version string of the pipeline, model, or procedure.",
        extras={"maxLength": 64},
    )


class DeviceInfo(dx.Model):
    """An instrument used in acquisition. Manufacturer, product and software are GROUNDED through defs#knowledgeRef rather than enumerated: an organization is a citable entity reachable via ror and wikidata, a package via rrid, and enumerating vendors in a released lexicon makes a rebrand a lexicon version bump. BIDS Manufacturer, ManufacturersModelName, DeviceSerialNumber, SoftwareVersions, SoftwareRRID; NWB Device."""  # noqa: E501

    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended device features not captured by the typed fields.",
    )
    kind: str = dx.field(
        description="Device kind slug (fallback when kindUri unavailable).",
        extras={
            "knownValues": (
                "microphone",
                "camera",
                "scanner",
                "eeg-amplifier",
                "electrode-cap",
                "meg-scanner",
                "mri-scanner",
                "fnirs-system",
                "electrode-array",
                "eye-tracker",
                "motion-capture-system",
                "articulograph",
                "ultrasound-system",
                "button-box",
                "keyboard",
                "mouse",
                "touchscreen",
                "response-glove",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the device kind definition node (typeDef of `device-kind`). MUST resolve into the same `modality` node set as recordingMethod.methodUri where the two overlap, so an instrument named in a protocol and the same instrument named in a session join.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    manufacturerName: str | None = dx.field(
        default=None,
        description="Display name when no identifier exists. Advisory; manufacturerRef wins.",  # noqa: E501
        extras={"maxLength": 256},
    )
    manufacturerRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="Manufacturer, grounded via source ror or wikidata. Replaces a free-text vendor name: MEGIN, Elekta and Elekta/MEGIN are one organization and must facet as one.",  # noqa: E501
    )
    model: str | None = dx.field(
        default=None,
        description="BIDS ManufacturersModelName, as printed on the device.",
        extras={"maxLength": 256},
    )
    productRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="The product, grounded via rrid where one exists.",
    )
    serialNumber: str | None = dx.field(
        default=None,
        description="BIDS DeviceSerialNumber. A serial number can be a de-anonymizing quasi-identifier in a single-site study; omit it when the participant's identifiability is anonymous.",  # noqa: E501
        extras={"maxLength": 256},
    )
    software: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
        description="Acquisition or presentation software, reusing the shared reproducibility block rather than re-declaring softwareName, softwareVersion, codeUri and operatingSystem. BIDS SoftwareVersions and GeneratedBy.",  # noqa: E501
    )


class LanguageRef(dx.Model):
    """A structured reference to a language or language variety, decomposing a BCP-47 tag into its codes plus a knowledge-graph grounding and a role. The tag is the canonical addressable key; importers normalize it on write."""  # noqa: E501

    knowledgeRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="Grounding of the language, with source glottolog, iso639-3, or cldr.",  # noqa: E501
    )
    languageUri: str | None = dx.field(
        default=None,
        description="AT-URI of the language definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    regionCode: str | None = dx.field(
        default=None,
        description="ISO 3166-1 or UN M.49 region code.",
        extras={"maxLength": 8},
    )
    role: str | None = dx.field(
        default=None,
        description="Language-role slug (fallback when roleUri unavailable), naming the role this language plays in the record.",  # noqa: E501
        extras={
            "knownValues": (
                "primary",
                "source",
                "target",
                "metalanguage",
                "gloss",
                "translation",
                "contact",
                "l1",
                "l2",
                "heritage",
                "simultaneous-bilingual",
                "signed-l1",
                "signed-l2",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    roleUri: str | None = dx.field(
        default=None,
        description="AT-URI of the language-role definition node (a language-role typeDef under layers-core.ontology.layers.pub). Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    scriptCode: str | None = dx.field(
        default=None,
        description="ISO 15924 script code.",
        extras={"maxLength": 8},
    )
    tag: str = dx.field(
        description="Canonical BCP-47 tag using the shortest ISO 639 code (en not eng, fi not fin, poma for Pomak). Importers must normalize on write.",  # noqa: E501
        extras={"maxLength": 32},
    )
    varietyLabel: str | None = dx.field(
        default=None,
        description="Prose residue naming the variety after every code applies.",
        extras={"maxLength": 256},
    )


class LicenseRef(dx.Model):
    """Detail for a single license. Follows the URI+slug pattern (spdxUri is the canonical knowledge-graph node, spdx is the human-readable fallback) and mirrors one entry of a DataCite rightsList (rightsIdentifier + rightsURI)."""  # noqa: E501

    appliesTo: str | None = dx.field(
        default=None,
        description="Component this license covers when an artifact mixes licenses by part (fallback when appliesToUri unavailable). Omit when the license covers the whole artifact.",  # noqa: E501
        extras={
            "knownValues": (
                "whole",
                "annotations",
                "underlying-text",
                "underlying-media",
                "code",
                "documentation",
                "ontology",
                "derived-data",
                "custom",
            ),
            "maxLength": 256,
        },
    )
    appliesToUri: str | None = dx.field(
        default=None,
        description="AT-URI of the license-component definition node (a license-component typeDef under layers-core.ontology.layers.pub). Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    attribution: str | None = dx.field(
        default=None,
        description="Required attribution / credit text for downstream users.",
        extras={"maxLength": 2048},
    )
    name: str | None = dx.field(
        default=None,
        description="Human-readable license name (e.g., 'Creative Commons Attribution 4.0 International').",  # noqa: E501
        extras={"maxLength": 256},
    )
    notes: str | None = dx.field(
        default=None,
        description="Additional licensing notes, restrictions, or usage terms.",
        extras={"maxLength": 4096},
    )
    spdx: str = dx.field(
        description="SPDX license identifier (fallback when spdxUri unavailable). Non-SPDX terms use 'proprietary' or 'custom' and ground the full text via spdxUri/url.",  # noqa: E501
        extras={
            "knownValues": (
                "CC0-1.0",
                "CC-BY-4.0",
                "CC-BY-SA-4.0",
                "CC-BY-NC-4.0",
                "CC-BY-NC-SA-4.0",
                "CC-BY-ND-4.0",
                "CC-BY-NC-ND-4.0",
                "MIT",
                "Apache-2.0",
                "BSD-3-Clause",
                "GPL-3.0-only",
                "LGPL-3.0-only",
                "LDC-User-Agreement",
                "ELRA-END-USER",
                "proprietary",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    spdxUri: str | None = dx.field(
        default=None,
        description="AT-URI of the license definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    url: str | None = dx.field(
        default=None,
        description="URL of the full license text (DataCite rightsURI).",
        extras={"format": "uri", "maxLength": 2048},
    )


class Licensing(dx.Model):
    """Complete licensing terms for a released artifact. Represents single, dual/multi (choose-one), composite (all-apply), exception (WITH), and component-scoped licensing. The SPDX license expression encodes the boolean relationship between licenses; the licenses array carries per-license detail."""  # noqa: E501

    expression: str | None = dx.field(
        default=None,
        description="SPDX license expression encoding the relationship between licenses: OR for dual/multi-licensing (the licensee chooses one), AND for composite terms (all apply), WITH for exceptions. Examples: 'MIT OR Apache-2.0', 'CC-BY-4.0 AND LicenseRef-LDC-User-Agreement'. Optional when a single license applies.",  # noqa: E501
        extras={"maxLength": 512},
    )
    licenses: tuple[dx.Embed[LicenseRef], ...] = dx.field(
        description="The individual licenses named by the expression, or the single governing license. Each entry may scope itself to a component via appliesTo.",  # noqa: E501
    )


class SpatialModifier(dx.Model):
    """Qualitative modification of a spatial value. Parallel to temporalModifier. Indicates precision, derivation method, or processing applied to a spatial entity."""  # noqa: E501

    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features of this spatial modifier not reached by the named fields.",  # noqa: E501
    )
    mod: str | None = dx.field(
        default=None,
        description="Spatial modifier slug (fallback when modUri unavailable).",
        extras={
            "knownValues": (
                "approximate",
                "projected",
                "interpolated",
                "estimated",
                "buffered",
                "simplified",
                "generalized",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    modUri: str | None = dx.field(
        default=None,
        description="AT-URI of the spatial modifier definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class SpatialExpression(dx.Model):
    """A complete spatial annotation packaging the expression type, normalized value, modifier, anchoring, and document function. Parallel to temporalExpression. Subsumes ISO-Space place annotations (ISO 24617-7), SpatialML PLACE elements, and general spatial semantic annotation. Attach to annotation objects via the spatial field."""  # noqa: E501

    anchorRef: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="What this spatial expression is relative to (e.g., a landmark annotation, a reference location, a trajector). For relative spatial expressions like 'behind the building'.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features of this spatial annotation not reached by the named fields.",  # noqa: E501
    )
    function: str | None = dx.field(
        default=None,
        description="Document function slug (fallback when functionUri unavailable). What role this place plays in the document.",  # noqa: E501
        extras={
            "knownValues": (
                "document-location",
                "publication-location",
                "situation-location",
                "origin",
                "destination",
                "waypoint",
                "none",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    functionUri: str | None = dx.field(
        default=None,
        description="AT-URI of the document function definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    modifier: dx.Embed[SpatialModifier] | None = dx.field(
        default=None,
        description="Qualitative modifier (approximate, projected, interpolated, etc.).",  # noqa: E501
    )
    type: str | None = dx.field(
        default=None,
        description="Spatial expression type slug (fallback when typeUri unavailable). Maps to ISO-Space spatial entity types.",  # noqa: E501
        extras={
            "knownValues": (
                "location",
                "region",
                "path",
                "direction",
                "distance",
                "relative",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    typeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the spatial expression type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    value: dx.Embed[SpatialEntity] | None = dx.field(
        default=None,
        description="The normalized spatial value.",
    )


class TemporalEntity(dx.Model):
    """A normalized temporal value representing a point, interval, duration, or uncertain range in calendar/clock time. Subsumes OWL-Time TemporalEntity (Instant, Interval, Duration) and TimeML TIMEX3 value. Consumers dispatch on which fields are populated: instant only (point), intervalStart+intervalEnd (bounded interval), duration only (pure duration), earliest+latest (uncertain bounds), recurrence (repeating pattern)."""  # noqa: E501

    calendar: str | None = dx.field(
        default=None,
        description="Calendar system slug (fallback when calendarUri unavailable). Maps to OWL-Time TRS (Temporal Reference System).",  # noqa: E501
        extras={
            "knownValues": (
                "gregorian",
                "julian",
                "hijri",
                "hebrew",
                "iso-week",
                "unix",
                "japanese-imperial",
                "buddhist",
                "coptic",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    calendarUri: str | None = dx.field(
        default=None,
        description="AT-URI of the calendar system definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    duration: str | None = dx.field(
        default=None,
        description="Duration as ISO 8601 duration (e.g., 'P3Y', 'PT2H30M', 'P1DT12H'). Maps to OWL-Time hasTemporalDuration.",  # noqa: E501
        extras={"maxLength": 64},
    )
    earliest: str | None = dx.field(
        default=None,
        description="Lower bound for uncertain or vague times, as ISO 8601 datetime.",
        extras={"maxLength": 64},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features of this temporal value not reached by the named fields.",  # noqa: E501
    )
    granularity: str | None = dx.field(
        default=None,
        description="Temporal granularity slug (fallback when granularityUri unavailable). Maps to OWL-Time unitType.",  # noqa: E501
        extras={
            "knownValues": (
                "millennium",
                "century",
                "decade",
                "year",
                "quarter",
                "month",
                "week",
                "day",
                "hour",
                "minute",
                "second",
                "millisecond",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    granularityUri: str | None = dx.field(
        default=None,
        description="AT-URI of the granularity definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    instant: str | None = dx.field(
        default=None,
        description="Point in time as ISO 8601 datetime (e.g., '2024-03-15', '2024-03-15T14:30:00Z'). Maps to OWL-Time Instant.",  # noqa: E501
        extras={"maxLength": 64},
    )
    intervalEnd: str | None = dx.field(
        default=None,
        description="Interval end as ISO 8601 datetime. Maps to OWL-Time hasEnd.",
        extras={"maxLength": 64},
    )
    intervalStart: str | None = dx.field(
        default=None,
        description="Interval start as ISO 8601 datetime. Maps to OWL-Time hasBeginning.",  # noqa: E501
        extras={"maxLength": 64},
    )
    latest: str | None = dx.field(
        default=None,
        description="Upper bound for uncertain or vague times, as ISO 8601 datetime.",
        extras={"maxLength": 64},
    )
    recurrence: str | None = dx.field(
        default=None,
        description="ISO 8601 repeating interval (e.g., 'R/P1W' for weekly, 'R5/P1D' for 5 daily repetitions).",  # noqa: E501
        extras={"maxLength": 128},
    )


class TemporalModifier(dx.Model):
    """Qualitative modification of a temporal value. Subsumes TimeML TIMEX3 mod attribute and OWL-Time DateTimeDescription qualifiers."""  # noqa: E501

    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features of this temporal modifier not reached by the named fields.",  # noqa: E501
    )
    mod: str | None = dx.field(
        default=None,
        description="Temporal modifier slug (fallback when modUri unavailable). Maps to TimeML TIMEX3 mod.",  # noqa: E501
        extras={
            "knownValues": (
                "approximate",
                "early",
                "mid",
                "late",
                "start",
                "end",
                "before",
                "after",
                "on-or-before",
                "on-or-after",
                "less-than",
                "more-than",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    modUri: str | None = dx.field(
        default=None,
        description="AT-URI of the temporal modifier definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class TemporalExpression(dx.Model):
    """A complete temporal annotation packaging the expression type, normalized value, modifier, anchoring, and document function. Subsumes TimeML TIMEX3 and OWL-Time GeneralDateTimeDescription. Attach to annotation objects via the temporal field."""  # noqa: E501

    anchorRef: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="What this temporal expression is relative to (e.g., document creation time, another temporal expression, a situation). Maps to TimeML anchorTimeID.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features of this temporal annotation not reached by the named fields.",  # noqa: E501
    )
    function: str | None = dx.field(
        default=None,
        description="Document function slug (fallback when functionUri unavailable). Maps to TimeML functionInDocument.",  # noqa: E501
        extras={
            "knownValues": (
                "creation-time",
                "publication-time",
                "expiration-time",
                "modification-time",
                "release-time",
                "reception-time",
                "none",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    functionUri: str | None = dx.field(
        default=None,
        description="AT-URI of the document function definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    modifier: dx.Embed[TemporalModifier] | None = dx.field(
        default=None,
        description="Qualitative modifier (approximate, early, late, etc.).",
    )
    type: str | None = dx.field(
        default=None,
        description="Temporal expression type slug (fallback when typeUri unavailable). Maps to TimeML TIMEX3 type.",  # noqa: E501
        extras={
            "knownValues": (
                "date",
                "time",
                "duration",
                "set",
                "interval",
                "relative",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    typeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the temporal expression type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    value: dx.Embed[TemporalEntity] | None = dx.field(
        default=None,
        description="The normalized temporal value.",
    )
