# generated by lairs gen; do not edit
# lexicon tree hash c579e63d3ffd0d55171eeeef7fbee9254e184419ebdfbb1bddc4807310069330
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.eprint lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import FeatureMap, KnowledgeRef

__all__ = [
    "DataLink",
    "Eprint",
    "ReproducibilityInfo",
]


class ReproducibilityInfo(dx.Model):
    """Information about how to reproduce the data from the eprint."""

    codeUri: str | None = dx.field(
        default=None,
        description="URI of the code repository.",
        extras={"format": "uri", "maxLength": 2048},
    )
    command: str | None = dx.field(
        default=None,
        description="Command to reproduce the data.",
        extras={"maxLength": 4096},
    )
    commitHash: str | None = dx.field(
        default=None,
        description="Git commit hash for reproducibility.",
        extras={"maxLength": 64},
    )
    environment: str | None = dx.field(
        default=None,
        description="Environment specification (Docker image, conda env, etc.).",
        extras={"maxLength": 2048},
    )
    randomSeed: int | None = dx.field(
        default=None,
        description="Random seed used.",
    )


class DataLink(dx.Model):
    """A link from an eprint to the Layers data it produced or is associated with. Generalizes the former chive-specific eprintDataLink."""  # noqa: E501

    annotationRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to specific annotation records.",
    )
    corpusRef: str | None = dx.field(
        default=None,
        description="Reference to a Layers corpus.",
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    dataKind: str = dx.field(
        description="Data kind slug (fallback when dataKindUri unavailable).",
        extras={
            "knownValues": (
                "corpus",
                "annotation-layer",
                "model-output",
                "gold-standard",
                "evaluation-data",
                "supplementary",
                "replication",
            ),
            "maxLength": 128,
        },
    )
    dataKindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the data kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    description: str | None = dx.field(
        default=None,
        extras={"maxLength": 10000},
    )
    eprintDid: str | None = dx.field(
        default=None,
        description="DID of the eprint author/owner on the publication platform.",
        extras={"format": "did"},
    )
    eprintUri: str = dx.field(
        description="AT-URI of the eprint on its publication platform.",
        extras={"format": "at-uri"},
    )
    expressionRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to specific Layers expressions.",
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    paperSection: str | None = dx.field(
        default=None,
        description="Which section of the paper this data corresponds to (e.g., 'Section 4.2', 'Table 3', 'Appendix A').",  # noqa: E501
        extras={"maxLength": 256},
    )
    reproducibility: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
    )


class Eprint(dx.Model):
    """A link between a Layers data record and an eprint."""

    annotationRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to specific annotation records linked to this eprint.",
    )
    citation: str | None = dx.field(
        default=None,
        description="Full citation string.",
        extras={"maxLength": 4096},
    )
    corpusRef: str | None = dx.field(
        default=None,
        description="Reference to a corpus record.",
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    description: str | None = dx.field(
        default=None,
        description="Description of the relationship.",
        extras={"maxLength": 10000},
    )
    eprintIdentifier: str = dx.field(
        description="The eprint identifier (DOI, arXiv ID, ACL Anthology ID, etc.).",
        extras={"maxLength": 512},
    )
    eprintIdentifierType: str | None = dx.field(
        default=None,
        description="Identifier type slug (fallback when eprintIdentifierTypeUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "doi",
                "arxiv",
                "acl-anthology",
                "semantic-scholar",
                "pubmed",
                "isbn",
                "url",
                "at-uri",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    eprintIdentifierTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the identifier type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    eprintUri: str | None = dx.field(
        default=None,
        description="Full URI of the eprint.",
        extras={"format": "uri"},
    )
    expressionRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to Layers expressions linked to this eprint.",
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references (e.g., Wikidata for the venue, DBLP, Semantic Scholar corpus ID).",  # noqa: E501
    )
    linkType: str = dx.field(
        description="Link type slug (fallback when linkTypeUri unavailable).",
        extras={
            "knownValues": (
                "produced-by",
                "described-in",
                "evaluated-in",
                "replicated-from",
                "extends",
                "supplements",
                "cited-in",
                "annotates",
                "training-data-for",
                "test-data-for",
            ),
            "maxLength": 128,
        },
    )
    linkTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the link type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    platformEprintRef: str | None = dx.field(
        default=None,
        description="AT-URI of the eprint record on its publication platform (e.g., chive.pub, any ATProto-native publication service).",  # noqa: E501
        extras={"format": "at-uri"},
    )
