# generated by lairs gen; do not edit
# lexicon tree hash cedfb9f34cc55fb5be1abb81dda63fd6a6671af2efd6a5e5923fca0c77ba0fd1
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.eprint lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AgentRef,
    FeatureMap,
    KnowledgeRef,
    ReproducibilityInfo,
)

__all__ = [
    "Citation",
    "Creator",
    "DataLink",
    "Date",
    "Eprint",
]


class Creator(dx.Model):
    """A bibliographic creator (author, editor, etc.). Name parts follow CSL-JSON; nameType and affiliation follow DataCite. ATProto-native creators additionally ground identity via agent (DID) or knowledgeRef (ORCID, ROR, OpenAlex)."""  # noqa: E501

    affiliation: str | None = dx.field(
        default=None,
        description="Affiliation (DataCite affiliation).",
        extras={"maxLength": 1024},
    )
    agent: dx.Embed[AgentRef] | None = dx.field(
        default=None,
        description="ATProto-native identity grounding (DID) for the creator, if any.",
    )
    droppingParticle: str | None = dx.field(
        default=None,
        description="Dropping particle (CSL 'dropping-particle').",
        extras={"maxLength": 128},
    )
    family: str | None = dx.field(
        default=None,
        description="Family/surname (CSL 'family').",
        extras={"maxLength": 512},
    )
    given: str | None = dx.field(
        default=None,
        description="Given name(s) (CSL 'given').",
        extras={"maxLength": 512},
    )
    knowledgeRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="External identity grounding (ORCID via source 'orcid', ROR for organizations, OpenAlex author id).",  # noqa: E501
    )
    literal: str | None = dx.field(
        default=None,
        description="Full name as a single string when parts are not separated, or an organization name (CSL 'literal').",  # noqa: E501
        extras={"maxLength": 1024},
    )
    nameType: str | None = dx.field(
        default=None,
        description="Whether the creator is a person or an organization (DataCite nameType; fallback when nameTypeUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "personal",
                "organizational",
            ),
            "maxLength": 64,
        },
    )
    nameTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the name-type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    nonDroppingParticle: str | None = dx.field(
        default=None,
        description="Non-dropping particle (CSL 'non-dropping-particle').",
        extras={"maxLength": 128},
    )
    role: str | None = dx.field(
        default=None,
        description="Creator role slug (CSL contributor role / DataCite contributorType; fallback when roleUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "author",
                "editor",
                "translator",
                "contributor",
                "illustrator",
                "director",
                "producer",
                "collector",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    roleUri: str | None = dx.field(
        default=None,
        description="AT-URI of the creator-role definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    sequence: int | None = dx.field(
        default=None,
        description="Position of this creator in the creator list (1-based).",
        extras={"minimum": 1},
    )
    suffix: str | None = dx.field(
        default=None,
        description="Name suffix (CSL 'suffix', e.g., 'Jr.', 'III').",
        extras={"maxLength": 128},
    )


class Date(dx.Model):
    """A date in CSL-JSON style: structured year/month/day and/or a free-form literal. Maps to CSL 'date-parts' (when year/month/day are set) or 'literal'/'raw' (when only literal is set)."""  # noqa: E501

    circa: bool | None = dx.field(
        default=None,
        description="Whether the date is approximate (CSL 'circa').",
    )
    day: int | None = dx.field(
        default=None,
        description="Day of month (1-31).",
        extras={"minimum": 1, "maximum": 31},
    )
    literal: str | None = dx.field(
        default=None,
        description="Free-form date string when structured parts are unavailable (CSL 'literal'/'raw').",  # noqa: E501
        extras={"maxLength": 128},
    )
    month: int | None = dx.field(
        default=None,
        description="Month (1-12).",
        extras={"minimum": 1, "maximum": 12},
    )
    season: str | None = dx.field(
        default=None,
        description="Season when the work was issued (CSL 'season').",
        extras={"maxLength": 32},
    )
    year: int | None = dx.field(
        default=None,
        description="Four-digit year.",
    )


class Citation(dx.Model):
    """A bibliographic citation, expressible as a raw formatted string (raw) and/or structured fields following CSL-JSON and DataCite conventions. Consumers prefer the structured fields when present and fall back to raw. Populate at least raw or title."""  # noqa: E501

    abstract: str | None = dx.field(
        default=None,
        description="Abstract (CSL 'abstract'; DataCite Abstract description).",
        extras={"maxLength": 20000},
    )
    accessed: dx.Embed[Date] | None = dx.field(
        default=None,
        description="Date the work was accessed (CSL 'accessed').",
    )
    containerTitle: str | None = dx.field(
        default=None,
        description="Title of the container: journal, book, or proceedings (CSL 'container-title').",  # noqa: E501
        extras={"maxLength": 2048},
    )
    creators: tuple[dx.Embed[Creator], ...] | None = dx.field(
        default_factory=tuple,
        description="Authors, editors, and other creators (CSL name variables; DataCite creators).",  # noqa: E501
    )
    doi: str | None = dx.field(
        default=None,
        description="DOI (CSL 'DOI'), e.g., '10.18653/v1/2020.acl-main.1'.",
        extras={"maxLength": 256},
    )
    edition: str | None = dx.field(
        default=None,
        extras={"maxLength": 64},
    )
    isbn: str | None = dx.field(
        default=None,
        extras={"maxLength": 32},
    )
    issn: str | None = dx.field(
        default=None,
        extras={"maxLength": 32},
    )
    issue: str | None = dx.field(
        default=None,
        extras={"maxLength": 64},
    )
    issued: dx.Embed[Date] | None = dx.field(
        default=None,
        description="Issue/publication date (CSL 'issued'; DataCite publicationYear).",
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="External grounding for the work or venue (Crossref, OpenAlex, DBLP, Semantic Scholar).",  # noqa: E501
    )
    language: str | None = dx.field(
        default=None,
        description="BCP-47 language tag of the work (CSL 'language').",
        extras={"maxLength": 32},
    )
    page: str | None = dx.field(
        default=None,
        description="Page range (CSL 'page', e.g., '101-126').",
        extras={"maxLength": 64},
    )
    pmid: str | None = dx.field(
        default=None,
        description="PubMed ID (CSL 'PMID').",
        extras={"maxLength": 32},
    )
    publisher: str | None = dx.field(
        default=None,
        description="Publisher (CSL 'publisher'; DataCite publisher).",
        extras={"maxLength": 1024},
    )
    publisherPlace: str | None = dx.field(
        default=None,
        description="Publisher location (CSL 'publisher-place').",
        extras={"maxLength": 512},
    )
    raw: str | None = dx.field(
        default=None,
        description="Full formatted citation string (CSL fallback). Sufficient on its own when structured metadata is unavailable.",  # noqa: E501
        extras={"maxLength": 4096},
    )
    title: str | None = dx.field(
        default=None,
        description="Title of the work (CSL 'title').",
        extras={"maxLength": 2048},
    )
    type: str | None = dx.field(
        default=None,
        description="CSL-JSON item type slug (fallback when typeUri unavailable).",
        extras={
            "knownValues": (
                "article-journal",
                "paper-conference",
                "article",
                "book",
                "chapter",
                "thesis",
                "report",
                "dataset",
                "software",
                "manuscript",
                "webpage",
                "entry",
                "standard",
                "preprint",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    typeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the bibliographic type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    url: str | None = dx.field(
        default=None,
        description="URL (CSL 'URL').",
        extras={"format": "uri", "maxLength": 2048},
    )
    version: str | None = dx.field(
        default=None,
        description="Version of the cited artifact (CSL 'version'; DataCite version).",
        extras={"maxLength": 64},
    )
    volume: str | None = dx.field(
        default=None,
        extras={"maxLength": 64},
    )


class DataLink(dx.Model):
    """A link from an eprint to the Layers data it produced or is associated with. Generalizes the former chive-specific eprintDataLink."""  # noqa: E501

    annotationRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to specific annotation records.",
    )
    corpusRef: str | None = dx.field(
        default=None,
        description="Reference to a Layers corpus.",
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    dataKind: str = dx.field(
        description="Data kind slug (fallback when dataKindUri unavailable).",
        extras={
            "knownValues": (
                "corpus",
                "annotation-layer",
                "model-output",
                "gold-standard",
                "evaluation-data",
                "supplementary",
                "replication",
            ),
            "maxLength": 128,
        },
    )
    dataKindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the data kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    description: str | None = dx.field(
        default=None,
        extras={"maxLength": 10000},
    )
    eprintDid: str | None = dx.field(
        default=None,
        description="DID of the eprint author/owner on the publication platform.",
        extras={"format": "did"},
    )
    eprintUri: str = dx.field(
        description="AT-URI of the eprint on its publication platform.",
        extras={"format": "at-uri"},
    )
    expressionRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to specific Layers expressions.",
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    paperSection: str | None = dx.field(
        default=None,
        description="Which section of the paper this data corresponds to (e.g., 'Section 4.2', 'Table 3', 'Appendix A').",  # noqa: E501
        extras={"maxLength": 256},
    )
    reproducibility: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
    )


class Eprint(dx.Model):
    """A link between a Layers data record and an eprint."""

    annotationRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to specific annotation records linked to this eprint.",
    )
    citation: dx.Embed[Citation] | None = dx.field(
        default=None,
        description="Bibliographic citation for the eprint. Carries rendered metadata (authors, title, venue, year) as a raw string and/or structured CSL-JSON/DataCite fields; eprintIdentifier/eprintIdentifierType remain the canonical link key.",  # noqa: E501
    )
    corpusRef: str | None = dx.field(
        default=None,
        description="Reference to a corpus record.",
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    description: str | None = dx.field(
        default=None,
        description="Description of the relationship.",
        extras={"maxLength": 10000},
    )
    eprintIdentifier: str = dx.field(
        description="The eprint identifier (DOI, arXiv ID, ACL Anthology ID, etc.).",
        extras={"maxLength": 512},
    )
    eprintIdentifierType: str | None = dx.field(
        default=None,
        description="Identifier type slug (fallback when eprintIdentifierTypeUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "doi",
                "arxiv",
                "acl-anthology",
                "semantic-scholar",
                "pubmed",
                "isbn",
                "url",
                "at-uri",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    eprintIdentifierTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the identifier type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    eprintUri: str | None = dx.field(
        default=None,
        description="Full URI of the eprint.",
        extras={"format": "uri"},
    )
    expressionRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to Layers expressions linked to this eprint.",
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references (e.g., Wikidata for the venue, DBLP, Semantic Scholar corpus ID).",  # noqa: E501
    )
    linkType: str = dx.field(
        description="Link type slug (fallback when linkTypeUri unavailable).",
        extras={
            "knownValues": (
                "produced-by",
                "described-in",
                "evaluated-in",
                "replicated-from",
                "extends",
                "supplements",
                "cited-in",
                "annotates",
                "training-data-for",
                "test-data-for",
            ),
            "maxLength": 128,
        },
    )
    linkTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the link type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    platformEprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of the eprint record on its publication platforms (e.g., chive.pub, any ATProto-native publication service). An eprint may be mirrored on multiple platforms.",  # noqa: E501
    )
