# generated by lairs gen; do not edit
# lexicon tree hash c579e63d3ffd0d55171eeeef7fbee9254e184419ebdfbb1bddc4807310069330
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.expression lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    Anchor,
    AnnotationMetadata,
    FeatureMap,
    KnowledgeRef,
)
from lairs.records.blobref import BlobRef

__all__ = [
    "Expression",
]


class Expression(dx.Model):
    """An expression record representing a linguistic data source or unit at any granularity, from full documents down to individual morphemes."""  # noqa: E501

    anchor: dx.Embed[Anchor] | None = dx.field(
        default=None,
        description="How this expression attaches to its parent (character span, temporal span, etc.).",  # noqa: E501
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    eprintRef: str | None = dx.field(
        default=None,
        description="Reference to an eprint record that this expression is associated with.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Arbitrary document-level features and metadata.",
    )
    id: str = dx.field(
        description="A corpus-level unique identifier (headline, URL, document ID, etc.).",  # noqa: E501
        extras={"maxLength": 1024},
    )
    kind: str = dx.field(
        description="Expression kind slug (fallback when kindUri unavailable).",
        extras={
            "knownValues": (
                "document",
                "transcript",
                "dialogue",
                "social-media",
                "email",
                "article",
                "recording",
                "video",
                "multimodal",
                "code",
                "section",
                "paragraph",
                "chapter",
                "turn",
                "utterance",
                "heading",
                "list",
                "sentence",
                "clause",
                "phrase",
                "word",
                "morpheme",
                "character",
                "other",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the expression kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="References to knowledge base entries relevant to this expression.",
    )
    language: str | None = dx.field(
        default=None,
        description="BCP-47 language tag for the primary language.",
        extras={"maxLength": 32},
    )
    languages: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Additional BCP-47 tags for multilingual or code-switching expressions.",  # noqa: E501
    )
    mediaBlob: BlobRef | None = dx.field(
        default=None,
        description="Optional inline media blob.",
    )
    mediaRef: str | None = dx.field(
        default=None,
        description="Reference to an associated media record (audio, video, image).",
        extras={"format": "at-uri"},
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
    parentRef: str | None = dx.field(
        default=None,
        description="Reference to the parent Expression this one is nested within. Absent for top-level expressions (documents, recordings, etc.).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    sourceRef: str | None = dx.field(
        default=None,
        description="AT-URI of an external ATProto record this expression is derived from or annotates (e.g., a standard.site Leaflet post, a com.whtwnd blog entry, an app.bsky.feed.post, an at.margin.bookmark).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    sourceUrl: str | None = dx.field(
        default=None,
        description="URL of the external web resource this expression was derived from or annotates. The appview indexes this field to discover co-located annotations from other ATProto apps.",  # noqa: E501
        extras={"format": "uri", "maxLength": 4096},
    )
    text: str | None = dx.field(
        default=None,
        description="The full raw text of the expression. All byte-offset spans reference this string.",  # noqa: E501
        extras={"maxLength": 10000000},
    )
