# generated by lairs gen; do not edit
# lexicon tree hash cedfb9f34cc55fb5be1abb81dda63fd6a6671af2efd6a5e5923fca0c77ba0fd1
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.graph lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AnnotationMetadata,
    FeatureMap,
    KnowledgeRef,
    Licensing,
    ObjectRef,
    ReproducibilityInfo,
    Uuid,
)

__all__ = [
    "GraphEdge",
    "GraphEdgeEntry",
    "GraphEdgeSet",
    "GraphNode",
]


class GraphEdge(dx.Model):
    """A single directed typed edge between any two Layers objects. Supports multidigraphs and cycles. Source and target use objectRef, which can point to local UUIDs, remote AT-URIs, or external knowledge graph nodes."""  # noqa: E501

    confidence: int | None = dx.field(
        default=None,
        description="Confidence 0-1000.",
        extras={"minimum": 0, "maximum": 1000},
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    edgeType: str = dx.field(
        description="Edge type slug (fallback when edgeTypeUri unavailable).",
        extras={
            "knownValues": (
                "reply-to",
                "quote",
                "repost",
                "translation-of",
                "continuation",
                "summary-of",
                "revision-of",
                "correction-of",
                "coreference",
                "causal",
                "part-of",
                "member-of",
                "type-of",
                "same-as",
                "related-to",
                "derived-from",
                "supports",
                "contradicts",
                "discourse",
                "bridging",
                "grounding",
                "instance-of",
                "denotes",
                "describes",
                "specializes",
                "elaborates",
                "produced-by",
                "described-in",
                "annotates",
                "see-also",
                "before",
                "after",
                "meets",
                "met-by",
                "overlaps",
                "overlapped-by",
                "starts",
                "started-by",
                "during",
                "contains",
                "finishes",
                "finished-by",
                "equals",
                "simultaneous",
                "initiates",
                "culminates",
                "terminates",
                "continues",
                "reinitiates",
                "disconnected",
                "externally-connected",
                "partially-overlapping",
                "tangential-proper-part",
                "non-tangential-proper-part",
                "tangential-proper-part-inverse",
                "non-tangential-proper-part-inverse",
                "spatially-equal",
                "north-of",
                "south-of",
                "east-of",
                "west-of",
                "above",
                "below",
                "in-front-of",
                "behind",
                "left-of",
                "right-of",
                "near",
                "far",
                "adjacent",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    edgeTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the edge type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    label: str | None = dx.field(
        default=None,
        description="Optional edge label.",
        extras={"maxLength": 512},
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
    ordinal: int | None = dx.field(
        default=None,
        description="Optional ordering among edges of the same type.",
        extras={"minimum": 0},
    )
    properties: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Edge properties as key-value pairs.",
    )
    source: dx.Embed[ObjectRef] = dx.field(
        description="Source node: use localId for same-record UUID, recordRef for cross-record AT-URI, knowledgeRef for external KG.",  # noqa: E501
    )
    target: dx.Embed[ObjectRef] = dx.field(
        description="Target node: use localId for same-record UUID, recordRef for cross-record AT-URI, knowledgeRef for external KG.",  # noqa: E501
    )


class GraphEdgeEntry(dx.Model):
    """A single directed edge entry within a graphEdgeSet."""

    confidence: int | None = dx.field(
        default=None,
        extras={"minimum": 0, "maximum": 1000},
    )
    edgeType: str = dx.field(
        description="Edge type slug. Overrides the set-level edgeType if different.",
        extras={"maxLength": 256},
    )
    edgeTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the edge type definition node. Overrides the set-level edgeType.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    source: dx.Embed[ObjectRef] = dx.field(
        description="Source node.",
    )
    target: dx.Embed[ObjectRef] = dx.field(
        description="Target node.",
    )
    uuid: dx.Embed[Uuid] = dx.field(
        description="generated field",
    )


class GraphEdgeSet(dx.Model):
    """A batch of typed, directed edges between Layers objects. Use for bulk edge creation when many edges share the same provenance and context."""  # noqa: E501

    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    edgeType: str | None = dx.field(
        default=None,
        description="Edge type slug shared by all edges in this set (fallback when edgeTypeUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "coreference",
                "causal",
                "part-of",
                "member-of",
                "type-of",
                "same-as",
                "related-to",
                "derived-from",
                "supports",
                "contradicts",
                "discourse",
                "bridging",
                "before",
                "after",
                "meets",
                "met-by",
                "overlaps",
                "overlapped-by",
                "starts",
                "started-by",
                "during",
                "contains",
                "finishes",
                "finished-by",
                "equals",
                "simultaneous",
                "initiates",
                "culminates",
                "terminates",
                "continues",
                "reinitiates",
                "disconnected",
                "externally-connected",
                "partially-overlapping",
                "tangential-proper-part",
                "non-tangential-proper-part",
                "tangential-proper-part-inverse",
                "non-tangential-proper-part-inverse",
                "spatially-equal",
                "north-of",
                "south-of",
                "east-of",
                "west-of",
                "above",
                "below",
                "in-front-of",
                "behind",
                "left-of",
                "right-of",
                "near",
                "far",
                "adjacent",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    edgeTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the edge type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    edges: tuple[dx.Embed[GraphEdgeEntry], ...] = dx.field(
        description="generated field",
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Eprint records (papers/preprints) describing or associated with this edge set.",  # noqa: E501
    )
    expression: str | None = dx.field(
        default=None,
        description="Optional primary expression context.",
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features (e.g., extraction method, model version, confidence threshold).",  # noqa: E501
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references for this edge set (e.g., the relation ontology it implements, source methodology).",  # noqa: E501
    )
    licensing: dx.Embed[Licensing] | None = dx.field(
        default=None,
        description="Licensing terms governing this edge set (supports dual/multi/component licensing).",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
    reproducibility: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
        description="How this edge set was produced (code, commit, command, environment, seed).",  # noqa: E501
    )


class GraphNode(dx.Model):
    """A standalone node in the property graph. Represents entities, concepts, situations, claims, or any domain object that does not have another Layers record. Existing Layers records (expressions, annotations, typeDefs) are implicitly nodes via objectRef."""  # noqa: E501

    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references grounding this node (Wikidata, chive.pub, FrameNet, etc.).",  # noqa: E501
    )
    label: str | None = dx.field(
        default=None,
        description="Human-readable node label.",
        extras={"maxLength": 1024},
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
    nodeType: str = dx.field(
        description="Node type slug (fallback when nodeTypeUri unavailable).",
        extras={
            "knownValues": (
                "entity",
                "concept",
                "situation",
                "state",
                "time",
                "location",
                "claim",
                "proposition",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    nodeTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the node type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    properties: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Node properties as key-value pairs.",
    )
