# generated by lairs gen; do not edit
# lexicon tree hash 1d20dc0bf4cfe7daa2b7aa022fdbdd1a8d405ff126cfcc078277f090f7364067
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.judgment lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AgentRef,
    AnnotationMetadata,
    Constraint,
    FeatureMap,
    KnowledgeRef,
    LanguageRef,
    Licensing,
    ObjectRef,
    ReproducibilityInfo,
    Span,
)

__all__ = [
    "AgreementReport",
    "ExperimentDef",
    "ExperimentDesign",
    "Judgment",
    "JudgmentSet",
    "ListConstraint",
    "PresentationSpec",
    "RecordingMethod",
    "RegionResponse",
]


class AgreementReport(dx.Model):
    """An inter-annotator agreement report summarizing agreement metrics across judgment sets."""  # noqa: E501

    createdAt: datetime = dx.field(
        description="When this agreement report record was created.",
        extras={"format": "datetime"},
    )
    experimentRef: str = dx.field(
        description="AT-URI of the pub.layers.judgment.experimentDef this report summarizes agreement for.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features carrying agreement-report detail not covered by the typed fields.",  # noqa: E501
    )
    judgmentSetRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="The judgment sets compared.",
    )
    metric: str | None = dx.field(
        default=None,
        description="Metric slug (fallback when metricUri unavailable).",
        extras={
            "knownValues": (
                "cohens-kappa",
                "fleiss-kappa",
                "krippendorff-alpha",
                "percent-agreement",
                "correlation",
                "f1",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    metricUri: str | None = dx.field(
        default=None,
        description="AT-URI of the metric definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    numAnnotators: int | None = dx.field(
        default=None,
        description="Number of annotators whose judgment sets entered this agreement computation.",  # noqa: E501
        extras={"minimum": 1},
    )
    numItems: int | None = dx.field(
        default=None,
        description="Number of items over which agreement was computed.",
        extras={"minimum": 1},
    )
    value: int | None = dx.field(
        default=None,
        description="Metric value scaled 0-1000.",
        extras={"minimum": 0, "maximum": 1000},
    )


class ListConstraint(dx.Model):
    """A constraint on item list construction for an experiment."""

    constraint: dx.Embed[Constraint] | None = dx.field(
        default=None,
        description="Optional formal constraint expression.",
    )
    kind: str = dx.field(
        description="Constraint kind slug.",
        extras={
            "knownValues": (
                "latin-square",
                "no-adjacent-same-condition",
                "balanced-frequency",
                "minimum-distance",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the constraint kind definition node. Community-expandable.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    parameters: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Constraint parameters (e.g., minimum distance, number of lists).",
    )
    targetProperty: str | None = dx.field(
        default=None,
        description="The item property this constraint operates on (e.g., 'condition', 'templateRef').",  # noqa: E501
        extras={"maxLength": 256},
    )


class ExperimentDesign(dx.Model):
    """Experiment design parameters for item distribution, ordering, and timing."""

    distributionStrategy: str | None = dx.field(
        default=None,
        description="How items are distributed to annotators.",
        extras={
            "knownValues": (
                "latin-square",
                "random",
                "blocked",
                "stratified",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    distributionStrategyUri: str | None = dx.field(
        default=None,
        description="AT-URI of the distribution strategy definition node. Community-expandable.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features carrying experiment-design detail not covered by the typed fields.",  # noqa: E501
    )
    itemOrder: str | None = dx.field(
        default=None,
        description="How items are ordered within a list.",
        extras={
            "knownValues": (
                "random-order",
                "fixed-order",
                "blocked",
                "adaptive",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    itemOrderUri: str | None = dx.field(
        default=None,
        description="AT-URI of the item order definition node. Community-expandable.",
        extras={"format": "at-uri"},
    )
    listConstraints: tuple[dx.Embed[ListConstraint], ...] | None = dx.field(
        default_factory=tuple,
        description="Constraints on item list construction (Latin square balancing, no-adjacent-same-condition, etc.).",  # noqa: E501
    )
    timingMs: int | None = dx.field(
        default=None,
        description="Target timing per item in milliseconds.",
        extras={"minimum": 0},
    )


class PresentationSpec(dx.Model):
    """How stimuli are displayed to participants."""

    chunkingUnit: str | None = dx.field(
        default=None,
        description="How text is segmented for incremental presentation (fallback when chunkingUnitUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "word",
                "character",
                "morpheme",
                "phrase",
                "clause",
                "sentence",
                "region",
                "sign",
                "gesture-phrase",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    chunkingUnitUri: str | None = dx.field(
        default=None,
        description="AT-URI of the chunking unit definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    cumulative: bool | None = dx.field(
        default=None,
        description="Whether previous chunks remain visible during incremental presentation.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features carrying presentation detail not covered by the typed fields.",  # noqa: E501
    )
    isiMs: int | None = dx.field(
        default=None,
        description="Inter-stimulus interval in milliseconds.",
        extras={"minimum": 0},
    )
    maskChar: str | None = dx.field(
        default=None,
        description="Masking character for non-cumulative displays (e.g., '-', '#').",
        extras={"maxLength": 8},
    )
    mediaRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of pub.layers.media.media records delivered as stimuli under this specification.",  # noqa: E501
    )
    method: str | None = dx.field(
        default=None,
        description="Presentation method (fallback when methodUri unavailable).",
        extras={
            "knownValues": (
                "rsvp",
                "self-paced",
                "whole-sentence",
                "auditory",
                "visual-world",
                "masked-priming",
                "cross-modal",
                "naturalistic",
                "gating",
                "maze",
                "boundary",
                "moving-window",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    methodUri: str | None = dx.field(
        default=None,
        description="AT-URI of the presentation method definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    participantRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of pub.layers.acquisition.participant records presented under this specification.",  # noqa: E501
    )
    pixelsPerDegree: int | None = dx.field(
        default=None,
        description="Pixels subtending one degree of visual angle at the stated viewing distance.",  # noqa: E501
        extras={"minimum": 0},
    )
    refreshRateMilliHz: int | None = dx.field(
        default=None,
        description="Display refresh rate in millihertz (e.g., 60000 for 60 Hz).",
        extras={"minimum": 0},
    )
    screenHeightMm: int | None = dx.field(
        default=None,
        description="Physical display height in millimeters.",
        extras={"minimum": 0},
    )
    screenHeightPx: int | None = dx.field(
        default=None,
        description="Display height in pixels.",
        extras={"minimum": 0},
    )
    screenWidthMm: int | None = dx.field(
        default=None,
        description="Physical display width in millimeters.",
        extras={"minimum": 0},
    )
    screenWidthPx: int | None = dx.field(
        default=None,
        description="Display width in pixels.",
        extras={"minimum": 0},
    )
    sessionRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.acquisition.session whose clock and setup this presentation was delivered under.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    timingMs: int | None = dx.field(
        default=None,
        description="Per-chunk display duration in milliseconds.",
        extras={"minimum": 0},
    )
    viewingDistanceMm: int | None = dx.field(
        default=None,
        description="Participant eye-to-screen distance in millimeters.",
        extras={"minimum": 0},
    )


class RecordingMethod(dx.Model):
    """A data capture instrument used in an experiment."""

    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features carrying recording-method detail not covered by the typed fields.",  # noqa: E501
    )
    mediaRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of pub.layers.media.media records produced by this recording instrument.",  # noqa: E501
    )
    method: str = dx.field(
        description="Recording method (fallback when methodUri unavailable).",
        extras={
            "knownValues": (
                "button-box",
                "keyboard",
                "mouse-click",
                "touchscreen",
                "voice",
                "eeg",
                "meg",
                "fmri",
                "fnirs",
                "eye-tracking",
                "pupillometry",
                "mouse-tracking",
                "emg",
                "skin-conductance",
                "ecog",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    methodUri: str | None = dx.field(
        default=None,
        description="AT-URI of the recording method definition node. Resolves into the shared modality node set in layers-acquisition.ontology.layers.pub (the same nodes backing media signalInfo.modalityUri and catalog contentSummary.modalityUri). Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    participantRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of pub.layers.acquisition.participant records this recording captured.",  # noqa: E501
    )
    sessionRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.acquisition.session whose clock this recording was captured on.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class ExperimentDef(dx.Model):
    """Definition of an annotation or judgment experiment."""

    collectionRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to pub.layers.resource#collection records providing filler pools for this experiment.",  # noqa: E501
    )
    corpusRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.corpus.corpus whose items this experiment draws stimuli from.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        description="When this experiment definition record was created.",
        extras={"format": "datetime"},
    )
    description: str | None = dx.field(
        default=None,
        description="Free-text description of this experiment and its purpose.",
        extras={"maxLength": 50000},
    )
    design: dx.Embed[ExperimentDesign] | None = dx.field(
        default=None,
        description="Experiment design parameters: list constraints, distribution strategy, item order.",  # noqa: E501
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Eprint records (papers/preprints) describing or associated with this experiment.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features carrying experiment detail not covered by the typed fields.",  # noqa: E501
    )
    guidelines: str | None = dx.field(
        default=None,
        description="Instructions or guidelines text shown to participants.",
        extras={"maxLength": 100000},
    )
    guidelinesFormat: str | None = dx.field(
        default=None,
        description="Format of the guidelines text, so consumers can render it safely without sniffing. Defaults to plain when omitted.",  # noqa: E501
        extras={
            "knownValues": (
                "plain",
                "html",
                "markdown",
            ),
            "maxLength": 32,
        },
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references (e.g., theoretical framework, methodology citation, task ontology).",  # noqa: E501
    )
    labels: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Available labels for categorical judgments.",
    )
    languageRefs: tuple[dx.Embed[LanguageRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Grounded language references for the stimuli, carrying canonical BCP-47 tag, script/region codes, variety label, and a knowledge-graph source (glottolog, iso639-3, cldr). Richer than the languages slug array; use both.",  # noqa: E501
    )
    languages: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="BCP-47 language tags of the stimuli in this experiment. Empty when language is unspecified or unknown.",  # noqa: E501
    )
    licensing: dx.Embed[Licensing] | None = dx.field(
        default=None,
        description="Licensing terms governing this experiment definition (supports dual/multi/component licensing).",  # noqa: E501
    )
    measureType: str | None = dx.field(
        default=None,
        description="What property or behavior is being measured (fallback when measureTypeUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "acceptability",
                "inference",
                "similarity",
                "plausibility",
                "comprehension",
                "preference",
                "extraction",
                "reading-time",
                "production",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    measureTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the measure type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    name: str = dx.field(
        description="Human-readable name of this experiment.",
        extras={"maxLength": 512},
    )
    ontologyRef: str | None = dx.field(
        default=None,
        description="AT-URI of the ontology record supplying the label or category vocabulary this experiment collects responses over.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    personaRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.persona.persona defining the interpretive framework annotators adopt for this experiment.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    presentation: dx.Embed[PresentationSpec] | None = dx.field(
        default=None,
        description="How stimuli are displayed to participants.",
    )
    recordingMethods: tuple[dx.Embed[RecordingMethod], ...] | None = dx.field(
        default_factory=tuple,
        description="Data capture instruments used in this experiment.",
    )
    reproducibility: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
        description="How this experiment dataset was produced (code, commit, command, environment, seed).",  # noqa: E501
    )
    scaleMax: int | None = dx.field(
        default=None,
        description="Maximum scale value.",
    )
    scaleMin: int | None = dx.field(
        default=None,
        description="Minimum scale value for ordinal-scale judgments.",
    )
    stimulusExpressionRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to pub.layers.expression.expression records used as stimuli in this experiment (text stimuli).",  # noqa: E501
    )
    stimulusMediaRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to pub.layers.media.media records used as stimuli in this experiment (audio, video, image, signal, and other carrier stimuli).",  # noqa: E501
    )
    taskType: str | None = dx.field(
        default=None,
        description="Response instrument: how the response is collected (fallback when taskTypeUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "forced-choice",
                "multi-select",
                "ordinal-scale",
                "magnitude",
                "binary",
                "categorical",
                "free-text",
                "cloze",
                "span-labeling",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    taskTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the response instrument definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    templateRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to pub.layers.resource#template records used to generate stimuli for this experiment.",  # noqa: E501
    )


class RegionResponse(dx.Model):
    """A per-region reading-time or response measurement within a judgment, addressing one region of the presented stimulus (e.g., in self-paced reading or eye-tracking region analysis)."""  # noqa: E501

    categoricalValue: str | None = dx.field(
        default=None,
        description="Categorical per-region response label.",
        extras={"maxLength": 512},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open key-value map for per-region measures not covered by the named fields.",  # noqa: E501
    )
    firstFixationMs: int | None = dx.field(
        default=None,
        description="First-fixation duration on this region in milliseconds.",
        extras={"minimum": 0},
    )
    fixationCount: int | None = dx.field(
        default=None,
        description="Number of fixations on this region.",
        extras={"minimum": 0},
    )
    gazeDurationMs: int | None = dx.field(
        default=None,
        description="Gaze (first-pass) duration on this region in milliseconds.",
        extras={"minimum": 0},
    )
    goPastMs: int | None = dx.field(
        default=None,
        description="Go-past (regression-path) duration on this region in milliseconds.",  # noqa: E501
        extras={"minimum": 0},
    )
    readingTimeMs: int | None = dx.field(
        default=None,
        description="Total reading time on this region in milliseconds.",
        extras={"minimum": 0},
    )
    region: dx.Embed[ObjectRef] = dx.field(
        description="Reference to the region being measured. Use recordRef for the stimulus record, objectId for a specific region object within it, localId for same-record references.",  # noqa: E501
    )
    regionIndex: int | None = dx.field(
        default=None,
        description="Zero-indexed position of this region within the stimulus presentation order.",  # noqa: E501
        extras={"minimum": 0},
    )
    regionRole: str | None = dx.field(
        default=None,
        description="Analysis role of this region (fallback when regionRoleUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "critical",
                "spillover",
                "precritical",
                "pretarget",
                "target",
                "posttarget",
                "filler",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    regionRoleUri: str | None = dx.field(
        default=None,
        description="AT-URI of the region role definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    regressionsIn: int | None = dx.field(
        default=None,
        description="Count of regressions landing in this region.",
        extras={"minimum": 0},
    )
    regressionsOut: int | None = dx.field(
        default=None,
        description="Count of regressions launched out of this region.",
        extras={"minimum": 0},
    )
    responseTimeMs: int | None = dx.field(
        default=None,
        description="Response time in milliseconds for a per-region response task (e.g., maze, grammaticality-at-region).",  # noqa: E501
        extras={"minimum": 0},
    )
    scalarValue: int | None = dx.field(
        default=None,
        description="Numeric per-region response value (e.g., rating at this region).",
    )
    totalTimeMs: int | None = dx.field(
        default=None,
        description="Total dwell time across all fixations on this region in milliseconds.",  # noqa: E501
        extras={"minimum": 0},
    )


class Judgment(dx.Model):
    """A single judgment about a linguistic item."""

    behavioralData: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Behavioral signals: mouse movements, keystroke patterns, eye tracking data, scroll events, etc.",  # noqa: E501
    )
    categoricalValue: str | None = dx.field(
        default=None,
        description="Categorical judgment label.",
        extras={"maxLength": 512},
    )
    confidence: int | None = dx.field(
        default=None,
        description="Annotator's stated confidence in this judgment, scaled 0-1000.",
        extras={"minimum": 0, "maximum": 1000},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features carrying judgment detail not covered by the typed fields.",  # noqa: E501
    )
    fillingRef: str | None = dx.field(
        default=None,
        description="Reference to the pub.layers.resource#filling that generated the item being judged.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    freeText: str | None = dx.field(
        default=None,
        description="Free-text response.",
        extras={"maxLength": 10000},
    )
    item: dx.Embed[ObjectRef] = dx.field(
        description="Reference to the item being judged. Use recordRef for the communication/annotation record, objectId for a specific object within it, localId for same-record references.",  # noqa: E501
    )
    regionResponses: tuple[dx.Embed[RegionResponse], ...] | None = dx.field(
        default_factory=tuple,
        description="Per-region reading-time or response measurements for this judgment, one per region of the presented stimulus (self-paced reading, eye-tracking region analysis).",  # noqa: E501
    )
    responseTimeMs: int | None = dx.field(
        default=None,
        description="Response time in milliseconds.",
        extras={"minimum": 0},
    )
    scalarValue: int | None = dx.field(
        default=None,
        description="Numeric response value (ordinal-scale rating, magnitude estimate, or rank position).",  # noqa: E501
    )
    textSpan: dx.Embed[Span] | None = dx.field(
        default=None,
        description="Selected text span for span-labeling tasks.",
    )


class JudgmentSet(dx.Model):
    """A set of judgments from a single annotator for an experiment."""

    agent: dx.Embed[AgentRef] | None = dx.field(
        default=None,
        description="The agent (human annotator, ML model, crowd worker, etc.) who produced this judgment set. Use did for ATProto-native annotators, id for anonymized/platform-specific identifiers, knowledgeRef for ORCID or model cards.",  # noqa: E501
    )
    createdAt: datetime = dx.field(
        description="When this judgment set record was created.",
        extras={"format": "datetime"},
    )
    experimentRef: str = dx.field(
        description="AT-URI of the pub.layers.judgment.experimentDef this judgment set was collected for.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features (e.g., annotator demographics, session metadata, completion time, payment info).",  # noqa: E501
    )
    judgments: tuple[dx.Embed[Judgment], ...] = dx.field(
        description="The judgments in this set, each a pub.layers.judgment.defs#judgment, all produced by the one annotator.",  # noqa: E501
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references (e.g., crowdsourcing platform, annotator population, methodology source).",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who created this judgment set record, with what tool.",
    )
