# generated by lairs gen; do not edit
# lexicon tree hash cedfb9f34cc55fb5be1abb81dda63fd6a6671af2efd6a5e5923fca0c77ba0fd1
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.judgment lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AgentRef,
    AnnotationMetadata,
    Constraint,
    FeatureMap,
    KnowledgeRef,
    Licensing,
    ObjectRef,
    ReproducibilityInfo,
    Span,
)

__all__ = [
    "AgreementReport",
    "ExperimentDef",
    "ExperimentDesign",
    "Judgment",
    "JudgmentSet",
    "ListConstraint",
    "PresentationSpec",
    "RecordingMethod",
]


class AgreementReport(dx.Model):
    """An inter-annotator agreement report summarizing agreement metrics across judgment sets."""  # noqa: E501

    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    experimentRef: str = dx.field(
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    judgmentSetRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="The judgment sets compared.",
    )
    metric: str | None = dx.field(
        default=None,
        description="Metric slug (fallback when metricUri unavailable).",
        extras={
            "knownValues": (
                "cohens-kappa",
                "fleiss-kappa",
                "krippendorff-alpha",
                "percent-agreement",
                "correlation",
                "f1",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    metricUri: str | None = dx.field(
        default=None,
        description="AT-URI of the metric definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    numAnnotators: int | None = dx.field(
        default=None,
        extras={"minimum": 1},
    )
    numItems: int | None = dx.field(
        default=None,
        extras={"minimum": 1},
    )
    value: int | None = dx.field(
        default=None,
        description="Metric value scaled 0-1000.",
        extras={"minimum": 0, "maximum": 1000},
    )


class ListConstraint(dx.Model):
    """A constraint on item list construction for an experiment."""

    constraint: dx.Embed[Constraint] | None = dx.field(
        default=None,
        description="Optional formal constraint expression.",
    )
    kind: str = dx.field(
        description="Constraint kind slug.",
        extras={
            "knownValues": (
                "latin-square",
                "no-adjacent-same-condition",
                "balanced-frequency",
                "minimum-distance",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the constraint kind definition node. Community-expandable.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    parameters: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Constraint parameters (e.g., minimum distance, number of lists).",
    )
    targetProperty: str | None = dx.field(
        default=None,
        description="The item property this constraint operates on (e.g., 'condition', 'templateRef').",  # noqa: E501
        extras={"maxLength": 256},
    )


class ExperimentDesign(dx.Model):
    """Experiment design parameters for item distribution, ordering, and timing."""

    distributionStrategy: str | None = dx.field(
        default=None,
        description="How items are distributed to annotators.",
        extras={
            "knownValues": (
                "latin-square",
                "random",
                "blocked",
                "stratified",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    distributionStrategyUri: str | None = dx.field(
        default=None,
        description="AT-URI of the distribution strategy definition node. Community-expandable.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    itemOrder: str | None = dx.field(
        default=None,
        description="How items are ordered within a list.",
        extras={
            "knownValues": (
                "random-order",
                "fixed-order",
                "blocked",
                "adaptive",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    itemOrderUri: str | None = dx.field(
        default=None,
        description="AT-URI of the item order definition node. Community-expandable.",
        extras={"format": "at-uri"},
    )
    listConstraints: tuple[dx.Embed[ListConstraint], ...] | None = dx.field(
        default_factory=tuple,
        description="Constraints on item list construction (Latin square balancing, no-adjacent-same-condition, etc.).",  # noqa: E501
    )
    timingMs: int | None = dx.field(
        default=None,
        description="Target timing per item in milliseconds.",
        extras={"minimum": 0},
    )


class PresentationSpec(dx.Model):
    """How stimuli are displayed to participants."""

    chunkingUnit: str | None = dx.field(
        default=None,
        description="How text is segmented for incremental presentation.",
        extras={
            "knownValues": (
                "word",
                "character",
                "morpheme",
                "phrase",
                "sentence",
                "region",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    cumulative: bool | None = dx.field(
        default=None,
        description="Whether previous chunks remain visible during incremental presentation.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    isiMs: int | None = dx.field(
        default=None,
        description="Inter-stimulus interval in milliseconds.",
        extras={"minimum": 0},
    )
    maskChar: str | None = dx.field(
        default=None,
        description="Masking character for non-cumulative displays (e.g., '-', '#').",
        extras={"maxLength": 8},
    )
    method: str | None = dx.field(
        default=None,
        description="Presentation method (fallback when methodUri unavailable).",
        extras={
            "knownValues": (
                "rsvp",
                "self-paced",
                "whole-sentence",
                "auditory",
                "visual-world",
                "masked-priming",
                "cross-modal",
                "naturalistic",
                "gating",
                "maze",
                "boundary",
                "moving-window",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    methodUri: str | None = dx.field(
        default=None,
        description="AT-URI of the presentation method definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    timingMs: int | None = dx.field(
        default=None,
        description="Per-chunk display duration in milliseconds.",
        extras={"minimum": 0},
    )


class RecordingMethod(dx.Model):
    """A data capture instrument used in an experiment."""

    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    method: str = dx.field(
        description="Recording method (fallback when methodUri unavailable).",
        extras={
            "knownValues": (
                "button-box",
                "keyboard",
                "mouse-click",
                "touchscreen",
                "voice",
                "eeg",
                "meg",
                "fmri",
                "fnirs",
                "eye-tracking",
                "pupillometry",
                "mouse-tracking",
                "emg",
                "skin-conductance",
                "ecog",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    methodUri: str | None = dx.field(
        default=None,
        description="AT-URI of the recording method definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class ExperimentDef(dx.Model):
    """Definition of an annotation or judgment experiment."""

    collectionRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to pub.layers.resource#collection records providing filler pools for this experiment.",  # noqa: E501
    )
    corpusRef: str | None = dx.field(
        default=None,
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    description: str | None = dx.field(
        default=None,
        extras={"maxLength": 50000},
    )
    design: dx.Embed[ExperimentDesign] | None = dx.field(
        default=None,
        description="Experiment design parameters: list constraints, distribution strategy, item order.",  # noqa: E501
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Eprint records (papers/preprints) describing or associated with this experiment.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    guidelines: str | None = dx.field(
        default=None,
        description="Instructions or guidelines text shown to participants.",
        extras={"maxLength": 100000},
    )
    guidelinesFormat: str | None = dx.field(
        default=None,
        description="Format of the guidelines text, so consumers can render it safely without sniffing. Defaults to plain when omitted.",  # noqa: E501
        extras={
            "knownValues": (
                "plain",
                "html",
                "markdown",
            ),
            "maxLength": 32,
        },
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references (e.g., theoretical framework, methodology citation, task ontology).",  # noqa: E501
    )
    labels: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Available labels for categorical judgments.",
    )
    licensing: dx.Embed[Licensing] | None = dx.field(
        default=None,
        description="Licensing terms governing this experiment definition (supports dual/multi/component licensing).",  # noqa: E501
    )
    measureType: str | None = dx.field(
        default=None,
        description="What property or behavior is being measured (fallback when measureTypeUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "acceptability",
                "inference",
                "similarity",
                "plausibility",
                "comprehension",
                "preference",
                "extraction",
                "reading-time",
                "production",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    measureTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the measure type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    name: str = dx.field(
        extras={"maxLength": 512},
    )
    ontologyRef: str | None = dx.field(
        default=None,
        extras={"format": "at-uri"},
    )
    personaRef: str | None = dx.field(
        default=None,
        extras={"format": "at-uri"},
    )
    presentation: dx.Embed[PresentationSpec] | None = dx.field(
        default=None,
        description="How stimuli are displayed to participants.",
    )
    recordingMethods: tuple[dx.Embed[RecordingMethod], ...] | None = dx.field(
        default_factory=tuple,
        description="Data capture instruments used in this experiment.",
    )
    reproducibility: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
        description="How this experiment dataset was produced (code, commit, command, environment, seed).",  # noqa: E501
    )
    scaleMax: int | None = dx.field(
        default=None,
        description="Maximum scale value.",
    )
    scaleMin: int | None = dx.field(
        default=None,
        description="Minimum scale value for ordinal-scale judgments.",
    )
    taskType: str | None = dx.field(
        default=None,
        description="Response instrument: how the response is collected (fallback when taskTypeUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "forced-choice",
                "multi-select",
                "ordinal-scale",
                "magnitude",
                "binary",
                "categorical",
                "free-text",
                "cloze",
                "span-labeling",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    taskTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the response instrument definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    templateRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to pub.layers.resource#template records used to generate stimuli for this experiment.",  # noqa: E501
    )


class Judgment(dx.Model):
    """A single judgment about a linguistic item."""

    behavioralData: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Behavioral signals: mouse movements, keystroke patterns, eye tracking data, scroll events, etc.",  # noqa: E501
    )
    categoricalValue: str | None = dx.field(
        default=None,
        description="Categorical judgment label.",
        extras={"maxLength": 512},
    )
    confidence: int | None = dx.field(
        default=None,
        extras={"minimum": 0, "maximum": 1000},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    fillingRef: str | None = dx.field(
        default=None,
        description="Reference to the pub.layers.resource#filling that generated the item being judged.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    freeText: str | None = dx.field(
        default=None,
        description="Free-text response.",
        extras={"maxLength": 10000},
    )
    item: dx.Embed[ObjectRef] = dx.field(
        description="Reference to the item being judged. Use recordRef for the communication/annotation record, objectId for a specific object within it, localId for same-record references.",  # noqa: E501
    )
    responseTimeMs: int | None = dx.field(
        default=None,
        description="Response time in milliseconds.",
        extras={"minimum": 0},
    )
    scalarValue: int | None = dx.field(
        default=None,
        description="Numeric response value (ordinal-scale rating, magnitude estimate, or rank position).",  # noqa: E501
    )
    textSpan: dx.Embed[Span] | None = dx.field(
        default=None,
        description="Selected text span for span-labeling tasks.",
    )


class JudgmentSet(dx.Model):
    """A set of judgments from a single annotator for an experiment."""

    agent: dx.Embed[AgentRef] | None = dx.field(
        default=None,
        description="The agent (human annotator, ML model, crowd worker, etc.) who produced this judgment set. Use did for ATProto-native annotators, id for anonymized/platform-specific identifiers, knowledgeRef for ORCID or model cards.",  # noqa: E501
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    experimentRef: str = dx.field(
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features (e.g., annotator demographics, session metadata, completion time, payment info).",  # noqa: E501
    )
    judgments: tuple[dx.Embed[Judgment], ...] = dx.field(
        description="generated field",
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references (e.g., crowdsourcing platform, annotator population, methodology source).",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
