# generated by lairs gen; do not edit
# lexicon tree hash cedfb9f34cc55fb5be1abb81dda63fd6a6671af2efd6a5e5923fca0c77ba0fd1
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.media lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AnnotationMetadata,
    FeatureMap,
    KnowledgeRef,
    Licensing,
)
from lairs.records.blobref import BlobRef

__all__ = [
    "AudioInfo",
    "DocumentInfo",
    "Media",
    "VideoInfo",
]


class AudioInfo(dx.Model):
    """Composable audio metadata. Attach to any media record representing audio content: standalone audio files, audio tracks in video, etc."""  # noqa: E501

    bitDepth: int | None = dx.field(
        default=None,
        description="Audio bit depth (e.g., 16, 24, 32).",
        extras={"minimum": 1},
    )
    bitRate: int | None = dx.field(
        default=None,
        description="Audio bitrate in bits per second.",
        extras={"minimum": 1},
    )
    bitRateMode: str | None = dx.field(
        default=None,
        description="Bitrate mode.",
        extras={
            "knownValues": (
                "cbr",
                "vbr",
            ),
            "maxLength": 16,
        },
    )
    channels: int | None = dx.field(
        default=None,
        description="Number of audio channels.",
        extras={"minimum": 1},
    )
    codec: str | None = dx.field(
        default=None,
        description="Audio codec identifier (e.g., 'pcm_s16le', 'aac', 'opus', 'flac').",  # noqa: E501
        extras={"maxLength": 128},
    )
    numberOfSamples: int | None = dx.field(
        default=None,
        description="Total number of audio samples. Enables sample-accurate alignment.",
        extras={"minimum": 0},
    )
    sampleRate: int | None = dx.field(
        default=None,
        description="Audio sample rate in Hz (e.g., 8000, 16000, 22050, 44100, 48000).",
        extras={"minimum": 1},
    )
    segmentationRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.segmentation record structuring the transcript.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    speakerCount: int | None = dx.field(
        default=None,
        description="Number of distinct speakers (for spoken language data).",
        extras={"minimum": 0},
    )
    transcriptRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.expression containing the transcript.",
        extras={"format": "at-uri"},
    )


class DocumentInfo(dx.Model):
    """Composable document/image metadata. Attach to any media record representing scanned documents, manuscripts, printed text, or other page-based media for OCR/HTR annotation workflows."""  # noqa: E501

    colorMode: str | None = dx.field(
        default=None,
        description="Scan color mode.",
        extras={
            "knownValues": (
                "color",
                "grayscale",
                "bitonal",
            ),
            "maxLength": 32,
        },
    )
    dpi: int | None = dx.field(
        default=None,
        description="Scanning resolution in dots per inch (300+ recommended for OCR).",
        extras={"minimum": 1},
    )
    ocrEngine: str | None = dx.field(
        default=None,
        description="OCR/HTR engine identifier (e.g., 'tesseract-5.3', 'transkribus', 'abbyy', 'google-vision').",  # noqa: E501
        extras={"maxLength": 256},
    )
    pageCount: int | None = dx.field(
        default=None,
        description="Number of pages in the document.",
        extras={"minimum": 1},
    )
    scriptSystem: str | None = dx.field(
        default=None,
        description="Writing system (ISO 15924 codes: 'Latn', 'Arab', 'Deva', 'Hans', 'Hant', 'Cyrl', 'Grek', etc.).",  # noqa: E501
        extras={"maxLength": 32},
    )
    writingDirection: str | None = dx.field(
        default=None,
        description="Primary text direction.",
        extras={
            "knownValues": (
                "ltr",
                "rtl",
                "ttb",
                "btt",
            ),
            "maxLength": 8,
        },
    )


class VideoInfo(dx.Model):
    """Composable video metadata. Attach to any media record representing video content."""  # noqa: E501

    aspectRatio: str | None = dx.field(
        default=None,
        description="Display aspect ratio (e.g., '16:9', '4:3', '1:1').",
        extras={"maxLength": 32},
    )
    bitRate: int | None = dx.field(
        default=None,
        description="Video bitrate in bits per second.",
        extras={"minimum": 1},
    )
    codec: str | None = dx.field(
        default=None,
        description="Video codec identifier (e.g., 'h264', 'h265', 'vp9', 'av1', 'prores').",  # noqa: E501
        extras={"maxLength": 128},
    )
    colorSpace: str | None = dx.field(
        default=None,
        description="Color space.",
        extras={
            "knownValues": (
                "rgb",
                "yuv420",
                "yuv422",
                "yuv444",
                "grayscale",
            ),
            "maxLength": 32,
        },
    )
    frameRate: int | None = dx.field(
        default=None,
        description="Frame rate scaled by 100 (e.g., 2997 = 29.97fps). Avoids floats.",
        extras={"minimum": 1},
    )
    height: int | None = dx.field(
        default=None,
        description="Height in pixels.",
        extras={"minimum": 1},
    )
    scanType: str | None = dx.field(
        default=None,
        description="Scan type. Affects frame extraction for annotation.",
        extras={
            "knownValues": (
                "progressive",
                "interlaced",
            ),
            "maxLength": 32,
        },
    )
    width: int | None = dx.field(
        default=None,
        description="Width in pixels.",
        extras={"minimum": 1},
    )


class Media(dx.Model):
    """A media source record (audio, video, image, or document) that can be referenced by expressions and annotations. Modality-specific metadata lives in composable audioInfo/videoInfo/documentInfo objects."""  # noqa: E501

    audio: dx.Embed[AudioInfo] | None = dx.field(
        default=None,
        description="Audio-specific metadata. Present for audio files and videos with audio tracks.",  # noqa: E501
    )
    blob: BlobRef | None = dx.field(
        default=None,
        description="The media blob.",
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    description: str | None = dx.field(
        default=None,
        extras={"maxLength": 10000},
    )
    document: dx.Embed[DocumentInfo] | None = dx.field(
        default=None,
        description="Document-specific metadata. Present for scanned documents, manuscripts, etc.",  # noqa: E501
    )
    durationMs: int | None = dx.field(
        default=None,
        description="Duration in milliseconds (for audio/video).",
        extras={"minimum": 0},
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Eprint records (papers/preprints) describing or associated with this media.",  # noqa: E501
    )
    externalUri: str | None = dx.field(
        default=None,
        description="URI for externally hosted media.",
        extras={"format": "uri", "maxLength": 2048},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features: recording conditions, speaker metadata, quality metrics, consent, etc.",  # noqa: E501
    )
    fileSizeBytes: int | None = dx.field(
        default=None,
        description="File size in bytes.",
        extras={"minimum": 0},
    )
    kind: str = dx.field(
        description="Media kind slug (fallback when kindUri unavailable).",
        extras={
            "knownValues": (
                "audio",
                "video",
                "image",
                "document",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the media kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references.",
    )
    languages: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="BCP-47 language tags this record covers. Empty when language is unspecified or unknown.",  # noqa: E501
    )
    licensing: dx.Embed[Licensing] | None = dx.field(
        default=None,
        description="Distribution licensing terms governing this media (supports dual/multi/component licensing). Canonical license for the media; the consent.license feature, when present, records per-clip consent terms.",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who created/uploaded this media record, with what tool.",  # noqa: E501
    )
    mimeType: str | None = dx.field(
        default=None,
        extras={"maxLength": 128},
    )
    parentMediaRef: str | None = dx.field(
        default=None,
        description="AT-URI of the parent media record this excerpt/clip was extracted from.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    startOffsetMs: int | None = dx.field(
        default=None,
        description="Offset in milliseconds where this excerpt starts within the parent media. Used with parentMediaRef.",  # noqa: E501
        extras={"minimum": 0},
    )
    title: str | None = dx.field(
        default=None,
        extras={"maxLength": 1024},
    )
    video: dx.Embed[VideoInfo] | None = dx.field(
        default=None,
        description="Video-specific metadata. Present for video files and image sequences.",  # noqa: E501
    )
