# generated by lairs gen; do not edit
# lexicon tree hash 1d20dc0bf4cfe7daa2b7aa022fdbdd1a8d405ff126cfcc078277f090f7364067
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.media lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AccessCondition,
    AnnotationMetadata,
    ContentDigest,
    DeviceInfo,
    FeatureMap,
    KnowledgeRef,
    LanguageRef,
    Licensing,
    ObjectRef,
    ReproducibilityInfo,
    Uuid,
)
from lairs.records.blobref import BlobRef

__all__ = [
    "AudioInfo",
    "CoordinateSystem",
    "DocumentInfo",
    "EventCode",
    "EyeTrackingInfo",
    "FilterSpec",
    "ImageInfo",
    "Media",
    "MotionInfo",
    "NamedPoint",
    "SensorSpec",
    "SignalChannel",
    "SignalInfo",
    "SyncInfo",
    "VideoInfo",
    "VolumeInfo",
]


class AudioInfo(dx.Model):
    """Composable audio metadata. Attach to any media record representing audio content: standalone audio files, audio tracks in video, etc."""  # noqa: E501

    bitDepth: int | None = dx.field(
        default=None,
        description="Audio bit depth (e.g., 16, 24, 32).",
        extras={"minimum": 1},
    )
    bitRate: int | None = dx.field(
        default=None,
        description="Audio bitrate in bits per second.",
        extras={"minimum": 1},
    )
    bitRateMode: str | None = dx.field(
        default=None,
        description="Bitrate mode.",
        extras={
            "knownValues": (
                "cbr",
                "vbr",
            ),
            "maxLength": 16,
        },
    )
    channels: int | None = dx.field(
        default=None,
        description="Number of audio channels.",
        extras={"minimum": 1},
    )
    codec: str | None = dx.field(
        default=None,
        description="Audio codec identifier (e.g., 'pcm_s16le', 'aac', 'opus', 'flac').",  # noqa: E501
        extras={"maxLength": 128},
    )
    numberOfSamples: int | None = dx.field(
        default=None,
        description="Total number of audio samples. Enables sample-accurate alignment.",
        extras={"minimum": 0},
    )
    sampleRate: int | None = dx.field(
        default=None,
        description="Audio sample rate in Hz (e.g., 8000, 16000, 22050, 44100, 48000).",
        extras={"minimum": 1},
    )
    segmentationRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.segmentation record structuring the transcript.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    speakerCount: int | None = dx.field(
        default=None,
        description="Number of distinct speakers (for spoken language data).",
        extras={"minimum": 0},
    )
    transcriptRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.expression containing the transcript.",
        extras={"format": "at-uri"},
    )


class NamedPoint(dx.Model):
    """A named point in the enclosing coordinate system, in that system's unit."""

    name: str = dx.field(
        description="Landmark slug (fallback when nameUri unavailable).",
        extras={
            "knownValues": (
                "nasion",
                "lpa",
                "rpa",
                "inion",
                "ac",
                "pc",
                "vertex",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    nameUri: str | None = dx.field(
        default=None,
        description="AT-URI of the landmark definition node.",
        extras={"format": "at-uri"},
    )
    x: int | None = dx.field(
        default=None,
        description="Signed X coordinate of the point, in the enclosing system's unit.",
    )
    y: int | None = dx.field(
        default=None,
        description="Signed Y coordinate of the point, in the enclosing system's unit.",
    )
    z: int | None = dx.field(
        default=None,
        description="Signed Z coordinate of the point, in the enclosing system's unit.",
    )


class CoordinateSystem(dx.Model):
    """The frame in which sensor, landmark, or volume coordinates are expressed. BIDS coordsystem.json, which requires a named system plus units and RECOMMENDS FiducialsCoordinates and AnatomicalLandmarkCoordinates. One def for all four use sites, so the four divergent lists the proposals carried collapse to one."""  # noqa: E501

    description: str | None = dx.field(
        default=None,
        description="Free-text note about this coordinate frame.",
        extras={"maxLength": 4096},
    )
    fiducials: tuple[dx.Embed[NamedPoint], ...] | None = dx.field(
        default_factory=tuple,
        description="Named landmark points defining the frame. BIDS FiducialsCoordinates and AnatomicalLandmarkCoordinates.",  # noqa: E501
    )
    referenceImageRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.media.media of kind volume or image this frame is defined against. BIDS IntendedFor, a filesystem path upstream.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    spatialAxes: str | None = dx.field(
        default=None,
        description="Direction code naming the positive direction of X, Y, Z (fallback when spatialAxesUri unavailable). BIDS Motion SpatialAxes. Determines how every coordinate in the record is read, so a consumer that cannot resolve it MUST NOT assume a default.",  # noqa: E501
        extras={
            "knownValues": (
                "RAS",
                "LAS",
                "RAI",
                "LPS",
                "ARS",
                "ALS",
                "FRU",
                "FLU",
                "custom",
            ),
            "maxLength": 32,
        },
    )
    spatialAxesUri: str | None = dx.field(
        default=None,
        description="AT-URI of the axis convention definition node (typeDef of `spatial-axes`).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    system: str = dx.field(
        description="Coordinate system slug (fallback when systemUri unavailable). Covers the BIDS EEG, MEG and iEEG coordinate system lists plus the stereotaxic spaces used for volumetric data.",  # noqa: E501
        extras={
            "knownValues": (
                "captrak",
                "eeglab",
                "ctf-head",
                "ctf-device",
                "elekta-neuromag-head",
                "elekta-neuromag-device",
                "bti-4d-head",
                "acpc",
                "scanner-ras",
                "mni152-nlin-2009c",
                "mni305",
                "talairach",
                "fsaverage",
                "individual-t1",
                "voxel-index",
                "pixel",
                "world-metric",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    systemUri: str | None = dx.field(
        default=None,
        description="AT-URI of the coordinate system definition node (typeDef of `coordinate-system`). Values MUST agree with pub.layers.defs#spatialEntity.crs.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    unit: str | None = dx.field(
        default=None,
        description="Unit of the stored integer coordinates (fallback when unitUri unavailable). BIDS coordinate units are m, mm or cm, plus pixels for iEEG on a photograph; nanometre is the integer-safe encoding of all three.",  # noqa: E501
        extras={
            "knownValues": (
                "nanometre",
                "micrometre",
                "pixel",
                "voxel",
                "per-mille-normalized",
            ),
            "maxLength": 64,
        },
    )
    unitUri: str | None = dx.field(
        default=None,
        description="AT-URI of the coordinate unit definition node.",
        extras={"format": "at-uri"},
    )


class DocumentInfo(dx.Model):
    """Composable document/image metadata. Attach to any media record representing scanned documents, manuscripts, printed text, or other page-based media for OCR/HTR annotation workflows."""  # noqa: E501

    colorMode: str | None = dx.field(
        default=None,
        description="Scan color mode.",
        extras={
            "knownValues": (
                "color",
                "grayscale",
                "bitonal",
            ),
            "maxLength": 32,
        },
    )
    dpi: int | None = dx.field(
        default=None,
        description="Scanning resolution in dots per inch (300+ recommended for OCR).",
        extras={"minimum": 1},
    )
    ocrEngine: str | None = dx.field(
        default=None,
        description="OCR/HTR engine identifier (e.g., 'tesseract-5.3', 'transkribus', 'abbyy', 'google-vision').",  # noqa: E501
        extras={"maxLength": 256},
    )
    pageCount: int | None = dx.field(
        default=None,
        description="Number of pages in the document.",
        extras={"minimum": 1},
    )
    scriptSystem: str | None = dx.field(
        default=None,
        description="Writing system (ISO 15924 codes: 'Latn', 'Arab', 'Deva', 'Hans', 'Hant', 'Cyrl', 'Grek', etc.).",  # noqa: E501
        extras={"maxLength": 32},
    )
    writingDirection: str | None = dx.field(
        default=None,
        description="Primary text direction slug (fallback when writingDirectionUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "ltr",
                "rtl",
                "ttb",
                "boustrophedon",
                "custom",
            ),
            "maxLength": 32,
        },
    )
    writingDirectionUri: str | None = dx.field(
        default=None,
        description="AT-URI of the writing-direction definition node (typeDef of `writing-direction` at layers-core.ontology.layers.pub). Refines writingDirection; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class EventCode(dx.Model):
    """One trigger code and what it means. Grounds BIDS events.tsv trial_type, a bare string upstream, in a type definition node."""  # noqa: E501

    channel: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="The channel this code appears on, when the recording has several trigger lines.",  # noqa: E501
    )
    code: int = dx.field(
        description="Integer value written on the trigger channel.",
    )
    description: str | None = dx.field(
        default=None,
        description="Free-text note about this trigger code.",
        extras={"maxLength": 1024},
    )
    knowledgeRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="External grounding, for instance a HED tag (source hed) or a Cognitive Atlas concept.",  # noqa: E501
    )
    label: str | None = dx.field(
        default=None,
        description="Condition label as the experimenter spells it.",
        extras={"maxLength": 256},
    )
    typeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the condition or event-type definition node, typically a pub.layers.ontology.typeDef.",  # noqa: E501
        extras={"format": "at-uri"},
    )


class EyeTrackingInfo(dx.Model):
    """Composable eye-tracking metadata, carried alongside signalInfo. Screen geometry is deliberately absent: the same tracker at a different viewing distance yields different degrees of visual angle, so it is a property of stimulus presentation and lives on pub.layers.judgment.defs#presentationSpec.screen, which is where BIDS puts it (the StimulusPresentation object of the events sidecar)."""  # noqa: E501

    averageCalibrationErrorMicrodegrees: int | None = dx.field(
        default=None,
        description="BIDS AverageCalibrationError. Microdegrees because typical values are fractions of a degree.",  # noqa: E501
        extras={"minimum": 0},
    )
    calibrationCount: int | None = dx.field(
        default=None,
        description="BIDS CalibrationCount.",
        extras={"minimum": 0},
    )
    calibrationPositionCount: int | None = dx.field(
        default=None,
        description="BIDS CalibrationPosition.",
        extras={"minimum": 0},
    )
    calibrationType: str | None = dx.field(
        default=None,
        description="BIDS CalibrationType (fallback when the Uri is unavailable), whose examples are H3 and HV9.",  # noqa: E501
        extras={
            "knownValues": (
                "h3",
                "hv5",
                "hv9",
                "hv13",
                "none",
                "custom",
            ),
            "maxLength": 32,
        },
    )
    calibrationTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the calibration grid definition node.",
        extras={"format": "at-uri"},
    )
    device: dx.Embed[DeviceInfo] | None = dx.field(
        default=None,
        description="Eye-tracking hardware.",
    )
    eventDetection: str | None = dx.field(
        default=None,
        description="Algorithm used to derive fixations and saccades (fallback when the Uri is unavailable). Absent means the trace is raw and no events were derived.",  # noqa: E501
        extras={
            "knownValues": (
                "velocity-threshold",
                "dispersion-threshold",
                "eyelink-parser",
                "engbert-kliegl",
                "none",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    eventDetectionUri: str | None = dx.field(
        default=None,
        description="AT-URI of the fixation and saccade detection algorithm definition node.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    maximalCalibrationErrorMicrodegrees: int | None = dx.field(
        default=None,
        description="BIDS MaximalCalibrationError.",
        extras={"minimum": 0},
    )
    method: str | None = dx.field(
        default=None,
        description="Tracking method slug (fallback when methodUri unavailable). BIDS EyeTrackingMethod, whose documented values include P-CR, DPI and EOG.",  # noqa: E501
        extras={
            "knownValues": (
                "p-cr",
                "dpi",
                "eog",
                "video-oculography",
                "scleral-search-coil",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    methodUri: str | None = dx.field(
        default=None,
        description="AT-URI of the eye-tracking method definition node.",
        extras={"format": "at-uri"},
    )
    pupilFitMethod: str | None = dx.field(
        default=None,
        description="BIDS PupilFitMethod (fallback when the Uri is unavailable).",
        extras={
            "knownValues": (
                "ellipse",
                "centroid",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    pupilFitMethodUri: str | None = dx.field(
        default=None,
        description="AT-URI of the pupil fit method definition node.",
        extras={"format": "at-uri"},
    )
    recordedEye: str | None = dx.field(
        default=None,
        description="Which eye was recorded (fallback when recordedEyeUri unavailable). BIDS RecordedEye, REQUIRED for eye-tracking recordings.",  # noqa: E501
        extras={
            "knownValues": (
                "left",
                "right",
                "both",
                "cyclopean",
            ),
            "maxLength": 32,
        },
    )
    recordedEyeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the recorded-eye definition node.",
        extras={"format": "at-uri"},
    )
    sampleCoordinateSystem: str | None = dx.field(
        default=None,
        description="What the x and y samples mean (fallback when the Uri is unavailable). BIDS SampleCoordinateSystem, REQUIRED. gaze-on-screen is the value that makes presentationSpec.screen mandatory.",  # noqa: E501
        extras={
            "knownValues": (
                "gaze-on-screen",
                "eye-in-head",
                "gaze-in-world",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    sampleCoordinateSystemUri: str | None = dx.field(
        default=None,
        description="AT-URI of the gaze coordinate system definition node.",
        extras={"format": "at-uri"},
    )
    sampleCoordinateUnit: str | None = dx.field(
        default=None,
        description="Unit of the gaze samples (fallback when the Uri is unavailable). BIDS SampleCoordinateUnits.",  # noqa: E501
        extras={
            "knownValues": (
                "pixel",
                "nanometre",
                "microdegree",
                "per-mille-normalized",
            ),
            "maxLength": 64,
        },
    )
    sampleCoordinateUnitUri: str | None = dx.field(
        default=None,
        description="AT-URI of the gaze sample unit definition node.",
        extras={"format": "at-uri"},
    )
    trackerDistanceNanometres: int | None = dx.field(
        default=None,
        description="BIDS EyeTrackerDistance.",
        extras={"minimum": 0},
    )


class FilterSpec(dx.Model):
    """One filter applied to a recording. BIDS makes SoftwareFilters REQUIRED and HardwareFilters RECOMMENDED and types both as arbitrary nested JSON, so a consumer cannot today decide whether a recording is admissible for a given analysis without reading prose. Every parameter here is an integer in a named unit."""  # noqa: E501

    bandwidthMilliHz: int | None = dx.field(
        default=None,
        description="Bandwidth of the stage, in millihertz.",
        extras={"minimum": 0},
    )
    centreMilliHz: int | None = dx.field(
        default=None,
        description="Centre frequency, for notch and bandstop stages, in millihertz.",
        extras={"minimum": 0},
    )
    componentsRemoved: int | None = dx.field(
        default=None,
        description="For ica and ssp.",
        extras={"minimum": 0},
    )
    description: str | None = dx.field(
        default=None,
        description="Free-text note about this filter stage.",
        extras={"maxLength": 2048},
    )
    design: str | None = dx.field(
        default=None,
        description="Filter design slug (fallback when designUri unavailable).",
        extras={
            "knownValues": (
                "butterworth",
                "chebyshev-1",
                "chebyshev-2",
                "elliptic",
                "bessel",
                "fir-windowed",
                "fir-least-squares",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    designUri: str | None = dx.field(
        default=None,
        description="AT-URI of the filter design definition node.",
        extras={"format": "at-uri"},
    )
    direction: str | None = dx.field(
        default=None,
        description="Whether the filter introduces phase shift (fallback when directionUri unavailable). Load-bearing for any latency claim about an ERP or evoked component.",  # noqa: E501
        extras={
            "knownValues": (
                "causal",
                "zero-phase",
                "unknown",
            ),
            "maxLength": 32,
        },
    )
    directionUri: str | None = dx.field(
        default=None,
        description="AT-URI of the filter direction definition node.",
        extras={"format": "at-uri"},
    )
    highCutoffMilliHz: int | None = dx.field(
        default=None,
        description="Low-pass cutoff of this filter stage, in millihertz.",
        extras={"minimum": 0},
    )
    lowCutoffMilliHz: int | None = dx.field(
        default=None,
        description="High-pass cutoff of this filter stage, in millihertz.",
        extras={"minimum": 0},
    )
    order: int | None = dx.field(
        default=None,
        description="Filter order.",
        extras={"minimum": 0},
    )
    software: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
        description="Software that applied the filter, reusing the shared block rather than re-declaring name and version.",  # noqa: E501
    )
    stage: str | None = dx.field(
        default=None,
        description="Where the filter was applied (fallback when stageUri unavailable). Distinguishes BIDS HardwareFilters from SoftwareFilters.",  # noqa: E501
        extras={
            "knownValues": (
                "hardware",
                "software",
                "unknown",
            ),
            "maxLength": 32,
        },
    )
    stageUri: str | None = dx.field(
        default=None,
        description="AT-URI of the filter stage definition node.",
        extras={"format": "at-uri"},
    )
    type: str = dx.field(
        description="Filter type slug (fallback when typeUri unavailable).",
        extras={
            "knownValues": (
                "highpass",
                "lowpass",
                "bandpass",
                "bandstop",
                "notch",
                "detrend",
                "resample",
                "rereference",
                "ica",
                "ssp",
                "regression",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    typeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the filter type definition node.",
        extras={"format": "at-uri"},
    )


class ImageInfo(dx.Model):
    """Composable still-image metadata. Added because 0.8.0 has no image block at all, so a photograph's width and height had to borrow videoInfo, whose own description says it is for video content."""  # noqa: E501

    bitDepth: int | None = dx.field(
        default=None,
        description="Bit depth per channel.",
        extras={"minimum": 1},
    )
    captureDevice: dx.Embed[DeviceInfo] | None = dx.field(
        default=None,
        description="Camera or scanner, structured rather than concatenated into a format string.",  # noqa: E501
    )
    codec: str | None = dx.field(
        default=None,
        description="Image codec identifier (jpeg, png, webp, jp2, tiff-lzw). Wire-format code, exempt from pairing.",  # noqa: E501
        extras={"maxLength": 128},
    )
    colorSpace: str | None = dx.field(
        default=None,
        description="Colour space slug (fallback when colorSpaceUri unavailable). Paired here even though the sibling videoInfo.colorSpace is not, since a new field should not inherit an existing wart.",  # noqa: E501
        extras={
            "knownValues": (
                "srgb",
                "adobe-rgb",
                "display-p3",
                "rec2020",
                "cmyk",
                "grayscale",
                "bitonal",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    colorSpaceUri: str | None = dx.field(
        default=None,
        description="AT-URI of the colour space definition node.",
        extras={"format": "at-uri"},
    )
    dpi: int | None = dx.field(
        default=None,
        description="Resolution in dots per inch, when the image derives from a physical original.",  # noqa: E501
        extras={"minimum": 1},
    )
    height: int | None = dx.field(
        default=None,
        description="Height in pixels.",
        extras={"minimum": 1},
    )
    orientation: int | None = dx.field(
        default=None,
        description="EXIF orientation tag.",
        extras={"minimum": 1, "maximum": 8},
    )
    width: int | None = dx.field(
        default=None,
        description="Width in pixels.",
        extras={"minimum": 1},
    )


class MotionInfo(dx.Model):
    """Composable motion-capture and articulography metadata: optical marker systems, inertial suits, electromagnetic articulography, ultrasound tongue imaging, and body or hand pose streams. Follows BIDS Motion, in which a tracking system is a grouping level below the session, so one session routinely carries several media records at different rates. A motion stream also carries signalInfo, because in BIDS Motion a mocap channel is typed POS, ORNT, VEL, ACCEL, GYRO, MAGN, ANGACCEL or JNTANG, that is, it is a sampled signal."""  # noqa: E501

    coordinateSystem: dx.Embed[CoordinateSystem] | None = dx.field(
        default=None,
        description="Carries spatialAxes; a motion stream must not define a second axis vocabulary.",  # noqa: E501
    )
    device: dx.Embed[DeviceInfo] | None = dx.field(
        default=None,
        description="Motion-capture hardware.",
    )
    format: str | None = dx.field(
        default=None,
        description="Container format slug (fallback when formatUri unavailable). Wire-format code.",  # noqa: E501
        extras={
            "knownValues": (
                "c3d",
                "bvh",
                "trc",
                "fbx",
                "tsv",
                "csv",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    formatUri: str | None = dx.field(
        default=None,
        description="AT-URI of the motion container format definition node.",
        extras={"format": "at-uri"},
    )
    rotationOrder: str | None = dx.field(
        default=None,
        description="BIDS Motion RotationOrder (fallback when the Uri is unavailable).",
        extras={
            "knownValues": (
                "xyz",
                "xzy",
                "yxz",
                "yzx",
                "zxy",
                "zyx",
                "quaternion",
            ),
            "maxLength": 32,
        },
    )
    rotationOrderUri: str | None = dx.field(
        default=None,
        description="AT-URI of the rotation order definition node.",
        extras={"format": "at-uri"},
    )
    rotationRule: str | None = dx.field(
        default=None,
        description="BIDS Motion RotationRule (fallback when the Uri is unavailable).",
        extras={
            "knownValues": (
                "right-hand",
                "left-hand",
            ),
            "maxLength": 32,
        },
    )
    rotationRuleUri: str | None = dx.field(
        default=None,
        description="AT-URI of the rotation handedness definition node.",
        extras={"format": "at-uri"},
    )
    skeleton: str | None = dx.field(
        default=None,
        description="Skeleton or marker-set slug (fallback when skeletonUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "coco-17",
                "openpose-body25",
                "openpose-135",
                "mediapipe-holistic",
                "mediapipe-hand-21",
                "smpl",
                "smplx",
                "vicon-plug-in-gait",
                "xsens-mvn",
                "ema-tongue-jaw-lips",
                "c3d-custom",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    skeletonUri: str | None = dx.field(
        default=None,
        description="AT-URI of the skeleton or marker-set definition node (typeDef of `skeleton`), which is where joint identity, joint order and joint topology are DEFINED. This is why no pose anchor is needed: the channels carry the numbers, this carries their meaning.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    trackedPointCount: int | None = dx.field(
        default=None,
        description="Number of tracked points, markers, or joints.",
        extras={"minimum": 0},
    )
    trackingSystem: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="The pub.layers.acquisition.defs#run or session stream grouping this system, as an objectRef. BIDS Motion tracksys entity, a bare label upstream.",  # noqa: E501
    )


class SensorSpec(dx.Model):
    """Physical placement of one sensor: an EEG electrode, an iEEG contact, a MEG coil, an fNIRS optode, a motion marker, or an anatomical landmark. Coordinates are signed integer nanometres in the frame named by the enclosing coordinateSystem."""  # noqa: E501

    anatomyRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="Grounded anatomical localization. NWB makes electrodes.location a required column and BIDS iEEG carries it free text; use source uberon. For iEEG this is a subject-specific claim about a subject-specific brain and inherits the participant's identifiability declaration.",  # noqa: E501
    )
    contactAreaSquareMicrometres: int | None = dx.field(
        default=None,
        description="BIDS iEEG electrodes.tsv size, a REQUIRED column, square millimetres upstream. Load-bearing for current-density interpretation.",  # noqa: E501
        extras={"minimum": 0},
    )
    description: str | None = dx.field(
        default=None,
        description="Free-text note about this sensor.",
        extras={"maxLength": 1024},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended per-sensor features not captured by the typed fields.",
    )
    group: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="Electrode group or shaft. NWB ElectrodeGroup, whose name, description, location and device are all required there.",  # noqa: E501
    )
    hemisphere: str | None = dx.field(
        default=None,
        description="Hemisphere slug (fallback when hemisphereUri unavailable). BIDS iEEG electrodes.tsv hemisphere.",  # noqa: E501
        extras={
            "knownValues": (
                "left",
                "right",
                "midline",
                "not-reported",
            ),
            "maxLength": 32,
        },
    )
    hemisphereUri: str | None = dx.field(
        default=None,
        description="AT-URI of the hemisphere definition node.",
        extras={"format": "at-uri"},
    )
    impedanceMilliOhm: int | None = dx.field(
        default=None,
        description="BIDS electrodes.tsv impedance; NWB electrodes.imp.",
        extras={"minimum": 0},
    )
    material: str | None = dx.field(
        default=None,
        description="Material slug (fallback when materialUri unavailable). BIDS electrodes.tsv material, free text upstream, where Ag/AgCl already has three predictable spellings.",  # noqa: E501
        extras={
            "knownValues": (
                "ag-agcl",
                "platinum",
                "platinum-iridium",
                "gold",
                "tin",
                "stainless-steel",
                "silicon",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    materialUri: str | None = dx.field(
        default=None,
        description="AT-URI of the electrode material definition node (typeDef of `electrode-material`).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    name: str = dx.field(
        description="Sensor name exactly as in the raw file.",
        extras={"maxLength": 128},
    )
    type: str = dx.field(
        description="Sensor type slug (fallback when typeUri unavailable). BIDS optodes.tsv type is REQUIRED and takes source or detector; the rest cover the electrode, coil, marker and landmark cases BIDS spreads across electrodes.tsv and coordsystem.json.",  # noqa: E501
        extras={
            "knownValues": (
                "electrode",
                "depth-contact",
                "grid-contact",
                "strip-contact",
                "magnetometer",
                "gradiometer",
                "reference-coil",
                "head-position-coil",
                "source",
                "detector",
                "marker",
                "imu",
                "camera",
                "fiducial",
                "anatomical-landmark",
                "head-point",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    typeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the sensor type definition node (typeDef of `sensor-type`).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    uuid: dx.Embed[Uuid] = dx.field(
        description="Stable identifier within this record. Required because channels, anchors and spatial regions point at sensors.",  # noqa: E501
    )
    xNanometres: int | None = dx.field(
        default=None,
        description="Signed X. BIDS electrodes.tsv x and optodes.tsv x, REQUIRED columns; NWB electrodes.x.",  # noqa: E501
    )
    yNanometres: int | None = dx.field(
        default=None,
        description="Signed Y.",
    )
    zNanometres: int | None = dx.field(
        default=None,
        description="Signed Z.",
    )


class SignalChannel(dx.Model):
    """One recorded channel. BIDS channels.tsv, whose name, type and units columns are REQUIRED for every electrophysiology modality and which additionally makes low_cutoff and high_cutoff REQUIRED for iEEG. Position is held by reference through sensor, because channel and sensor are not in one-to-one correspondence."""  # noqa: E501

    description: str | None = dx.field(
        default=None,
        description="Free-text note about this channel.",
        extras={"maxLength": 1024},
    )
    detectorSensor: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="Receiving optode. BIDS NIRS channels.tsv detector, a REQUIRED column.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended per-channel features not captured by the typed fields.",
    )
    group: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="Electrode group, shaft, grid, or tracking system this channel belongs to. NWB ElectrodeGroup; BIDS Motion tracksys.",  # noqa: E501
    )
    highCutoffMilliHz: int | None = dx.field(
        default=None,
        description="Low-pass cutoff. BIDS channels.tsv high_cutoff, a REQUIRED column for iEEG.",  # noqa: E501
        extras={"minimum": 0},
    )
    lowCutoffMilliHz: int | None = dx.field(
        default=None,
        description="High-pass cutoff. 0 means DC-coupled. BIDS channels.tsv low_cutoff, a REQUIRED column for iEEG.",  # noqa: E501
        extras={"minimum": 0},
    )
    name: str = dx.field(
        description="Channel name exactly as in the raw file (Cz, MEG0113, S1-D1-760, gaze_x).",  # noqa: E501
        extras={"maxLength": 128},
    )
    notchMilliHz: int | None = dx.field(
        default=None,
        description="BIDS channels.tsv notch.",
        extras={"minimum": 0},
    )
    referenceChannel: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="Per-channel reference for bipolar and mixed intracranial montages. BIDS channels.tsv reference.",  # noqa: E501
    )
    samplingFrequencyMilliHz: int | None = dx.field(
        default=None,
        description="Per-channel rate when it differs from the recording's nominal rate, routine for auxiliary channels multiplexed into one file.",  # noqa: E501
        extras={"minimum": 1},
    )
    sensor: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="The sensors entry this channel reads from. How a channel acquires a position without duplicating coordinates per channel.",  # noqa: E501
    )
    sourceSensor: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="Emitting optode. BIDS NIRS channels.tsv source, a REQUIRED column.",  # noqa: E501
    )
    status: str | None = dx.field(
        default=None,
        description="Channel quality slug (fallback when statusUri unavailable). BIDS channels.tsv status.",  # noqa: E501
        extras={
            "knownValues": (
                "good",
                "bad",
                "interpolated",
                "not-reported",
            ),
            "maxLength": 32,
        },
    )
    statusDescription: str | None = dx.field(
        default=None,
        description="Why the channel is bad or interpolated. BIDS channels.tsv status_description.",  # noqa: E501
        extras={"maxLength": 1024},
    )
    statusUri: str | None = dx.field(
        default=None,
        description="AT-URI of the channel status definition node.",
        extras={"format": "at-uri"},
    )
    type: str = dx.field(
        description="Channel type slug (fallback when typeUri unavailable). Union of the BIDS keyword sets, uppercase as BIDS spells them.",  # noqa: E501
        extras={
            "knownValues": (
                "EEG",
                "REF",
                "EOG",
                "HEOG",
                "VEOG",
                "ECG",
                "EMG",
                "GSR",
                "PPG",
                "RESP",
                "TEMP",
                "PUPIL",
                "EYEGAZE",
                "TRIG",
                "SYSCLOCK",
                "AUDIO",
                "MISC",
                "MEGMAG",
                "MEGGRADAXIAL",
                "MEGGRADPLANAR",
                "MEGREFMAG",
                "MEGREFGRADAXIAL",
                "MEGREFGRADPLANAR",
                "MEGOTHER",
                "HLU",
                "FITERR",
                "ADC",
                "DAC",
                "SEEG",
                "ECOG",
                "DBS",
                "NIRSCWAMPLITUDE",
                "NIRSCWOPTICALDENSITY",
                "NIRSCWHBO",
                "NIRSCWHBR",
                "ACCEL",
                "GYRO",
                "MAGN",
                "ORNT",
                "POS",
                "VEL",
                "ANGACCEL",
                "JNTANG",
                "LATENCY",
                "CUSTOM",
            ),
            "maxLength": 64,
        },
    )
    typeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the channel type definition node (typeDef of `channel-type` at layers-acquisition.ontology.layers.pub). The authoritative field: the union of the BIDS EEG, MEG, iEEG, NIRS and Motion keyword sets already runs to roughly sixty terms and grows with each extension proposal. The knownValues below are a seed, not a closed list.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    unit: str | None = dx.field(
        default=None,
        description="Physical unit of this channel's samples (fallback when unitUri unavailable). BIDS channels.tsv units, REQUIRED, which expects SI units.",  # noqa: E501
        extras={
            "knownValues": (
                "volt",
                "millivolt",
                "microvolt",
                "tesla",
                "femtotesla",
                "ampere",
                "microampere",
                "ohm",
                "siemens",
                "microsiemens",
                "degree-celsius",
                "pixel",
                "millimetre",
                "degree",
                "microdegree",
                "radian",
                "metre-per-second-squared",
                "radian-per-second",
                "arbitrary",
                "not-applicable",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    unitUri: str | None = dx.field(
        default=None,
        description="AT-URI of the physical unit definition node (typeDef of `si-unit`).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    uuid: dx.Embed[Uuid] = dx.field(
        description="Stable identifier for this channel within this record. Required because anchors, reference declarations and sync declarations point at channels, and a name or a positional index silently mis-addresses when a republished recording drops two bad channels.",  # noqa: E501
    )
    wavelengthPicometres: int | None = dx.field(
        default=None,
        description="Nominal wavelength (760 nm = 760000). BIDS NIRS channels.tsv wavelength_nominal, a REQUIRED column.",  # noqa: E501
        extras={"minimum": 1},
    )


class SignalInfo(dx.Model):
    """Composable metadata for a sampled time-series recording. Attach to any media record of kind signal or motion. Frequencies are millihertz because BIDS types SamplingFrequency as number and 512.03 Hz occurs; lengths are nanometres because iEEG contact localization is reported sub-millimetre; times are session-relative nanoseconds, never UTC-epoch, since 2^53 ns is about 104 days."""  # noqa: E501

    associatedEmptyRoomRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.media.media holding the empty-room noise recording. BIDS AssociatedEmptyRoom is a filesystem path; an AT-URI is the structured form of the same relation.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    channelCount: int | None = dx.field(
        default=None,
        description="Total recorded channels. BIDS EEGChannelCount / MEGChannelCount / NIRSChannelCount. Authoritative when channels is not fully enumerated.",  # noqa: E501
        extras={"minimum": 0},
    )
    channels: tuple[dx.Embed[SignalChannel], ...] | None = dx.field(
        default_factory=tuple,
        description="Per-channel table in acquisition order. BIDS channels.tsv, whose name, type and units columns are REQUIRED. Inline rather than one record per channel: getRepo bulk export is fast and unmetered while listRecords caps at 100 per page, and a montage is one logical object.",  # noqa: E501
    )
    cogAtlasRef: dx.Embed[KnowledgeRef] | None = dx.field(
        default=None,
        description="Cognitive Atlas term for the task. BIDS CogAtlasID is RECOMMENDED on every electrophysiology and behavioural sidecar. Use source cognitive-atlas.",  # noqa: E501
    )
    continuousHeadLocalization: bool | None = dx.field(
        default=None,
        description="BIDS ContinuousHeadLocalization.",
    )
    coordinateSystem: dx.Embed[CoordinateSystem] | None = dx.field(
        default=None,
        description="Frame in which sensors coordinates are expressed. BIDS coordsystem.json.",  # noqa: E501
    )
    detectorOptodeCount: int | None = dx.field(
        default=None,
        description="BIDS NIRSDetectorOptodeCount, REQUIRED in the NIRS sidecar.",
        extras={"minimum": 0},
    )
    device: dx.Embed[DeviceInfo] | None = dx.field(
        default=None,
        description="Acquisition hardware. BIDS Manufacturer / ManufacturersModelName / DeviceSerialNumber / SoftwareVersions; NWB Device.",  # noqa: E501
    )
    dewarPosition: str | None = dx.field(
        default=None,
        description="MEG dewar position slug (fallback when dewarPositionUri unavailable). BIDS DewarPosition, REQUIRED in the MEG sidecar.",  # noqa: E501
        extras={
            "knownValues": (
                "upright",
                "supine",
                "degrees-45",
                "custom",
            ),
            "maxLength": 64,
        },
    )
    dewarPositionUri: str | None = dx.field(
        default=None,
        description="AT-URI of the dewar position definition node.",
        extras={"format": "at-uri"},
    )
    digitizedHeadPoints: bool | None = dx.field(
        default=None,
        description="BIDS DigitizedHeadPoints, REQUIRED in the MEG sidecar.",
    )
    digitizedLandmarks: bool | None = dx.field(
        default=None,
        description="BIDS DigitizedLandmarks, REQUIRED in the MEG sidecar.",
    )
    epochCount: int | None = dx.field(
        default=None,
        description="Number of epochs, for epoched recordings.",
        extras={"minimum": 0},
    )
    epochLengthNanos: int | None = dx.field(
        default=None,
        description="BIDS EpochLength. Absent for continuous recordings.",
        extras={"minimum": 0},
    )
    eventChannel: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="The trigger or stimulus-code channel, as an objectRef into this record's channels.",  # noqa: E501
    )
    eventCodes: tuple[dx.Embed[EventCode], ...] | None = dx.field(
        default_factory=tuple,
        description="Trigger codes and their meanings. BIDS events.tsv carries trial_type as a bare string; grounding each code through a typeDef lets two labs' code 12 be recognized as the same condition or as different ones.",  # noqa: E501
    )
    eventLayerRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.annotation.annotationLayer of kind tier holding the decoded event stream. This is where BIDS events.tsv lands: onset and duration map to anchor.temporalSpan or anchor.signalSpan, trial_type to the layer subkind or the annotation label.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features not captured by the typed fields.",
    )
    filterStatus: str | None = dx.field(
        default=None,
        description="Whether filters is a complete account (fallback when filterStatusUri unavailable). BIDS makes SoftwareFilters REQUIRED and permits the literal n/a, which conflates none-applied with not-reported; separating them means an empty filters array is unambiguous.",  # noqa: E501
        extras={
            "knownValues": (
                "as-listed",
                "none-applied",
                "not-reported",
            ),
            "maxLength": 64,
        },
    )
    filterStatusUri: str | None = dx.field(
        default=None,
        description="AT-URI of the filter-reporting status definition node.",
        extras={"format": "at-uri"},
    )
    filters: tuple[dx.Embed[FilterSpec], ...] | None = dx.field(
        default_factory=tuple,
        description="Filters in application order. Carries BIDS HardwareFilters and SoftwareFilters, arbitrary untyped JSON upstream, as a typed list so a consumer can decide admissibility without parsing prose.",  # noqa: E501
    )
    format: str | None = dx.field(
        default=None,
        description="Container format slug (fallback when formatUri unavailable). Names what a reader must open; mimeType names the wire type, which for most of these is application/octet-stream.",  # noqa: E501
        extras={
            "knownValues": (
                "edf",
                "edf-plus",
                "bdf",
                "fif",
                "eeglab-set",
                "brainvision",
                "nwb",
                "nix",
                "snirf",
                "asc",
                "edf-eyelink",
                "c3d",
                "trc",
                "bvh",
                "tsv",
                "csv",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    formatUri: str | None = dx.field(
        default=None,
        description="AT-URI of the container format definition node (typeDef of `signal-format` at layers-acquisition.ontology.layers.pub).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    groundSensor: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="The ground electrode. BIDS EEGGround / iEEGGround.",
    )
    headCircumferenceNanometres: int | None = dx.field(
        default=None,
        description="BIDS HeadCircumference, centimetres upstream. On the recording rather than the participant because it is measured at acquisition.",  # noqa: E501
        extras={"minimum": 0},
    )
    maxMovementNanometres: int | None = dx.field(
        default=None,
        description="BIDS MaxMovement.",
        extras={"minimum": 0},
    )
    modality: str = dx.field(
        description="Modality slug (fallback when modalityUri unavailable). Mirrors recordingMethod.method member for member, extended with the continuous physiological channels that vocabulary omits.",  # noqa: E501
        extras={
            "knownValues": (
                "eeg",
                "meg",
                "ieeg",
                "ecog",
                "fmri",
                "fnirs",
                "eye-tracking",
                "pupillometry",
                "emg",
                "ecg",
                "skin-conductance",
                "respiration",
                "mouse-tracking",
                "keystroke",
                "motion-capture",
                "articulography",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    modalityUri: str | None = dx.field(
        default=None,
        description="AT-URI of the modality definition node: a pub.layers.ontology.typeDef of the `modality` ontology at layers-core.ontology.layers.pub, or a pub.layers.graph.graphNode. The SAME node set is named by pub.layers.judgment.defs#recordingMethod.methodUri and pub.layers.catalog.defs#contentSummary.modalityUri. Each modality node reaches its carrier node by parentTypeRef, so media.kindUri is the parent rather than a synonym. Refines modality; never replaces it.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    numberOfSamples: int | None = dx.field(
        default=None,
        description="Total samples per channel. With samplingFrequencyMilliHz this makes pub.layers.defs#signalSpan sample anchoring exact.",  # noqa: E501
        extras={"minimum": 0},
    )
    placementScheme: str | None = dx.field(
        default=None,
        description="Placement scheme slug (fallback when placementSchemeUri unavailable). BIDS EEGPlacementScheme, free text upstream.",  # noqa: E501
        extras={
            "knownValues": (
                "10-20",
                "10-10",
                "10-5",
                "biosemi-32",
                "biosemi-64",
                "biosemi-128",
                "egi-hydrocel-128",
                "egi-hydrocel-256",
                "ctf-275",
                "neuromag-306",
                "subdural-grid",
                "subdural-strip",
                "depth-electrode",
                "mixed-intracranial",
                "subject-specific",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    placementSchemeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the electrode or sensor placement definition node (typeDef of `electrode-placement`).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    powerLineFrequencyMilliHz: int | None = dx.field(
        default=None,
        description="Mains frequency in millihertz (50000 or 60000). BIDS PowerLineFrequency, REQUIRED in every electrophysiology sidecar: no downstream filtering decision can be made without it.",  # noqa: E501
        extras={"minimum": 0},
    )
    recordingDurationNanos: int | None = dx.field(
        default=None,
        description="BIDS RecordingDuration, given in seconds upstream.",
        extras={"minimum": 0},
    )
    recordingType: str | None = dx.field(
        default=None,
        description="Recording continuity slug (fallback when recordingTypeUri unavailable). BIDS RecordingType, same three values.",  # noqa: E501
        extras={
            "knownValues": (
                "continuous",
                "epoched",
                "discontinuous",
            ),
            "maxLength": 64,
        },
    )
    recordingTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the recording continuity definition node.",
        extras={"format": "at-uri"},
    )
    referenceDescription: str | None = dx.field(
        default=None,
        description="Free-text reference detail for schemes the slug vocabulary cannot express. Carries BIDS EEGReference verbatim when it does not map.",  # noqa: E501
        extras={"maxLength": 2048},
    )
    referenceScheme: str | None = dx.field(
        default=None,
        description="Referencing scheme slug (fallback when referenceSchemeUri unavailable). BIDS EEGReference and iEEGReference are both REQUIRED and both free text upstream; typing the common cases while keeping referenceDescription for the rest is the improvement over the upstream string.",  # noqa: E501
        extras={
            "knownValues": (
                "single-electrode",
                "linked-mastoids",
                "linked-ears",
                "average",
                "rest",
                "bipolar",
                "laplacian",
                "intracranial-common",
                "hardware-common",
                "not-applicable",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    referenceSchemeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the reference scheme definition node (typeDef of `eeg-reference-scheme`).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    referenceSensor: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="The reference electrode, as an objectRef whose objectId names a sensors[] uuid in this record. Replaces a free-text channel name, which cannot be validated and cannot be detected as dangling.",  # noqa: E501
    )
    samplingFrequencyMilliHz: int = dx.field(
        description="Nominal sampling frequency in millihertz (2048 Hz = 2048000). BIDS SamplingFrequency, REQUIRED in the EEG, MEG, iEEG and NIRS sidecars; NWB ElectricalSeries.rate.",  # noqa: E501
        extras={"minimum": 1},
    )
    sensors: tuple[dx.Embed[SensorSpec], ...] | None = dx.field(
        default_factory=tuple,
        description="Physical sensor geometry. BIDS electrodes.tsv and optodes.tsv plus NWB's electrodes DynamicTable. Separate from channels because the two are not in bijection: an fNIRS channel is a source-detector-wavelength triple and a bipolar iEEG channel is a difference of two contacts.",  # noqa: E501
    )
    sourceOptodeCount: int | None = dx.field(
        default=None,
        description="BIDS NIRSSourceOptodeCount, REQUIRED in the NIRS sidecar.",
        extras={"minimum": 0},
    )


class SyncInfo(dx.Model):
    """How one media stream aligns to a session's shared time base. This is what makes multimodal Layers possible: the 0.8.0 chain is annotationLayer.expression (single, REQUIRED) to expression.mediaRef (single), so a session of two cameras, a lapel microphone, an EEG cap and an eye tracker is unrepresentable, and parentMediaRef with startOffsetMs expresses excerpt-of, a different relation."""  # noqa: E501

    clockSource: str | None = dx.field(
        default=None,
        description="How alignment was established (fallback when the Uri is unavailable). A consumer needs it to know how far to trust a cross-stream anchor: a hardware trigger and a clapperboard differ by three orders of magnitude.",  # noqa: E501
        extras={
            "knownValues": (
                "session-master",
                "shared-trigger",
                "ltc-timecode",
                "clapperboard",
                "audio-cross-correlation",
                "ptp",
                "ntp",
                "manual",
                "unsynchronized",
                "unknown",
            ),
            "maxLength": 64,
        },
    )
    clockSourceUri: str | None = dx.field(
        default=None,
        description="AT-URI of the synchronization method definition node (typeDef of `sync-method`).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    driftPartsPerBillion: int | None = dx.field(
        default=None,
        description="Signed measured drift against the session master. Independent oscillators diverge measurably over an hour, and zero is a claim rather than a safe default.",  # noqa: E501
    )
    offsetNanos: int | None = dx.field(
        default=None,
        description="Signed offset from session time zero to this stream's first sample. Session-relative, never UTC-epoch. Negative when the stream began before the origin, which is normal for a continuously running amplifier and which BIDS StartTime explicitly permits.",  # noqa: E501
    )
    sessionRef: str = dx.field(
        description="AT-URI of the pub.layers.acquisition.session whose clock this stream is expressed against.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    syncChannel: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="The channel carrying the shared sync signal, when clockSource is shared-trigger.",  # noqa: E501
    )
    syncUncertaintyNanos: int | None = dx.field(
        default=None,
        description="Worst-case alignment error. Bounds how finely a cross-stream anchor may honestly be read.",  # noqa: E501
        extras={"minimum": 0},
    )


class VideoInfo(dx.Model):
    """Composable video metadata. Attach to any media record representing video content."""  # noqa: E501

    aspectRatio: str | None = dx.field(
        default=None,
        description="Display aspect ratio (e.g., '16:9', '4:3', '1:1').",
        extras={"maxLength": 32},
    )
    bitRate: int | None = dx.field(
        default=None,
        description="Video bitrate in bits per second.",
        extras={"minimum": 1},
    )
    codec: str | None = dx.field(
        default=None,
        description="Video codec identifier (e.g., 'h264', 'h265', 'vp9', 'av1', 'prores').",  # noqa: E501
        extras={"maxLength": 128},
    )
    colorSpace: str | None = dx.field(
        default=None,
        description="Color space.",
        extras={
            "knownValues": (
                "rgb",
                "yuv420",
                "yuv422",
                "yuv444",
                "grayscale",
            ),
            "maxLength": 32,
        },
    )
    frameRate: int | None = dx.field(
        default=None,
        description="Frame rate scaled by 100 (e.g., 2997 = 29.97fps). Avoids floats.",
        extras={"minimum": 1},
    )
    height: int | None = dx.field(
        default=None,
        description="Height in pixels.",
        extras={"minimum": 1},
    )
    scanType: str | None = dx.field(
        default=None,
        description="Scan type. Affects frame extraction for annotation.",
        extras={
            "knownValues": (
                "progressive",
                "interlaced",
            ),
            "maxLength": 32,
        },
    )
    width: int | None = dx.field(
        default=None,
        description="Width in pixels.",
        extras={"minimum": 1},
    )


class VolumeInfo(dx.Model):
    """Composable metadata for volumetric imaging: fMRI runs, structural scans, and derived masks or parcellations. Volumes almost always exceed the blob cap, so externalUri plus contentDigest is the normal carriage rather than the exception."""  # noqa: E501

    coordinateSystem: dx.Embed[CoordinateSystem] | None = dx.field(
        default=None,
        description="Stereotaxic frame the voxel grid is expressed against.",
    )
    device: dx.Embed[DeviceInfo] | None = dx.field(
        default=None,
        description="Scanner hardware.",
    )
    dimX: int | None = dx.field(
        default=None,
        description="Voxel grid extent along X.",
        extras={"minimum": 1},
    )
    dimY: int | None = dx.field(
        default=None,
        description="Voxel grid extent along Y.",
        extras={"minimum": 1},
    )
    dimZ: int | None = dx.field(
        default=None,
        description="Voxel grid extent along Z.",
        extras={"minimum": 1},
    )
    echoTimeNanos: int | None = dx.field(
        default=None,
        description="BIDS EchoTime.",
        extras={"minimum": 0},
    )
    flipAngleMicrodegrees: int | None = dx.field(
        default=None,
        description="BIDS FlipAngle.",
        extras={"minimum": 0},
    )
    format: str | None = dx.field(
        default=None,
        description="Container format slug (fallback when formatUri unavailable). Wire-format code.",  # noqa: E501
        extras={
            "knownValues": (
                "nifti-1",
                "nifti-2",
                "cifti-2",
                "gifti",
                "dicom",
                "mgz",
                "minc",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    formatUri: str | None = dx.field(
        default=None,
        description="AT-URI of the volume container format definition node.",
        extras={"format": "at-uri"},
    )
    phaseEncodingDirection: str | None = dx.field(
        default=None,
        description="BIDS PhaseEncodingDirection (j, j-). Wire-format code.",
        extras={"maxLength": 8},
    )
    repetitionTimeNanos: int | None = dx.field(
        default=None,
        description="BIDS RepetitionTime.",
        extras={"minimum": 0},
    )
    sliceEncodingDirection: str | None = dx.field(
        default=None,
        description="BIDS SliceEncodingDirection (k, k-). Wire-format code.",
        extras={"maxLength": 8},
    )
    sliceTimingNanos: tuple[int, ...] | None = dx.field(
        default_factory=tuple,
        description="Per-slice acquisition offsets within one TR. BIDS SliceTiming.",
    )
    volumeCount: int | None = dx.field(
        default=None,
        description="Volumes in the run. Bounds pub.layers.defs#signalSpan.volumeIndexEnd.",  # noqa: E501
        extras={"minimum": 0},
    )
    volumeKind: str = dx.field(
        description="Volume kind slug (fallback when the Uri is unavailable). BIDS suffix plus datatype.",  # noqa: E501
        extras={
            "knownValues": (
                "bold",
                "anatomical-t1",
                "anatomical-t2",
                "dwi",
                "fieldmap",
                "perfusion",
                "mask",
                "statistical-map",
                "parcellation",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    volumeKindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the volume kind definition node.",
        extras={"format": "at-uri"},
    )
    voxelSizeXNanometres: int | None = dx.field(
        default=None,
        description="Voxel edge length along X, in nanometres.",
        extras={"minimum": 1},
    )
    voxelSizeYNanometres: int | None = dx.field(
        default=None,
        description="Voxel edge length along Y, in nanometres.",
        extras={"minimum": 1},
    )
    voxelSizeZNanometres: int | None = dx.field(
        default=None,
        description="Voxel edge length along Z, in nanometres.",
        extras={"minimum": 1},
    )


class Media(dx.Model):
    """A media source record (audio, video, image, document, signal, motion, or volume) that can be referenced by expressions and annotations. Modality-specific metadata lives in composable info objects; a single medium may carry several (a motion stream also carries signalInfo)."""  # noqa: E501

    access: dx.Embed[AccessCondition] | None = dx.field(
        default=None,
        description="Conditions under which the bytes may be obtained. Distinct from licensing, which governs what may be done with them, and from consent, which governs the person they came from. All three must hold.",  # noqa: E501
    )
    audio: dx.Embed[AudioInfo] | None = dx.field(
        default=None,
        description="Audio-specific metadata. Present for audio files and videos with audio tracks.",  # noqa: E501
    )
    blob: BlobRef | None = dx.field(
        default=None,
        description="The media blob. Signal, motion and volume containers (EDF, BDF, FIF, EEGLAB SET, BrainVision, SNIRF, NWB, NIfTI, ASC, C3D, TRC) travel as application/octet-stream or application/x-hdf5, with the concrete container named by the relevant info block's format field. Content above maxSize MUST use externalUri.",  # noqa: E501
    )
    contentDigest: dx.Embed[ContentDigest] | None = dx.field(
        default=None,
        description="Hash over the referenced bytes. The only integrity guarantee available for externalUri carriage, and therefore expected whenever externalUri is used without a blob. A record CID pins the record, not the bytes behind a URI.",  # noqa: E501
    )
    createdAt: datetime = dx.field(
        description="Timestamp at which this media record was created.",
        extras={"format": "datetime"},
    )
    description: str | None = dx.field(
        default=None,
        description="Free-text description of this medium.",
        extras={"maxLength": 10000},
    )
    document: dx.Embed[DocumentInfo] | None = dx.field(
        default=None,
        description="Document-specific metadata. Present for scanned documents, manuscripts, etc.",  # noqa: E501
    )
    durationMs: int | None = dx.field(
        default=None,
        description="Duration in milliseconds (for audio/video).",
        extras={"minimum": 0},
    )
    durationNanos: int | None = dx.field(
        default=None,
        description="Duration in nanoseconds; authoritative over durationMs where both are present. Milliseconds round away whole samples at 2048 Hz and above.",  # noqa: E501
        extras={"minimum": 0},
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Eprint records (papers/preprints) describing or associated with this media.",  # noqa: E501
    )
    externalUri: str | None = dx.field(
        default=None,
        description="URI for externally hosted media.",
        extras={"format": "uri", "maxLength": 2048},
    )
    eyeTracking: dx.Embed[EyeTrackingInfo] | None = dx.field(
        default=None,
        description="Eye-tracking specifics, carried alongside signal. A nested block rather than an eighth carrier kind, because BIDS types eye-tracking as a physiological recording.",  # noqa: E501
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features: recording conditions, speaker metadata, quality metrics, consent, etc.",  # noqa: E501
    )
    fileSizeBytes: int | None = dx.field(
        default=None,
        description="File size in bytes.",
        extras={"minimum": 0},
    )
    image: dx.Embed[ImageInfo] | None = dx.field(
        default=None,
        description="Still-image metadata. Photographs previously had to borrow videoInfo.",  # noqa: E501
    )
    kind: str = dx.field(
        description="Media kind slug (fallback when kindUri unavailable). Names the CARRIER only. The instrument is named by signalInfo.modalityUri, which resolves into the same node set as pub.layers.judgment.defs#recordingMethod.methodUri; one media kind per instrument would fork that vocabulary across two lexicons.",  # noqa: E501
        extras={
            "knownValues": (
                "audio",
                "video",
                "image",
                "document",
                "signal",
                "motion",
                "volume",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the media kind definition node (typeDef of `media-kind` at layers-core.ontology.layers.pub). Names the carrier; the instrument-level modality is named by signalInfo.modalityUri, whose nodes reach their carrier node by parentTypeRef. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references.",
    )
    languageRefs: tuple[dx.Embed[LanguageRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Structured language references, for varieties a BCP-47 tag cannot name. Each entry's tag SHOULD also appear in languages.",  # noqa: E501
    )
    languages: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="BCP-47 language tags this record covers. Empty when language is unspecified or unknown.",  # noqa: E501
    )
    licensing: dx.Embed[Licensing] | None = dx.field(
        default=None,
        description="Distribution licensing terms governing this media (supports dual/multi/component licensing). Canonical license for the media; the consent.license feature, when present, records per-clip consent terms.",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who created/uploaded this media record, with what tool.",  # noqa: E501
    )
    mimeType: str | None = dx.field(
        default=None,
        description="MIME type of the carried bytes.",
        extras={"maxLength": 128},
    )
    motion: dx.Embed[MotionInfo] | None = dx.field(
        default=None,
        description="Motion-capture and articulography metadata, carried alongside signal.",  # noqa: E501
    )
    parentMediaRef: str | None = dx.field(
        default=None,
        description="AT-URI of the parent media record this excerpt/clip was extracted from.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    participantRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="AT-URIs of the pub.layers.acquisition.participant records this recording captures. On the record rather than inside four sibling info blocks, because a speech recording and a face video capture participants too, and four copies with no precedence rule is a conflict waiting to be written.",  # noqa: E501
    )
    sessionRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.acquisition.session this medium is a stream of. Every stream of one synchronized recording carries the same sessionRef. parentMediaRef expresses excerpt-of and MUST NOT be used for synchronization.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    signal: dx.Embed[SignalInfo] | None = dx.field(
        default=None,
        description="Sampled time-series metadata (EEG, MEG, iEEG, fNIRS, EMG, ECG, EDA, respiration, gaze, mouse and key logging).",  # noqa: E501
    )
    startOffsetMs: int | None = dx.field(
        default=None,
        description="Offset in milliseconds where this excerpt starts within the parent media. Used with parentMediaRef.",  # noqa: E501
        extras={"minimum": 0},
    )
    stream: dx.Embed[ObjectRef] | None = dx.field(
        default=None,
        description="The session stream this medium fills, as an objectRef whose recordRef is sessionRef and whose objectId is the stream's uuid. Replaces a session-local label string: a name join cannot be validated and cannot be detected as dangling.",  # noqa: E501
    )
    sync: dx.Embed[SyncInfo] | None = dx.field(
        default=None,
        description="How this stream aligns to its session's shared time base.",
    )
    title: str | None = dx.field(
        default=None,
        description="Human-readable title for this medium.",
        extras={"maxLength": 1024},
    )
    video: dx.Embed[VideoInfo] | None = dx.field(
        default=None,
        description="Video-specific metadata. Present for video files and image sequences.",  # noqa: E501
    )
    volume: dx.Embed[VolumeInfo] | None = dx.field(
        default=None,
        description="Volumetric imaging metadata.",
    )
