# generated by lairs gen; do not edit
# lexicon tree hash c579e63d3ffd0d55171eeeef7fbee9254e184419ebdfbb1bddc4807310069330
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.ontology lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import Constraint, FeatureMap, KnowledgeRef

__all__ = [
    "Ontology",
    "RoleSlot",
    "TypeDef",
]


class Ontology(dx.Model):
    """An annotation ontology: a collection of typed definitions (entity types, situation types, role types, relation types) that together form a complete annotation framework."""  # noqa: E501

    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    description: str | None = dx.field(
        default=None,
        description="Detailed description of the ontology's purpose and scope.",
        extras={"maxLength": 10000},
    )
    domain: str | None = dx.field(
        default=None,
        description="Domain slug (fallback when domainUri unavailable).",
        extras={
            "knownValues": (
                "general",
                "biomedical",
                "legal",
                "financial",
                "news",
                "social-media",
                "scientific",
                "intelligence",
                "dialogue",
                "multimodal",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    domainUri: str | None = dx.field(
        default=None,
        description="AT-URI of the domain definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references grounding this ontology.",
    )
    name: str = dx.field(
        description="Human-readable name for this ontology.",
        extras={"maxLength": 512},
    )
    parentRef: str | None = dx.field(
        default=None,
        description="Reference to a parent ontology this one extends.",
        extras={"format": "at-uri"},
    )
    personaRef: str | None = dx.field(
        default=None,
        description="Reference to the persona that created/owns this ontology.",
        extras={"format": "at-uri"},
    )
    version: str | None = dx.field(
        default=None,
        description="Semantic version string.",
        extras={"maxLength": 32},
    )


class RoleSlot(dx.Model):
    """A role/argument slot in a frame or situation type definition. Structurally parallel to pub.layers.resource#slot: both represent named positions with type constraints. roleSlot is ontology-level (what roles a frame type allows); resource slot is template-level (what variables a template exposes)."""  # noqa: E501

    collectionRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.resource#collection constraining allowed fillers.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    constraints: tuple[dx.Embed[Constraint], ...] | None = dx.field(
        default_factory=tuple,
        description="Declarative constraints on fillers of this role (e.g., selectional restrictions, agreement requirements).",  # noqa: E501
    )
    defaultValue: str | None = dx.field(
        default=None,
        description="Default filler value if not explicitly filled.",
        extras={"maxLength": 4096},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features for this role slot (e.g., semantic type, animacy preference, optionality conditions).",  # noqa: E501
    )
    fillerTypeRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="References to allowed filler types (pub.layers.ontology#typeDef AT-URIs).",  # noqa: E501
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
    )
    required: bool | None = dx.field(
        default=None,
        description="Whether this role is obligatory.",
    )
    roleDescription: str | None = dx.field(
        default=None,
        extras={"maxLength": 2048},
    )
    roleName: str = dx.field(
        description="The role label (e.g., Agent, Patient, Theme, ARG0).",
        extras={"maxLength": 256},
    )


class TypeDef(dx.Model):
    """A type definition within an ontology. Covers entity types, situation types, role types, and relation types in a single unified model."""  # noqa: E501

    allowedRoles: tuple[dx.Embed[RoleSlot], ...] | None = dx.field(
        default_factory=tuple,
        description="For frame/situation types: the roles that can be filled.",
    )
    allowedValues: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="For attribute types: enumerated allowed values.",
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    gloss: str | None = dx.field(
        default=None,
        description="Rich text definition/gloss of this type. May include references to other types and Wikidata entities, following FOVEA conventions.",  # noqa: E501
        extras={"maxLength": 10000},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph groundings (Wikidata, chive.pub, FrameNet, etc.).",
    )
    name: str = dx.field(
        description="The type name/label.",
        extras={"maxLength": 512},
    )
    ontologyRef: str = dx.field(
        description="The ontology this type belongs to.",
        extras={"format": "at-uri"},
    )
    parentTypeRef: str | None = dx.field(
        default=None,
        description="Reference to a parent type (for type hierarchies/inheritance).",
        extras={"format": "at-uri"},
    )
    typeKind: str = dx.field(
        description="Type kind slug (fallback when typeKindUri unavailable).",
        extras={
            "knownValues": (
                "entity-type",
                "situation-type",
                "role-type",
                "relation-type",
                "attribute-type",
            ),
            "maxLength": 128,
        },
    )
    typeKindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the type kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
