# generated by lairs gen; do not edit
# lexicon tree hash c579e63d3ffd0d55171eeeef7fbee9254e184419ebdfbb1bddc4807310069330
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.persona lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import FeatureMap, KnowledgeRef
from lairs.records.blobref import BlobRef

__all__ = [
    "Persona",
]


class Persona(dx.Model):
    """A persona representing an annotator's role, expertise, and interpretive framework."""  # noqa: E501

    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    description: str | None = dx.field(
        default=None,
        description="Description of the persona's role, expertise, and information needs.",  # noqa: E501
        extras={"maxLength": 10000},
    )
    domain: str | None = dx.field(
        default=None,
        description="Domain slug (fallback when domainUri unavailable).",
        extras={
            "knownValues": (
                "linguistics",
                "nlp",
                "biomedical",
                "legal",
                "intelligence",
                "social-science",
                "humanities",
                "custom",
            ),
            "maxLength": 256,
        },
    )
    domainUri: str | None = dx.field(
        default=None,
        description="AT-URI of the domain definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features: expertise level, certification, language proficiency, inter-annotator reliability, etc.",  # noqa: E501
    )
    guidelines: str | None = dx.field(
        default=None,
        description="Annotation guidelines text.",
        extras={"maxLength": 100000},
    )
    guidelinesBlob: BlobRef | None = dx.field(
        default=None,
        description="Annotation guidelines document.",
    )
    guidelinesFormat: str | None = dx.field(
        default=None,
        description="Format of the guidelines text, so consumers can render it safely without sniffing. Defaults to plain when omitted.",  # noqa: E501
        extras={
            "knownValues": (
                "plain",
                "html",
                "markdown",
            ),
            "maxLength": 32,
        },
    )
    kind: str | None = dx.field(
        default=None,
        description="Persona kind slug (fallback when kindUri unavailable).",
        extras={
            "knownValues": (
                "human-annotator",
                "ml-model",
                "guidelines-persona",
                "expert-panel",
                "crowd-worker",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the persona kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references (e.g., ORCID, institutional identifiers, Wikidata for organizations).",  # noqa: E501
    )
    name: str = dx.field(
        description="The persona name (e.g., 'Syntactician', 'Intelligence Analyst', 'Biomedical NER Annotator').",  # noqa: E501
        extras={"maxLength": 256},
    )
    ontologyRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Ontologies this persona uses for annotation.",
    )
    parentRef: str | None = dx.field(
        default=None,
        description="AT-URI of a parent persona this one specializes (e.g., 'Biomedical NER Annotator' specializes 'NER Annotator').",  # noqa: E501
        extras={"format": "at-uri"},
    )
