# generated by lairs gen; do not edit
# lexicon tree hash c579e63d3ffd0d55171eeeef7fbee9254e184419ebdfbb1bddc4807310069330
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.resource lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AnnotationMetadata,
    Constraint,
    FeatureMap,
    KnowledgeRef,
)

__all__ = [
    "Collection",
    "CollectionMembership",
    "Entry",
    "Filling",
    "MweComponent",
    "Slot",
    "SlotFilling",
    "Template",
    "TemplateComposition",
    "TemplateMember",
]


class Collection(dx.Model):
    """A named collection of linguistic resource entries. Abstract enough to represent bead Lexicons, FrameNet frame inventories, PropBank frame files, WordNet synsets, morphological paradigm tables, gazetteers, stop-word lists, etc."""  # noqa: E501

    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    description: str | None = dx.field(
        default=None,
        extras={"maxLength": 10000},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    kind: str | None = dx.field(
        default=None,
        description="Collection kind slug (fallback when kindUri unavailable).",
        extras={
            "knownValues": (
                "lexicon",
                "frame-inventory",
                "gazetteer",
                "paradigm",
                "stop-list",
                "stimulus-pool",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the collection kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
    )
    language: str | None = dx.field(
        default=None,
        description="BCP-47 language tag.",
        extras={"maxLength": 32},
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who curated this collection, with what tool.",
    )
    name: str = dx.field(
        description="Human-readable name for this collection.",
        extras={"maxLength": 512},
    )
    ontologyRef: str | None = dx.field(
        default=None,
        description="Reference to a pub.layers.ontology defining the type system for entries in this collection.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    version: str | None = dx.field(
        default=None,
        description="Version string (e.g., 'FrameNet 1.7', 'PropBank 3.4').",
        extras={"maxLength": 64},
    )


class CollectionMembership(dx.Model):
    """Links an entry to a collection. Separate record enables many-to-many relationships (an entry can belong to multiple collections) and decentralized curation (anyone can propose membership)."""  # noqa: E501

    collectionRef: str = dx.field(
        description="AT-URI of the collection.",
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    entryRef: str = dx.field(
        description="AT-URI of the entry.",
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who added this entry to this collection, when, with what tool.",  # noqa: E501
    )
    ordinal: int | None = dx.field(
        default=None,
        description="Optional ordering position within the collection.",
        extras={"minimum": 0},
    )


class MweComponent(dx.Model):
    """A component of a multi-word expression entry."""

    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    form: str = dx.field(
        description="Surface form of this component.",
        extras={"maxLength": 1024},
    )
    isHead: bool | None = dx.field(
        default=None,
        description="Whether this component is the head of the MWE.",
    )
    lemma: str | None = dx.field(
        default=None,
        description="Lemma/citation form of this component.",
        extras={"maxLength": 1024},
    )
    position: int | None = dx.field(
        default=None,
        description="Position in the MWE (0-based).",
        extras={"minimum": 0},
    )


class Entry(dx.Model):
    """A linguistic resource entry: a lexical item, frame element filler, morphological paradigm cell, or any atomic unit in a structured linguistic collection. Abstract enough to represent bead LexicalItems, FrameNet lexical units, PropBank rolesets, WordNet synset members, morphological paradigm cells, etc."""  # noqa: E501

    components: tuple[dx.Embed[MweComponent], ...] | None = dx.field(
        default_factory=tuple,
        description="For multi-word expressions: the component words.",
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features: pos, morphological features, frequency, register, etc.",  # noqa: E501
    )
    form: str = dx.field(
        description="Surface form or string representation.",
        extras={"maxLength": 4096},
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph groundings (WordNet synset, FrameNet lexical unit, Wikidata, etc.).",  # noqa: E501
    )
    language: str | None = dx.field(
        default=None,
        description="BCP-47 language tag.",
        extras={"maxLength": 32},
    )
    lemma: str | None = dx.field(
        default=None,
        description="Canonical/citation form.",
        extras={"maxLength": 1024},
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who created this entry, with what tool, under what persona.",  # noqa: E501
    )
    mweKind: str | None = dx.field(
        default=None,
        description="MWE kind slug (fallback when mweKindUri unavailable).",
        extras={
            "knownValues": (
                "compound",
                "phrasal-verb",
                "idiom",
                "light-verb",
                "named-entity",
                "collocation",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    mweKindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the MWE kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    ontologyTypeRef: str | None = dx.field(
        default=None,
        description="Reference to a pub.layers.ontology#typeDef classifying this entry.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    sourceRef: str | None = dx.field(
        default=None,
        description="AT-URI of the source record this entry was derived from (e.g., an annotation, another entry).",  # noqa: E501
        extras={"format": "at-uri"},
    )


class SlotFilling(dx.Model):
    """A single slot→filler mapping in a filled template. The filler can be an entry reference (AT-URI to a resource entry), a literal value, or both (entry reference with rendered surface form)."""  # noqa: E501

    entryRef: str | None = dx.field(
        default=None,
        description="AT-URI of the resource entry filling this slot.",
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    literalValue: str | None = dx.field(
        default=None,
        description="Literal string value for this slot (used when no entry reference is needed, or as override).",  # noqa: E501
        extras={"maxLength": 4096},
    )
    renderedForm: str | None = dx.field(
        default=None,
        description="The surface form as rendered in the filled text (may differ from entry form due to morphological inflection, agreement, etc.).",  # noqa: E501
        extras={"maxLength": 4096},
    )
    slotName: str = dx.field(
        description="Name of the slot being filled (must match a slot name in the template).",  # noqa: E501
        extras={"maxLength": 256},
    )


class Filling(dx.Model):
    """A filled template: a template with all slots mapped to specific fillers, producing a rendered text. Generalizes bead's FilledTemplate and Item. The rendered text can optionally be materialized as a pub.layers.expression for annotation. Fillings are composable: they reference templates, entries, and communications via AT-URIs."""  # noqa: E501

    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    expressionRef: str | None = dx.field(
        default=None,
        description="AT-URI of the pub.layers.expression materializing this filling (for annotation).",  # noqa: E501
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features: model name for MLM filling, seed for random, solver stats for CSP, etc.",  # noqa: E501
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references (e.g., generation model in a KB, sampling distribution, linguistic theory motivating the filling).",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: what tool/process generated this filling.",
    )
    renderedText: str | None = dx.field(
        default=None,
        description="The fully rendered text after substitution.",
        extras={"maxLength": 100000},
    )
    slotFillings: tuple[dx.Embed[SlotFilling], ...] = dx.field(
        description="The slot→filler mappings.",
    )
    strategy: str | None = dx.field(
        default=None,
        description="Filling strategy slug (fallback when strategyUri unavailable).",
        extras={
            "knownValues": (
                "exhaustive",
                "random",
                "stratified",
                "mlm",
                "csp",
                "mixed",
                "manual",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    strategyUri: str | None = dx.field(
        default=None,
        description="AT-URI of the filling strategy definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    templateRef: str = dx.field(
        description="AT-URI of the template being filled.",
        extras={"format": "at-uri"},
    )


class Slot(dx.Model):
    """A named variable slot in a template. Generalizes bead's Slot (template variable position with constraints and defaults), ontology roleSlots (argument positions with filler type constraints), and similar parameterized positions in any structured linguistic pattern. Slots are composable: they can reference collections of allowed fillers, ontology types, or express arbitrary constraints."""  # noqa: E501

    collectionRef: str | None = dx.field(
        default=None,
        description="AT-URI of a resource collection constraining allowed fillers.",
        extras={"format": "at-uri"},
    )
    constraints: tuple[dx.Embed[Constraint], ...] | None = dx.field(
        default_factory=tuple,
        description="Slot-level constraints (e.g., 'self.pos == \"VERB\"', 'self.features.number == \"sg\"').",  # noqa: E501
    )
    defaultValue: str | None = dx.field(
        default=None,
        description="Default filler value if not explicitly filled.",
        extras={"maxLength": 4096},
    )
    description: str | None = dx.field(
        default=None,
        extras={"maxLength": 2048},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    fillerTypeRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Multiple allowed filler type references (disjunctive constraint).",
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
    )
    name: str = dx.field(
        description="Slot name (used as placeholder key in template text, e.g., 'subject', 'verb', 'arg0').",  # noqa: E501
        extras={"maxLength": 256},
    )
    ontologyTypeRef: str | None = dx.field(
        default=None,
        description="AT-URI of a pub.layers.ontology#typeDef constraining the filler type.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    required: bool | None = dx.field(
        default=None,
        description="Whether this slot must be filled.",
    )


class Template(dx.Model):
    """A parameterized text template with named variable slots. Generalizes bead's Template (text pattern with {slotName} placeholders, slot definitions, and cross-slot constraints) and similar pattern structures used for stimulus generation, item construction, data augmentation, and controlled natural language. Templates are composable: they can reference ontologies, collections, and other templates."""  # noqa: E501

    constraints: tuple[dx.Embed[Constraint], ...] | None = dx.field(
        default_factory=tuple,
        description="Cross-slot constraints (e.g., agreement, semantic compatibility). These apply across multiple slots in this template.",  # noqa: E501
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    experimentRef: str | None = dx.field(
        default=None,
        description="Reference to the experiment this template was designed for.",
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features: measureType, taskType, category, domain, etc.",  # noqa: E501
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
    )
    language: str | None = dx.field(
        default=None,
        description="BCP-47 language tag.",
        extras={"maxLength": 32},
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
        description="Provenance: who designed this template, with what tool.",
    )
    name: str | None = dx.field(
        default=None,
        description="Human-readable template name.",
        extras={"maxLength": 512},
    )
    ontologyRef: str | None = dx.field(
        default=None,
        description="Reference to the ontology defining the type system used by this template.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    slots: tuple[dx.Embed[Slot], ...] = dx.field(
        description="The named slots in this template.",
    )
    text: str = dx.field(
        description="Template text with {slotName} placeholders (e.g., '{subject} {verb} the {object}').",  # noqa: E501
        extras={"maxLength": 50000},
    )


class TemplateMember(dx.Model):
    """A member in a template composition. References either a template or a nested composition."""  # noqa: E501

    compositionRef: str | None = dx.field(
        default=None,
        description="AT-URI of a nested templateComposition (for tree structures).",
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    label: str | None = dx.field(
        default=None,
        description="Optional label for this member (e.g., 'context', 'target', 'filler').",  # noqa: E501
        extras={"maxLength": 256},
    )
    ordinal: int = dx.field(
        description="Position in the composition (0-based).",
        extras={"minimum": 0},
    )
    templateRef: str | None = dx.field(
        default=None,
        description="AT-URI of a template record.",
        extras={"format": "at-uri"},
    )


class TemplateComposition(dx.Model):
    """A composition of templates (sequence, tree, or other structure). Used for multi-part stimuli, template hierarchies, and complex item construction."""  # noqa: E501

    compositionType: str = dx.field(
        description="Composition type slug (fallback when compositionTypeUri unavailable).",  # noqa: E501
        extras={
            "knownValues": (
                "sequence",
                "tree",
                "parallel",
                "alternation",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    compositionTypeUri: str | None = dx.field(
        default=None,
        description="AT-URI of the composition type definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    experimentRef: str | None = dx.field(
        default=None,
        description="Reference to the experiment this composition was designed for.",
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
    )
    members: tuple[dx.Embed[TemplateMember], ...] = dx.field(
        description="Ordered members of this composition.",
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
