# generated by lairs gen; do not edit
# lexicon tree hash cedfb9f34cc55fb5be1abb81dda63fd6a6671af2efd6a5e5923fca0c77ba0fd1
# ruff: noqa: N815, TC001, TC003

"""Generated models for the pub.layers.segmentation lexicon namespace.

This module is emitted by ``lairs gen`` from the vendored lexicons and
must not be edited by hand. Each class mirrors a lexicon record, object,
or union definition.
"""

from datetime import datetime

import didactic.api as dx

from lairs.records._generated.defs import (
    AnnotationMetadata,
    FeatureMap,
    KnowledgeRef,
    Licensing,
    ReproducibilityInfo,
    Span,
    TemporalSpan,
    Uuid,
)

__all__ = [
    "Segmentation",
    "Token",
    "Tokenization",
]


class Token(dx.Model):
    """A single token within a tokenization."""

    temporalSpan: dx.Embed[TemporalSpan] | None = dx.field(
        default=None,
    )
    text: str | None = dx.field(
        default=None,
        description="The surface form of the token.",
        extras={"maxLength": 4096},
    )
    textSpan: dx.Embed[Span] | None = dx.field(
        default=None,
        description="UTF-8 byte offsets into the expression text.",
    )
    tokenIndex: int = dx.field(
        description="Position of this token in the tokenization (0-based).",
        extras={"minimum": 0},
    )


class Tokenization(dx.Model):
    """An ordered sequence of tokens for an expression or sub-expression. Multiple tokenizations can coexist for the same expression (e.g., whitespace vs. BPE vs. morphological), enabling interlinear glossing, alternative segmentation strategies, or multi-granularity analysis."""  # noqa: E501

    expressionRef: str | None = dx.field(
        default=None,
        description="Reference to the specific sub-expression this tokenization covers (e.g., a sentence-level expression). If absent, covers the entire expression referenced by the segmentation record.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    kind: str = dx.field(
        description="Tokenization kind slug (fallback when kindUri unavailable).",
        extras={
            "knownValues": (
                "whitespace",
                "penn-treebank",
                "bpe",
                "sentencepiece",
                "character",
                "morphological",
                "custom",
            ),
            "maxLength": 128,
        },
    )
    kindUri: str | None = dx.field(
        default=None,
        description="AT-URI of the tokenization kind definition node. Community-expandable via knowledge graph.",  # noqa: E501
        extras={"format": "at-uri"},
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
    tokens: tuple[dx.Embed[Token], ...] = dx.field(
        description="The ordered token sequence.",
    )
    uuid: dx.Embed[Uuid] = dx.field(
        description="generated field",
    )


class Segmentation(dx.Model):
    """A segmentation of an expression into tokenizations. Structural hierarchy (sections, sentences, paragraphs) is expressed via expression records with parentRef; this record provides the token-level decomposition."""  # noqa: E501

    createdAt: datetime = dx.field(
        extras={"format": "datetime"},
    )
    eprintRefs: tuple[str, ...] | None = dx.field(
        default_factory=tuple,
        description="Eprint records (papers/preprints) describing or associated with this segmentation.",  # noqa: E501
    )
    expression: str = dx.field(
        description="Reference to the expression this segmentation applies to.",
        extras={"format": "at-uri"},
    )
    features: dx.Embed[FeatureMap] | None = dx.field(
        default=None,
        description="Open-ended features (e.g., tokenizer version, parameters, language model used).",  # noqa: E501
    )
    knowledgeRefs: tuple[dx.Embed[KnowledgeRef], ...] | None = dx.field(
        default_factory=tuple,
        description="Knowledge graph references (e.g., tokenizer algorithm, sentence splitting model).",  # noqa: E501
    )
    licensing: dx.Embed[Licensing] | None = dx.field(
        default=None,
        description="Licensing terms governing this segmentation (supports dual/multi/component licensing).",  # noqa: E501
    )
    metadata: dx.Embed[AnnotationMetadata] | None = dx.field(
        default=None,
    )
    reproducibility: dx.Embed[ReproducibilityInfo] | None = dx.field(
        default=None,
        description="How this segmentation was produced (code, commit, command, environment, seed).",  # noqa: E501
    )
    tokenizations: tuple[dx.Embed[Tokenization], ...] = dx.field(
        description="The tokenizations in this segmentation. Each tokenization can optionally scope to a sub-expression via expressionRef.",  # noqa: E501
    )
